/**
 * Hand-curated aliases for Ask OnCo entity resolution: the ways people actually write a record's name in a
 * question that the record's own `name`, `aka`, `brand` and `code` fields do not cover ("triple-negative"
 * for tnbc, "Enhertu" is already a brand, "CT scan" for ct). Keys are record ids; a vitest checks that every
 * id exists. Matching is case-insensitive and hyphen/space tolerant (see ask-index.ts), so one spelling of
 * each variant is enough. Pure data, browser-safe.
 */
export const ASK_ALIASES: Record<string, string[]> = {
  // ---- cancers ----
  tnbc: ["triple-negative", "triple-negative breast cancer", "triple-negative breast", "mTNBC", "metastatic TNBC", "early TNBC", "TNBC"],
  "breast-hr-positive": ["HR-positive breast cancer", "HR+ breast cancer", "HR+/HER2- breast cancer", "hormone-positive breast cancer", "hormone receptor-positive breast cancer", "ER-positive breast cancer", "ER+ breast cancer", "luminal breast cancer", "hormone-positive", "oestrogen receptor-positive breast cancer"],
  "breast-her2-positive": ["HER2-positive breast cancer", "HER2+ breast cancer", "HER2-positive"],
  nsclc: ["NSCLC", "non-small cell lung cancer", "lung cancer", "lung adenocarcinoma", "EGFR-mutant lung cancer", "EGFR-mutant NSCLC", "advanced lung cancer", "metastatic lung cancer"],
  sclc: ["SCLC", "small-cell lung cancer", "small cell lung cancer"],
  colorectal: ["CRC", "mCRC", "bowel cancer", "colon cancer", "rectal cancer", "colorectal cancers"],
  pancreatic: ["pancreatic cancer", "PDAC", "pancreas cancer", "cancer of the pancreas", "metastatic pancreatic cancer"],
  prostate: ["mCRPC", "castration-resistant prostate cancer", "mHSPC", "advanced prostate cancer"],
  urothelial: ["bladder cancer", "urothelial cancer", "urothelial carcinoma", "mUC", "advanced bladder cancer"],
  hcc: ["HCC", "liver cancer", "hepatocellular carcinoma"],
  rcc: ["RCC", "kidney cancer", "renal cell carcinoma", "renal cancer"],
  glioblastoma: ["GBM", "glioblastoma", "glioma", "gliomas", "brain tumour", "brain tumor", "brain cancer"],
  aml: ["AML", "acute myeloid leukemia", "acute myeloid leukaemia"],
  "all-leukemia": ["ALL", "acute lymphoblastic leukaemia", "acute lymphoblastic leukemia"],
  cll: ["CLL", "chronic lymphocytic leukemia"],
  cml: ["CML", "chronic myeloid leukemia", "chronic myeloid leukaemia"],
  dlbcl: ["DLBCL", "large B-cell lymphoma", "diffuse large B-cell lymphoma", "LBCL"],
  "multiple-myeloma": ["myeloma"],
  "hodgkin-lymphoma": ["Hodgkin lymphoma", "Hodgkin's lymphoma", "Hodgkin"],
  "follicular-lymphoma": ["follicular lymphoma"],
  "head-and-neck": ["head and neck cancer", "HNSCC", "head and neck squamous cell carcinoma", "throat cancer", "oral cancer"],
  gastric: ["gastric cancer", "stomach cancer", "GEJ cancer", "gastro-oesophageal junction cancer", "gastroesophageal cancer", "gastro-oesophageal cancer"],
  esophageal: ["oesophageal cancer", "esophageal cancer"],
  ovarian: ["ovarian cancer", "ovarian cancers"],
  endometrial: ["endometrial cancer", "uterine cancer", "womb cancer"],
  cervical: ["cervical cancer", "cervix cancer"],
  melanoma: ["advanced melanoma", "metastatic melanoma", "malignant melanoma"],
  thyroid: ["thyroid cancer"],
  sarcoma: ["sarcoma", "sarcomas", "soft-tissue sarcoma", "soft tissue sarcoma"],
  mesothelioma: ["mesothelioma"],
  cholangiocarcinoma: ["bile duct cancer", "biliary tract cancer", "biliary cancer", "cholangiocarcinoma"],
  neuroblastoma: ["neuroblastoma"],
  medulloblastoma: ["medulloblastoma"],
  "cutaneous-scc": ["cutaneous squamous cell carcinoma"],
  "basal-cell-carcinoma": ["basal cell carcinoma"],
  "merkel-cell-carcinoma": ["Merkel cell carcinoma"],
  "mantle-cell-lymphoma": ["mantle cell lymphoma", "MCL"],
  mds: ["MDS", "myelodysplastic syndrome", "myelodysplastic syndromes"],
  testicular: ["testicular cancer", "germ cell tumour", "germ cell tumor"],
  gist: ["GIST", "gastrointestinal stromal tumour", "gastrointestinal stromal tumor"],
  neuroendocrine: ["neuroendocrine tumour", "neuroendocrine tumours", "neuroendocrine tumor", "neuroendocrine tumors", "NET", "NETs"],

  // ---- technologies ----
  "checkpoint-inhibitor": ["checkpoint inhibitor", "checkpoint inhibitors", "immune checkpoint inhibitor", "immune checkpoint inhibitors", "PD-1 inhibitor", "PD-1 inhibitors", "PD-L1 inhibitor", "PD-L1 inhibitors", "anti-PD-1", "anti-PD-L1", "checkpoint blockade", "immune checkpoint blockade", "ICI", "ICIs"],
  adc: ["ADC", "ADCs", "antibody-drug conjugate", "antibody-drug conjugates", "antibody drug conjugate", "antibody drug conjugates"],
  "car-t": ["CAR-T", "CAR T", "CAR-T cells", "CAR T cells", "CAR T-cell therapy", "CAR-T therapy", "chimeric antigen receptor T cells", "CAR-T cell therapy"],
  "bispecific-adc": ["bispecific ADC", "bispecific ADCs", "biparatopic ADC"],
  "bispecific-antibody": ["bispecific", "bispecifics", "bispecific antibody", "bispecific antibodies", "T-cell engager", "T cell engager", "T-cell engagers", "BiTE", "BiTEs"],
  ct: ["CT scan", "CT scans", "computed tomography", "CAT scan"],
  pet: ["PET scan", "PET scans", "positron emission tomography"],
  "fdg-pet": ["FDG PET", "FDG-PET", "FDG scan", "FDG"],
  "fapi-pet": ["FAPI PET", "FAPI-PET", "FAPI PET scan", "FAPI"],
  "trop2-pet": ["TROP2 PET", "TROP2 PET scan", "TROP2 PET tracer"],
  "psma-pet": ["PSMA PET scan", "PSMA-PET"],
  "protac-degrader": ["PROTAC", "PROTACs", "protein degrader", "protein degraders", "targeted protein degradation", "molecular glue", "molecular glues", "degrader", "degraders"],
  "parp-inhibitor": ["PARP inhibitor", "PARP inhibitors", "PARPi"],
  "cdk46-inhibitor": ["CDK4/6 inhibitor", "CDK4/6 inhibitors", "CDK4/6"],
  "kras-inhibitors": ["KRAS inhibitor", "KRAS inhibitors", "KRAS G12C inhibitor", "KRAS G12C inhibitors"],
  "radioligand-therapy": ["radioligand therapy", "radioligand", "radioligands", "radiopharmaceutical therapy", "lutetium therapy", "PSMA radioligand", "radiopharmaceuticals"],
  "neoantigen-mrna-vaccine": ["personalised cancer vaccine", "personalized cancer vaccine", "personalised cancer vaccines", "personalized cancer vaccines", "mRNA cancer vaccine", "personalised mRNA vaccine", "personalized mRNA vaccine", "personalised mRNA cancer vaccine", "personalized mRNA cancer vaccine", "individualised neoantigen therapy", "cancer vaccine", "cancer vaccines", "neoantigen vaccine", "personalised vaccines", "personalized vaccines"],
  "in-vivo-car-t": ["in vivo CAR-T", "in vivo CAR T"],
  "flash-rt": ["FLASH", "FLASH radiotherapy", "FLASH RT"],
  mced: ["multi-cancer early detection", "multi-cancer blood test", "MCED test", "cancer screening blood test", "blood test for cancer"],
  "liquid-biopsy": ["liquid biopsy", "liquid biopsies", "ctDNA test", "ctDNA testing"],
  "mrd-testing": ["MRD test", "MRD testing", "molecular residual disease", "ctDNA MRD", "leftover disease"],
  "til-therapy": ["TIL therapy", "TIL therapies", "tumour-infiltrating lymphocyte therapy"],
  "germline-testing": ["germline testing", "germline genetic testing", "hereditary testing", "genetic testing", "BRCA testing", "inherited testing"],
  "scalp-cooling": ["scalp cooling", "cold cap", "cold caps"],
  "exercise-oncology": ["exercise oncology", "structured exercise", "exercise programme", "exercise program"],
  "proton-therapy": ["proton therapy", "proton beam", "proton beam therapy", "protons"],
  brachytherapy: ["internal radiotherapy", "seed implants"],
  "digital-pathology-ai": ["AI pathology", "digital pathology"],
  "pathology-foundation-model": ["pathology foundation model", "pathology foundation models", "foundation models in pathology", "foundation model"],
  optune: ["tumour treating fields", "tumor treating fields", "TTFields", "Optune"],
  "monoclonal-antibody": ["monoclonal antibody", "monoclonal antibodies"],
  "endocrine-therapy": ["endocrine therapy", "hormone-blocking", "hormone blockers"],
  mammography: ["mammogram", "mammograms", "mammography"],
  "low-dose-ct-screening": ["lung screening", "lung cancer screening", "low-dose CT"],
  "colorectal-screening": ["bowel screening", "colorectal screening", "colon cancer screening"],
  "hpv-vaccine": ["HPV vaccine", "HPV vaccination"],
  sbrt: ["SBRT", "SABR", "stereotactic radiotherapy", "stereotactic body radiotherapy"],
  cgp: ["comprehensive genomic profiling", "genomic profiling", "tumour sequencing", "tumor sequencing", "NGS panel"],
  "ai-trial-matching": ["trial matching", "trial-matching", "find a clinical trial", "finding a trial"],

  // ---- products ----
  "trastuzumab-deruxtecan": ["T-DXd", "DS-8201", "Enhertu"],
  "sacituzumab-govitecan": ["Trodelvy", "IMMU-132"],
  "datopotamab-deruxtecan": ["Datroway", "Dato-DXd", "datopotamab"],
  "sacituzumab-tirumotecan": ["sac-TMT", "SKB264", "MK-2870"],
  "izalontamab-brengitecan": ["iza-bren", "izabren", "BL-B01D1"],
  pembrolizumab: ["Keytruda", "pembro"],
  nivolumab: ["Opdivo", "nivo"],
  ipilimumab: ["Yervoy", "ipi"],
  atezolizumab: ["Tecentriq"],
  durvalumab: ["Imfinzi"],
  olaparib: ["Lynparza"],
  osimertinib: ["Tagrisso"],
  pluvicto: ["Pluvicto", "lutetium PSMA", "Lu-PSMA", "177Lu-PSMA-617", "lutetium-177 PSMA", "Lu-177 PSMA", "PSMA-617", "lutetium PSMA-617"],
  lutathera: ["Lutathera", "lutetium dotatate", "177Lu-DOTATATE"],
  daraxonrasib: ["RMC-6236", "Rasonque"],
  amivantamab: ["Rybrevant"],
  lifileucel: ["Amtagvi"],
  tarlatamab: ["Imdelltra"],
  revumenib: ["Revuforj"],
  ivonescimab: ["ivonescimab", "AK112"],
  imatinib: ["Gleevec", "Glivec"],
  venetoclax: ["Venclexta", "Venclyxto"],
  "enfortumab-vedotin": ["Padcev", "EV"],
  "trastuzumab-emtansine": ["Kadcyla", "T-DM1"],
  galleri: ["Galleri test", "Galleri"],
  "oncotype-dx": ["Oncotype", "21-gene test", "21-gene assay", "Oncotype DX"],
  abemaciclib: ["Verzenio"],
  ribociclib: ["Kisqali"],
  palbociclib: ["Ibrance"],
  sotorasib: ["Lumakras", "Lumykras"],
  adagrasib: ["Krazati"],
  lorlatinib: ["Lorbrena"],
  alectinib: ["Alecensa"],
  dostarlimab: ["Jemperli"],
  vepdegestrant: ["vepdegestrant", "ARV-471"],
  tazemetostat: ["Tazverik"],
  zolbetuximab: ["Vyloy"],

  // ---- targets ----
  her2: ["HER2", "ERBB2", "HER-2", "HER2-positive tumours"],
  pdl1: ["PD-L1"],
  pd1: ["PD-1"],
  trop2: ["TROP2", "TROP-2", "Trop-2"],
  kras: ["KRAS", "KRAS G12C", "KRAS G12D", "RAS"],
  egfr: ["EGFR", "EGFR mutation", "EGFR-mutant"],
  brca: ["BRCA", "BRCA1", "BRCA2", "BRCA1/2", "BRCA mutation", "BRCA-mutated", "germline BRCA"],
  psma: ["PSMA"],
  "estrogen-receptor": ["oestrogen receptor", "estrogen receptor", "ESR1", "ER-positive", "ER+"],
  "androgen-receptor": ["androgen receptor"],
  bcma: ["BCMA"],
  cd19: ["CD19"],
  cd20: ["CD20"],
  tigit: ["TIGIT"],
  bcl2: ["BCL-2", "BCL2"],
  menin: ["menin"],
  "cldn18-2": ["Claudin 18.2", "CLDN18.2", "claudin"],
  dll3: ["DLL3"],
  nectin4: ["Nectin-4", "nectin4"],
  "cdk4-6": ["CDK4", "CDK6"],

  // ---- terms ----
  "her2-low": ["HER2-low", "HER2 low", "HER2-ultralow", "HER2 ultralow", "HER2-zero", "HER2-low breast cancer", "HER2-low breast cancers"],
  pcr: ["pCR", "pathologic complete response", "pathological complete response", "complete pathological response"],
  rcb: ["residual cancer burden", "RCB"],
  "hazard-ratio": ["hazard ratio", "hazard ratios"],
  "cold-vs-hot": ["hot tumour", "cold tumour", "hot tumor", "cold tumor", "hot versus cold", "hot vs cold", "hot and cold tumours", "hot and cold tumors"],
  irae: ["irAE", "irAEs", "immune-related adverse events", "immune-related adverse event", "immune-related side effects", "immune side effects", "immunotherapy side effects"],
  theranostics: ["theranostic"],
  "synthetic-lethality": ["synthetically lethal", "synthetic lethal"],
  "accelerated-approval": ["accelerated approvals"],
  "bystander-effect": ["bystander effect", "bystander killing"],
  dar: ["drug-to-antibody ratio", "drug to antibody ratio", "DAR"],
  cps: ["CPS", "combined positive score", "PD-L1 CPS"],
  tils: ["TILs", "TIL score", "tumour-infiltrating lymphocytes", "tumor-infiltrating lymphocytes"],
  ctdna: ["ctDNA", "circulating tumour DNA", "circulating tumor DNA"],
  mrd: ["MRD", "minimal residual disease", "molecular residual disease"],
  msi: ["MSI-H", "dMMR", "mismatch repair deficient", "microsatellite instability", "MSI-high"],
  tmb: ["TMB", "tumour mutational burden", "tumor mutational burden"],
  hrd: ["HRD", "homologous recombination deficiency"],
  ild: ["ILD", "interstitial lung disease", "pneumonitis"],
  crs: ["CRS", "cytokine release syndrome"],
  ppv: ["positive predictive value", "PPV"],
  "oncogene-addiction": ["oncogene addiction", "oncogene-addicted"],
  "tumour-agnostic": ["tumour-agnostic", "tumor-agnostic", "tissue-agnostic"],
  "adc-sequencing": ["ADC sequencing", "sequencing ADCs", "second ADC", "ADC after ADC"],

  // ---- pathways ----
  "pi3k-akt-mtor": ["PI3K/AKT/mTOR", "PI3K pathway", "PI3K-AKT-mTOR", "PI3K/AKT/mTOR pathway", "mTOR pathway", "PI3K"],
  "ras-mapk": ["MAPK pathway", "RAS/MAPK", "RAS-MAPK", "MAPK", "BRAF/MEK", "BRAF and MEK"],
  "cgas-sting": ["cGAS-STING", "cGAS–STING", "STING pathway", "cGAS-STING pathway", "STING"],
  "pd1-checkpoint": ["PD-1 checkpoint", "PD-1/PD-L1 axis", "PD-1 pathway"],
  ddr: ["DNA damage response", "DDR"],
  emt: ["epithelial-mesenchymal transition", "EMT"],

  // ---- companies and institutions ----
  mskcc: ["MSK", "MSKCC", "Memorial Sloan Kettering", "Sloan Kettering"],
  "md-anderson": ["MD Anderson", "M.D. Anderson"],
  "dana-farber": ["Dana-Farber", "Dana Farber"],
  "royal-marsden": ["Royal Marsden"],
  "gustave-roussy": ["Gustave Roussy", "IGR"],
  merck: ["Merck", "MSD", "Merck & Co"],
  bms: ["BMS", "Bristol Myers Squibb", "Bristol-Myers Squibb", "Bristol Myers"],
  "roche-genentech": ["Roche", "Genentech"],
  gilead: ["Gilead", "Gilead Sciences", "Kite", "Kite Pharma"],
  pfizer: ["Pfizer", "Seagen"],
  "daiichi-sankyo": ["Daiichi", "Daiichi Sankyo"],
  astrazeneca: ["AstraZeneca", "Astra Zeneca"],
  "eli-lilly": ["Lilly", "Eli Lilly"],
  "johnson-johnson": ["J&J", "Johnson & Johnson", "Janssen"],
  novartis: ["Novartis"],
  amgen: ["Amgen"],
  "revolution-medicines": ["Revolution Medicines", "RevMed"],
  systimmune: ["SystImmune", "Biokin", "Sichuan Biokin"],
  "kelun-biotech": ["Kelun", "Kelun-Biotech", "Sichuan Kelun"],
  akeso: ["Akeso"],
  "summit-therapeutics": ["Summit", "Summit Therapeutics"],
  grail: ["GRAIL"],
  nci: ["NCI", "National Cancer Institute"],
  "clinicaltrials-gov": ["ClinicalTrials.gov", "clinicaltrials gov"],
  depmap: ["DepMap", "Cancer Dependency Map"],
  oncokb: ["OncoKB"],
  nccn: ["NCCN", "NCCN guidelines"],

  // ---- complementary and supportive approaches (graded records; the grade travels in the Ask index) ----
  "acupuncture-nausea": ["acupuncture", "acupressure", "acupuncture for nausea", "P6 acupressure", "acupressure wristbands", "Sea-Bands"],
  "acupuncture-aromatase-inhibitor-arthralgia": ["acupuncture for joint pain", "acupuncture for arthralgia", "acupuncture for aromatase inhibitor joint pain"],
  "acupuncture-hot-flushes": ["acupuncture for hot flushes", "acupuncture for hot flashes"],
  "acupuncture-xerostomia": ["acupuncture for dry mouth"],
  "acupuncture-chemotherapy-neuropathy": ["acupuncture for neuropathy"],
  "mindfulness-based-interventions": ["mindfulness", "MBSR", "mindfulness-based stress reduction", "meditation"],
  "cbt-insomnia-cancer": ["CBT-I", "CBT for insomnia", "cognitive behavioural therapy for insomnia", "cognitive behavioral therapy for insomnia", "CBT", "sleep therapy"],
  "cbt-fatigue-distress": ["CBT for fatigue", "cognitive behavioural therapy", "cognitive behavioral therapy"],
  "yoga-cancer": ["yoga"],
  "tai-chi-qigong": ["tai chi", "qigong", "qi gong"],
  "hypnosis-cancer-care": ["hypnosis", "hypnotherapy", "clinical hypnosis"],
  "relaxation-guided-imagery": ["guided imagery", "relaxation training", "relaxation techniques"],
  "music-therapy-cancer": ["music therapy"],
  "dance-movement-therapy": ["dance therapy", "dance movement therapy"],
  "peer-support-groups": ["support groups", "support group", "peer support"],
  "massage-therapy-cancer": ["massage", "massage therapy", "oncology massage"],
  "aromatherapy-cancer": ["aromatherapy", "essential oils"],
  "reflexology-cancer": ["reflexology"],
  "reiki-energy-therapies": ["reiki", "healing touch", "energy healing", "energy therapy", "therapeutic touch"],
  "ginger-nausea": ["ginger"],
  "curcumin-turmeric": ["curcumin", "turmeric"],
  "green-tea-egcg": ["green tea", "EGCG", "green tea extract"],
  "american-ginseng-fatigue": ["ginseng", "American ginseng", "Wisconsin ginseng"],
  "melatonin-cancer": ["melatonin"],
  "omega3-epa-cachexia": ["fish oil", "omega-3", "omega 3", "EPA supplements"],
  "probiotics-treatment-diarrhoea": ["probiotics", "probiotic"],
  "glutamine-mucositis-neuropathy": ["glutamine", "L-glutamine"],
  "honey-radiation-mucositis": ["honey", "manuka honey"],
  "mistletoe-extracts": ["mistletoe", "mistletoe therapy", "mistletoe extract", "Iscador", "Helixor", "Viscum album"],
  "high-dose-vitamin-c": ["vitamin C", "high-dose vitamin C", "intravenous vitamin C", "IV vitamin C", "ascorbate"],
  "psk-krestin-adjuvant": ["PSK", "Krestin", "polysaccharide K"],
  "medicinal-mushrooms-reishi-turkey-tail": ["medicinal mushrooms", "reishi", "turkey tail", "shiitake", "mushroom supplements", "mushrooms"],
  "traditional-chinese-herbal-medicine": ["Chinese herbal medicine", "traditional Chinese medicine", "TCM", "Chinese herbs"],
  "ayurvedic-medicine-cancer": ["Ayurveda", "Ayurvedic medicine", "Ayurvedic"],
  "homeopathy-cancer": ["homeopathy", "homeopathic"],
  "st-johns-wort-interaction": ["St John's wort", "St. John's wort", "St Johns wort", "Hypericum"],
  "cannabinoids-nausea": ["medical cannabis", "cannabis", "cannabinoids", "dronabinol", "nabilone", "medical marijuana", "marijuana", "THC"],
  "cannabinoids-pain-appetite": ["CBD", "CBD oil", "cannabis oil", "cannabis for pain", "Rick Simpson oil"],
  "oral-cryotherapy-mucositis": ["ice chips", "oral cryotherapy", "sucking ice", "ice during chemo"],
  "frozen-gloves-compression-taxane": ["frozen gloves", "frozen socks", "cold gloves", "compression gloves"],
  "photobiomodulation-mucositis": ["photobiomodulation", "low-level laser", "low-level laser therapy", "LLLT"],
  "hyperbaric-oxygen-radiation-injury": ["hyperbaric oxygen", "HBOT", "hyperbaric oxygen therapy"],
  "lymphoedema-decongestive-therapy": ["lymphoedema treatment", "lymphedema treatment", "compression sleeve", "decongestive therapy", "lymphatic drainage"],
  "minoxidil-chemotherapy-alopecia": ["minoxidil", "Rogaine"],
  "bimatoprost-eyelash-regrowth": ["bimatoprost", "Latisse"],
  "wigs-cranial-prosthesis": ["wigs", "wig", "cranial prosthesis", "head coverings"],
  "alternative-medicine-instead-of-treatment": ["alternative medicine", "alternative therapy", "alternative therapies", "alternative treatment", "alternative treatments", "refusing chemotherapy", "instead of chemotherapy", "natural cures", "natural cure"],
  "laetrile-amygdalin": ["laetrile", "amygdalin", "vitamin B17", "B17", "apricot kernels", "apricot kernel"],
  "gerson-therapy-detox-regimens": ["Gerson therapy", "Gerson", "coffee enemas", "coffee enema", "detox", "detox diet", "juicing"],
  "shark-cartilage": ["shark cartilage"],
  "hydrazine-sulfate": ["hydrazine sulfate", "hydrazine sulphate", "hydrazine"],
  antineoplastons: ["antineoplastons", "Burzynski", "Burzynski clinic"],
  "black-salve-escharotics": ["black salve", "escharotic", "bloodroot"],
  "fenbendazole-ivermectin-repurposing-claims": ["fenbendazole", "ivermectin", "dog dewormer", "Joe Tippens", "mebendazole", "repurposed cures"],
  "essiac-herbal-cancer-cures": ["Essiac", "Hoxsey", "herbal cancer cure", "herbal cancer cures", "Essiac tea"],
  "ketogenic-diet-glioblastoma": ["ketogenic diet", "keto diet", "keto", "ketogenic", "ketogenic diets"],
  "dietary-supplements-treatment-interactions": ["supplements during chemotherapy", "antioxidant supplements", "dietary supplements", "supplements"],

  // ---- investors ----
  "y-combinator": ["YC", "YCombinator", "Y-Combinator", "YC-backed"],
  "a16z-bio-health": ["a16z", "Andreessen Horowitz", "a16z Bio + Health", "a16z bio"],
  "arch-venture-partners": ["ARCH", "ARCH Venture", "Arch Ventures"],
  "flagship-pioneering": ["Flagship"],
  "third-rock-ventures": ["Third Rock"],
  orbimed: ["OrbiMed Advisors"],
  "ra-capital": ["RA Capital"],
  gv: ["Google Ventures", "GV"],
  "polaris-partners": ["Polaris"],
  "versant-ventures": ["Versant"],
  "sofinnova-partners": ["Sofinnova"],
  "frazier-life-sciences": ["Frazier"],
  "bain-capital-life-sciences": ["Bain Capital"],
  "deerfield-management": ["Deerfield"],
  "foresite-capital": ["Foresite"],
  "lux-capital": ["Lux"],
  "khosla-ventures": ["Khosla"],
  "mpm-bioimpact": ["MPM Capital", "MPM"],
  jjdc: ["JJDC", "Johnson & Johnson Innovation"],
  "msd-global-health-innovation-fund": ["Merck GHI", "MSD GHI", "Merck Global Health Innovation"],
  "lls-therapy-acceleration-program": ["LLS TAP", "Leukemia & Lymphoma Society", "LLS"],
  "mmrf-myeloma-investment-fund": ["MMRF", "Myeloma Investment Fund"],
  "acs-brightedge": ["BrightEdge"],
  tcgx: ["TCG Crossover"],
  "ecor1-capital": ["EcoR1"],
  "section-32": ["S32"],
  "perceptive-advisors": ["Perceptive"],
  "casdin-capital": ["Casdin"],
  "f-prime-capital": ["F-Prime"],
  bpifrance: ["BPI France"],

  // ---- journals (ordinary-word names need a "journal" cue; abbreviations come from aka) ----
  "lancet-oncology": ["Lancet Oncology"],
  lancet: ["Lancet"],
  nejm: ["New England Journal"],
  blood: ["Blood journal", "the journal Blood", "Blood (journal)"],
  "cancer-wiley": ["the journal Cancer", "Cancer journal", "Cancer (journal)"],
  nature: ["Nature journal", "the journal Nature"],
  science: ["Science journal", "the journal Science"],
  cell: ["Cell journal", "the journal Cell"],
  jco: ["Journal of Clinical Oncology"],

  // ---- fronts (weak on their own; they anchor roadmap questions) ----
  surgery: ["cancer surgery", "surgical oncology", "surgery", "operations"],
  radiation: ["radiation therapy", "radiotherapy", "radiation oncology"],
  chemotherapy: ["chemotherapy", "chemo"],
  diagnostics: ["cancer diagnostics", "diagnostics", "biomarker testing"],
  "early-detection": ["early detection", "cancer screening", "screening"],
  "targeted-therapy": ["targeted therapy", "targeted therapies", "precision oncology"],
  "cell-therapy": ["cell therapy", "cell therapies"],
  radiopharma: ["radiopharmaceuticals", "radiopharma"],
  hormonal: ["hormonal therapy", "hormone therapy"],
  epigenetics: ["epigenetics", "epigenetic therapy"],
  "supportive-care": ["supportive care", "survivorship"],
  "ai-computation": ["AI in oncology", "artificial intelligence", "machine learning", "AI"],
  "drug-discovery": ["drug discovery"],
  prevention: ["cancer prevention", "prevention", "risk reduction"],
  "nutrition-lifestyle": ["diet and exercise", "lifestyle", "nutrition"],
  devices: ["medical devices", "physical therapies"],

  // ---- roadmaps ----
  "radiation-roadmap": ["radiotherapy roadmap", "radiation roadmap", "radiation therapy roadmap"],
  "surgery-roadmap": ["surgery roadmap", "surgical roadmap"],
  "chemotherapy-roadmap": ["chemotherapy roadmap", "chemo roadmap"],
  "hormonal-therapy-roadmap": ["hormonal therapy roadmap", "hormone therapy roadmap", "endocrine therapy roadmap"],
  "epigenetics-roadmap": ["epigenetics roadmap", "epigenetic therapy roadmap"],
  "survivorship-roadmap": ["survivorship roadmap", "supportive care roadmap"],
  "ai-oncology-roadmap": ["AI in oncology roadmap", "AI roadmap", "artificial intelligence roadmap"],
  "nutrition-lifestyle-roadmap": ["nutrition roadmap", "diet roadmap", "lifestyle roadmap", "exercise roadmap"],
  "devices-roadmap": ["devices roadmap", "medical devices roadmap"],
  "targeted-therapy-roadmap": ["targeted therapy roadmap"],
  "drug-discovery-roadmap": ["drug discovery roadmap"],
  "prevention-roadmap": ["prevention roadmap", "cancer prevention roadmap"],
  "paediatric-oncology-roadmap": ["paediatric oncology roadmap", "pediatric oncology roadmap", "paediatric oncology", "pediatric oncology", "childhood cancer roadmap", "children's cancer roadmap"],
  "global-access-roadmap": ["global access roadmap", "affordability roadmap", "access roadmap"],
  "trial-modernisation-roadmap": ["trial modernisation roadmap", "trial modernization roadmap", "clinical trials roadmap", "trials roadmap"],
  "diagnostics-roadmap": ["diagnostics roadmap"],
  "adc-generations": ["ADC roadmap"],
  "radiopharma-roadmap": ["radiopharmaceutical roadmap", "radiopharma roadmap", "radioligand roadmap"],
  "cell-therapy-roadmap": ["cell therapy roadmap", "CAR-T roadmap"],
  "immunotherapy-roadmap": ["immunotherapy roadmap"],
  "kras-roadmap": ["KRAS roadmap"],
  "early-detection-roadmap": ["early detection roadmap", "screening roadmap"],
  "molecular-imaging-roadmap": ["imaging roadmap", "molecular imaging roadmap"],
  "tnbc-history": ["TNBC roadmap"],
  "trop2-adc-roadmap": ["TROP2 roadmap", "TROP2 ADC roadmap"],

  // ---- India and China ----
  "talicabtagene-autoleucel": ["tali-cel", "NexCAR-19", "Nex CAR19", "NexCAR 19"],
  "varnimcabtagene-autoleucel": ["var-cel"],
  cervavac: ["Indian HPV vaccine", "India's HPV vaccine", "Serum Institute HPV vaccine"],
  "low-dose-nivolumab-tmh": ["low-dose nivolumab", "low dose nivolumab", "low-dose immunotherapy trial"],
  "osmanabad-hpv-screening": ["Osmanabad", "Osmanabad trial"],
  "kerala-oral-screening": ["Kerala oral screening", "Kerala trial", "Trivandrum oral cancer screening"],
  "metro-plus-varanasi": ["METRO PLUS"],
  "tata-memorial": ["Tata Memorial", "TMH", "Tata Memorial Centre", "Tata Memorial Hospital", "Tata Memorial Center"],
  junshi: ["Junshi Biosciences"],
  "nhs-targeted-lung-health-check": ["Targeted Lung Health Check", "lung health check", "TLHC"],
  "race-for-children-act": ["RACE Act", "RACE for Children"],
};

/**
 * Ordinary words that are also record names or aliases. Never used as entity anchors in a question,
 * whatever the kind (cf. STOP in term-hover.tsx).
 */
export const ASK_STOP = new Set([
  "cancer", "cancers", "cell", "cells", "blood", "brain", "skin", "bone", "liver", "lung", "breast", "colon", "the", "and", "for", "with",
  "breast cancer", "breast cancers", "solid tumours", "solid tumors", "tumour", "tumor", "tumours", "tumors", "patients", "patient", "oncology", "cancer care",
  "uk", "eu", "us", "usa", "united kingdom", "european union", "america", "europe", "australia", "germany", "france", "india", "korea", "canada",
  "science", "nature", "cell press", "target", "targets", "trial", "trials", "study", "group", "center", "centre", "institute", "hospital",
  "university", "foundation", "society", "china", "japan", "europe", "united states", "other", "protein", "gene", "genes", "dose",
  "stage", "grade", "cure", "cost", "price", "net", "nets", "her", "therap", "phikon", "gears", "hibou", "musk", "chief",
]);

/**
 * Record names that are also ordinary words (mostly trial acronyms and regulators). They resolve only when the
 * question writes them in capitals ("VISION", "FDA") or follows them with "trial" or "study" ("the Vision trial").
 */
export const ASK_CASE_SENSITIVE = new Set([
  "vision", "destiny", "ascent", "monarch", "paradigm", "checkmate", "keynote", "impassion", "javelin", "pacific", "aurora", "orbit",
  "spotlight", "clear", "match", "action", "crown", "emerald", "prima", "solo", "select", "reflect", "compete", "motion", "atlas", "voyager",
  "insight", "convert", "columbus", "bond", "fires", "hilo", "glow", "sano", "splash", "amplify", "tower", "sunrise", "sunlight", "cabinet",
  "harmoni", "dream", "libretto", "magnitude", "belinda", "indigo", "pluto", "merlin", "midnight", "mirai", "flash", "sting", "ras", "ev",
  "io", "ici", "all", "protect", "embark", "arches", "latitude", "profound", "propel", "resonate", "sequoia", "stellar", "transform",
  "felix", "captivate", "alpine", "astra", "cross", "defi", "extreme", "frontmind", "invictus", "maps", "mirasol", "outback", "persephone",
  "perseus", "polo", "rainbow", "ruby", "sharp", "stampede", "thor", "vital", "whel", "lidera", "liger", "rathl", "gemelli", "candiolo",
  "big", "pumch", "smc", "sheba", "hcg", "falp", "arc", "fda", "ema", "nice", "tga", "pbac", "mhra", "pmda", "nci", "net", "mcl", "who", "has", "arc", "cancer", "aims", "gog", "big", "cog", "trog", "ion", "ash", "asco", "esmo", "sso", "eha", "ecco", "estro", "astro", "snmmi",
  // investors, fronts and codes that are also words or short tokens
  "yc", "gv", "ai", "arch", "lux", "flagship", "polaris", "versant", "perceptive", "mpm", "s32", "lls", "psk", "cbt", "tcm", "thc", "cbd", "keto", "detox", "b17", "tmh", "race act",
]);
