/** Site information architecture: six groups, each with a landing page and its pages. Used by the header, footer, landing pages, and home. */
/** `regions`: show only when the reader has chosen one of these countries (Global view shows everything). */
export type NavItem = { href: string; label: string; blurb: string; regions?: Array<"US" | "EU" | "UK" | "JP" | "CN" | "AU" | "IN"> };
/** `short` is an optional shorter label for the desktop header bar only; the drawer, footer and landing pages use `label`. */
export type NavGroup = { id: string; label: string; short?: string; href: string; blurb: string; items: NavItem[] };

export const NAV_GROUPS: NavGroup[] = [
  {
    id: "find", label: "Start here", href: "/find/", blurb: "Begin from your situation or your question: your cancer, your biomarkers, what to compare, where the cancer is in the body.",
    items: [
      { href: "/explore/", label: "Explore", blurb: "Pick a cancer, switch kind, get a ranked and sortable list." },
      { href: "/tagged/", label: "Tags", blurb: "Every tag with its count; each opens a filterable table of the records carrying it, whatever their kind." },
      { href: "/search/", label: "Search", blurb: "Word and concept search side by side, each result explaining why it matched." },
      { href: "/path/", label: "Path finder", blurb: "How any two objects are related: shortest routes with every relationship named." },
      { href: "/for-me/", label: "For me", blurb: "Choose your cancer type(s) and see what works and what could work." },
      { href: "/navigator/", label: "Navigator", blurb: "Standard of care for your stage, what you have tried, cautions, next options, trials near you." },
      { href: "/biomarker-matrix/", label: "Biomarker matrix", blurb: "Every biomarker against every cancer: approved products in your region versus trials, one grid." },
      { href: "/calculators/", label: "Calculators", blurb: "BSA, Calvert, creatinine clearance, ANC, corrected calcium, RECIST 1.1, anthracycline dose, dose banding." },
      { href: "/interactions/", label: "Interactions", blurb: "Pick two or more drugs and see flagged pairs: CYP3A4, QT, PPIs, P-gp, bleeding, plus food and organ flags." },
      { href: "/tools/", label: "Decision aids", blurb: "Answer a few questions from a report and read the guideline statement that applies, quoted with its source: gallbladder polyps, incidental gallbladder cancer, cancers compared." },
      { href: "/irae/", label: "irAE guide", blurb: "Checkpoint-inhibitor toxicity by organ and grade: hold, steroids, escalation, rechallenge. Printable." },
      { href: "/tumor-board/", label: "Tumour board", blurb: "Tick biomarkers and alterations, get matched options and cautions." },
      { href: "/compare/", label: "Compare", blurb: "Up to five products, technologies, targets, trials, or cancers side by side, differences highlighted." },
      { href: "/pivot/", label: "Landscape grid", blurb: "Count products, trials, or technologies by cancer, target, treatment type, or company in one grid." },
      { href: "/rankings/", label: "Rankings", blurb: "League tables computed from the corpus: cancers by trials, targets by products, companies by approvals, trials by enrolment, each stating its basis." },
      { href: "/timeline/", label: "Timeline", blurb: "Every dated fact on one timeline: the shape of the whole field, what that shape shows, and a page for every year." },
      { href: "/years/", label: "Years", blurb: "One page per year: everything the corpus dates to it, from approvals to landmarks, each line linking to the record it came from." },
      { href: "/query/", label: "Query", blurb: "Build a graph query and get a table." },
      { href: "/graph/", label: "Graph explorer", blurb: "Navigate the knowledge graph visually." },
      { href: "/saved/", label: "Saved", blurb: "Your saved table views and watched pages, with what changed since you looked. Stored in your browser only." },
      { href: "/body/", label: "Body map", blurb: "Start from where the cancer is." },
    ],
  },
  {
    id: "map", label: "Cancers & treatments", href: "/map/", blurb: "Every cancer, every way to detect and treat it, every drug, target, trial, and term. One page each, in plain English first.",
    items: [
      { href: "/cancers/", label: "Cancers", blurb: "State of the art, standard of care, history, pipeline." },
      { href: "/cancers/map/", label: "Cancer map", blurb: "Every cancer type on one layered map: organ system to cancer to subtype, with a cancer under more than one node where it belongs to both. Badges count trials, products, approvals or ideas." },
      { href: "/fronts/", label: "Fronts", blurb: "The fronts of the war: imaging to cell therapy." },
      { href: "/technologies/", label: "Technologies", blurb: "Every way we see, measure, or attack a tumour." },
      { href: "/targets/", label: "Targets", blurb: "The molecules drugs and tracers aim at." },
      { href: "/biomarkers/", label: "Biomarkers", blurb: "PD-L1 CPS, HER2 IHC 3+, MSI-high: each readout under its gene, with the thresholds approvals use and the tests that measure it." },
      { href: "/drugs/", label: "Treatments & tests", blurb: "Approved and pipeline products, with rotating molecules." },
      { href: "/pathways/", label: "Pathways", blurb: "Signalling circuits, drawn and explained." },
      { href: "/checkpoints/", label: "Checkpoint families", blurb: "One word, two biologies: immune checkpoints on the synapse and cell-cycle gates on the ring, each member with its partner, expression, drugs and approvals." },
      { href: "/virotherapy/", label: "Oncolytic viruses", blurb: "Why a virus kills a cancer cell and not its neighbour, every approved product with what its trial really showed, and the failures." },
      { href: "/dossiers/", label: "Target dossiers", blurb: "Everything about a target on one page: biology, prevalence, hotspots, products by phase, trials, resistance, assays, models, open questions, external ids." },
      { href: "/pathway-drugs/", label: "Pathway-to-drug matrix", blurb: "Which pathway nodes have a drug, at what phase, and which druggable nodes have none." },
      { href: "/tumour-testing/", label: "Tumour sequencing tests", blurb: "BostonGene, Tempus, Foundation Medicine, Caris, Guardant and the rest side by side: tissue or blood, panel or exome, what the report returns, and regulatory status where certain." },
      { href: "/models/", label: "Models & datasets", blurb: "Foundation models and the datasets they train on, with parameters, weights, licence and benchmarks." },
      { href: "/machines/", label: "Machines", blurb: "The scanners, accelerators, robots and ablation devices hospitals use against cancer: what each does, its advantages and limits, who makes it, and which centres run the rare ones." },
      { href: "/open-questions/", label: "Open questions", blurb: "Unresolved questions per target and technology: why open, what would answer them, who acts." },
      { href: "/preclinical-models/", label: "Preclinical models", blurb: "Cell lines with Cellosaurus and DepMap ids, PDX banks, mouse models and organoids per cancer and target." },
      { href: "/regimens/", label: "Regimens", blurb: "Named regimens with doses, days, cycles, emetogenicity and G-CSF need; calendar strip per regimen." },
      { href: "/sequencing/", label: "Lines of therapy", blurb: "Per cancer, the standard of care by line and biomarker subgroup, with sequence and caution pairings." },
      { href: "/staging/", label: "Staging & risk scores", blurb: "TNM, FIGO, Lugano, BCLC, R-ISS and interactive IPI, IMDC, CLL-IPI, Child-Pugh, Khorana scorers." },
      { href: "/journeys/", label: "Treatment journeys", blurb: "What the next twelve months look like for a cancer at a stage, phase by phase, with the decision points." },
      { href: "/atlas/", label: "Atlas", blurb: "Organ schematics with subsites and node stations, and where each cancer spreads." },
      { href: "/molecules/", label: "Molecule gallery", blurb: "Every product with a 3D structure, filterable by modality, payload, target and status." },
      { href: "/mechanics/", label: "Mechanics of cancer", blurb: "How cancer works, drawn stage by stage, with the drugs that act on each mechanism." },
      { href: "/prevalence/", label: "Prevalence", blurb: "How common each target is in each cancer." },
      { href: "/trials/", label: "Trials", blurb: "Landmark and current trials." },
      { href: "/pairings/", label: "Pairings", blurb: "What works together, and what does not." },
      { href: "/roadmaps/", label: "Roadmaps", blurb: "History to horizon for each technology family." },
      { href: "/dependencies/", label: "Dependency map", blurb: "What each technology needs to exist, drawn in layers from foundations to end products: what CAR-T cannot run without, and what stops if one step fails." },
      { href: "/bottlenecks/", label: "Bottlenecks", blurb: "The constraints slowing the whole war on cancer, and the ideas that could break each one." },
      { href: "/ideas/", label: "Ideas", blurb: "Hypotheses and fixes, each with a proposed test." },
      { href: "/terms/", label: "Glossary", blurb: "Terms with TL;DRs and Wikipedia links." },
      { href: "/collections/", label: "Collections", blurb: "The open databases the field runs on." },
    ],
  },
  {
    id: "intel", label: "News & evidence", href: "/intel/", blurb: "What is happening and how strong the evidence is: dates, congress readouts, approvals, failures, resistance, and the supply chain behind the drugs.",
    items: [
      { href: "/edge/", label: "Edge", blurb: "The freshest signals in cancer: new papers, trial results, approvals and law, one feed updated with every build, with RSS and JSON." },
      { href: "/journals/", label: "Journals", blurb: "Where the evidence is published: scope, access model and the key papers each venue carried." },
      { href: "/key-papers/", label: "Key papers", blurb: "The papers that changed practice, each explained: what it found, what it means, what to be careful about." },
      { href: "/explained/", label: "Trials in plain words", blurb: "Every trial result as people out of 100, medians explained, surrogate endpoints flagged." },
      { href: "/trial-designs/", label: "Trial design picker", blurb: "Every trial design as a card: when to use it, a worked example from the corpus and its main risk, with a plain-English guide to which design fits your question." },
      { href: "/guidelines/", label: "Guidelines", blurb: "Where NCCN, ESMO, NICE and ASCO agree and disagree, and what changed between guideline versions." },
      { href: "/forest/", label: "Forest plot", blurb: "Every hazard ratio in the trial corpus on one log axis; filter by cancer, setting and endpoint." },
      { href: "/evidence/", label: "Evidence", blurb: "Every trial ranked by evidence strength, endpoints as people out of 100." },
      { href: "/catalysts/", label: "Catalyst calendar", blurb: "Regulatory decisions, expected readouts, filings and deal closings by company, with a calendar feed." },
      { href: "/deals/", label: "Deals and licences", blurb: "Who bought or licensed what, for how much, and where assets flow between regions." },
      { href: "/exclusivity/", label: "Exclusivity expiry", blurb: "When each product loses patent or regulatory exclusivity, and the biosimilars and generics coming." },
      { href: "/pipeline/", label: "Pipeline funnel", blurb: "Assets by phase for any target, modality or cancer, and how crowded each target is." },
      { href: "/pipeline/engine/", label: "Open drug engine", blurb: "Every medicine taken apart into its modules, and the grid of every combination: approved, in development, tried and stopped with the reason, or never tried." },
      { href: "/modalities/", label: "Modalities", blurb: "One hub per shape of medicine (ADC, radioligand, CAR-T, bispecific, degrader and the rest): how it works, approved medicines, phase 3, parts, companies, trials, side effects, resistance, papers, roadmaps, ideas and manufacturing, each section naming its records." },
      { href: "/market/", label: "Addressable population", blurb: "Incidence times prevalence times setting share, every input linked, as a range." },
      { href: "/calendar/", label: "Readout calendar", blurb: "Decisions, readouts, advisory committees, congresses." },
      { href: "/digests/", label: "Congress digests", blurb: "ASCO, ESMO, AACR, ASCO GU, sourced item by item." },
      { href: "/failures/", label: "Failure museum", blurb: "What did not work, and the lesson." },
      { href: "/resistance/", label: "Resistance atlas", blurb: "Escape routes per drug class and the countermeasures." },
      { href: "/resistance/gaps/", label: "Unaddressed resistance", blurb: "Escape routes with no countermeasure, or only preclinical ones: the drug-design opportunities." },
      { href: "/assays/", label: "Companion diagnostics", blurb: "Every assay and its cut-off: PD-L1 CPS, HER2-low, MSI, TMB, HRD and the multi-gene panels, linked to the drugs they gate." },
      { href: "/preprints/", label: "Preprint tracker", blurb: "bioRxiv and medRxiv preprints of the last 90 days per target, product and technology, and which have since been published." },
      { href: "/payloads/", label: "Payloads & linkers", blurb: "The chemistry inside ADCs." },
      { href: "/regulatory/", label: "Regulatory timeline", blurb: "Every dated filing, approval, CRL, and label change." },
      { href: "/law/", label: "Laws around oncology", blurb: "The statutes, regulations and court rulings that decide how cancer drugs are approved, paid for and tested, and how data and genes are protected, by jurisdiction and theme." },
      { href: "/coverage/us/", label: "Paying for care in the US", blurb: "Medicare Part B or D, prior authorisation, list prices and assistance programmes for every approved product.", regions: ["US"] },
      { href: "/coverage/uk/", label: "NHS coverage", blurb: "NICE, Cancer Drugs Fund and SMC decisions for every approved product, and how NHS cancer care works.", regions: ["UK"] },
      { href: "/coverage/rankings/", label: "Coverage rankings", blurb: "US insurers and plan types ranked by one published metric at a time, UK NHS entitlement against private medical insurance, and how ten countries pay for cancer drugs." },
      { href: "/costs/", label: "Cutting cancer care costs", blurb: "Each cost driver paired with what is being done and the ideas that could do more: biosimilars, negotiation, dose optimisation, shorter courses, parity, prior authorisation." },
      { href: "/hta/", label: "HTA decisions", blurb: "NICE, SMC, G-BA and PBAC verdicts per product and country, with dates and links to the appraisal." },
      { href: "/survival/", label: "Survival statistics", blurb: "Five-year relative survival by cancer and stage from SEER, with the period and caveats." },
      { href: "/regulatory/regions/", label: "Approvals by region", blurb: "Which products are approved in the US, EU, UK, Japan, China and Australia, and which are missing where." },
      { href: "/papers/", label: "Publishing trends", blurb: "Fastest-growing topics in the literature, refreshed weekly from Europe PMC." },
      { href: "/pulse/", label: "Research pulse", blurb: "What the leading journals, regulators and news sources are saying this month." },
      { href: "/toxicity/", label: "Toxicity compare", blurb: "Grade 3+ adverse events across products of the same class." },
      { href: "/isotopes/", label: "Isotope supply", blurb: "Lu-177, Ac-225, Pb-212 and who makes them." },
      { href: "/report/", label: "Annual report", blurb: "The state of the war on cancer, year by year, generated from the corpus." },
      { href: "/changelog/", label: "Changelog", blurb: "What changed in OnCo, and when." },
      { href: "/status/", label: "Data currency", blurb: "When each automated feed last ran, what is stale, and the incident log." },
      { href: "/freshness/", label: "Freshness", blurb: "How old is too old for each kind of record, by review track, and what is past due." },
      { href: "/history/", label: "Recent changes", blurb: "What changed on which record, field by field, from the git history." },
      { href: "/audit/", label: "Audit", blurb: "Staleness, contradictions, and registry mismatches, recomputed each build." },
      { href: "/corrections/", label: "Corrections", blurb: "Every factual correction, what was wrong and how it was found." },
    ],
  },
  {
    id: "who", label: "Institutions & people", short: "Who's who", href: "/institutions/", blurb: "The hospitals, universities, doctors, scientists, companies, countries, and funders behind the field, mapped and ranked with disclosed formulas.",
    items: [
      { href: "/institutions/", label: "Institutions", blurb: "Global map and ranking of cancer centres and institutes." },
      { href: "/universities/", label: "Universities", blurb: "Research output from OpenAlex, Nature Index, SCImago." },
      { href: "/leadership/", label: "Trial leadership", blurb: "Who led the pivotal trials." },
      { href: "/people/", label: "People", blurb: "The clinicians and scientists doing the work: specialisms, bios, papers." },
      { href: "/heroes/", label: "Heroes and heroines", blurb: "The patients, families, advocates and pioneers whose lives and cases changed cancer." },
      { href: "/companies/", label: "Companies", blurb: "Pharma, biotech, diagnostics, devices, AI." },
      { href: "/startups/", label: "Startups", blurb: "Y Combinator and venture-backed companies attacking cancer, by stage, modality, cancer, batch, investor and country." },
      { href: "/startup-requests/", label: "Requests for startups", blurb: "Problems with no company on them: ideas that need a builder, druggable targets with no product, bottlenecks with no market entrant." },
      { href: "/investors/", label: "Investors", blurb: "The venture funds, corporate venture arms and disease foundations that back oncology companies, each with its portfolio." },
      { href: "/scorecards/", label: "Company scorecards", blurb: "Every company ranked by one disclosed formula, with financial snapshots from annual reports." },
      { href: "/sponsors/", label: "Trial sponsors", blurb: "Who runs the most phase 2 and 3 trials, by cancer, from the registry and the corpus." },
      { href: "/manufacturing/", label: "Manufacturing map", blurb: "Where ADCs are conjugated, cell therapies made and isotopes produced." },
      { href: "/countries/", label: "Countries", blurb: "Who is doing the most cancer research: output, growth, trials, burden, funders." },
      { href: "/countries/us/", label: "United States deep dive", blurb: "What the United States is up to: who pays and what it costs a person, the FDA, why coverage is not approval, the NCI trial network, and the disparities." },
      { href: "/countries/in/", label: "India deep dive", blurb: "What India is up to: cancer profile, paying for care, CDSCO, institutions, companies, trials and people." },
      { href: "/countries/cn/", label: "China deep dive", blurb: "What China is up to: cancer profile, the NMPA, national insurance listing, institutions, companies, trials and people." },
      { href: "/countries/de/", label: "Germany deep dive", blurb: "What Germany does differently: reimbursement from day one and the benefit assessment that follows, certified cancer centres, mandatory clinical cancer registration, institutions, companies, trials and people." },
      { href: "/countries/il/", label: "Israel deep dive", blurb: "What Israel is up to: the public committee that decides each year which drugs the state pays for, the four health funds, founder genetics and population testing, and the trial and device industry." },
      { href: "/countries/gb/", label: "United Kingdom deep dive", blurb: "What the UK does: four health services under one name, who pays, NICE and the SMC, the trials and the genomics, and what the figures say it does badly." },
      { href: "/cases/", label: "Cases by country", blurb: "New cancer cases per country and per cancer, with the data gaps made explicit." },
      { href: "/funding/", label: "Funding flows", blurb: "Where the money comes from." },
    ],
  },
  {
    id: "live", label: "Living with cancer", href: "/live/", blurb: "Practical help for patients, families and carers: what to ask, what to watch for, what it costs and who can help, in plain words.",
    items: [
      { href: "/for-me/", label: "For me", blurb: "Research your cancer type and see what works and what could work." },
      { href: "/first-60-days/", label: "The first 60 days", blurb: "Week by week after a diagnosis, for your cancer type: the tests, the team, the decisions ahead, the questions to ask, the trials to mention and the help that costs nothing." },
      { href: "/prep/", label: "Appointment prep pack", blurb: "Tick the questions to ask for your cancer, add your own, and print or download one page for the appointment; each cancer also has a one-page sheet with room for the answers." },
      { href: "/side-effects/", label: "Side effects", blurb: "Start from the symptom: which treatments cause it, how often, and when to call." },
      { href: "/symptoms/", label: "Symptom to test", blurb: "Start from a worrying symptom: what it can mean, which test comes first, and the referral thresholds guidelines state." },
      { href: "/report-reader/", label: "Report reader", blurb: "Type the values from a pathology report and read what each one means. Nothing is stored." },
      { href: "/survivorship/", label: "Survivorship planner", blurb: "Late effects to watch for after each treatment, the screening test, how often, and the guideline that says so." },
      { href: "/second-opinion/", label: "Second opinion", blurb: "Expert centres for your cancer in your country, the people who work on it, and how referral works where you live." },
      { href: "/assistance/", label: "Financial help", blurb: "Manufacturer programmes, reimbursement and generics by country and product, plus national schemes and charities." },
      { href: "/free/", label: "Free in oncology", blurb: "Everything you can get for nothing: free tumour and gene testing, screening and HPV vaccination, nurse helplines, rides and lodging, second opinions, trial travel help, wigs and prostheses, and open data. Who is eligible and where." },
      { href: "/coverage/us/", label: "Paying for care in the US", blurb: "Medicare Part B or D, prior authorisation, list prices and assistance programmes for every approved product.", regions: ["US"] },
      { href: "/coverage/uk/", label: "NHS coverage", blurb: "NICE, Cancer Drugs Fund and SMC decisions for every approved product, and how NHS cancer care works.", regions: ["UK"] },
      { href: "/countries/in/", label: "Paying for care in India", blurb: "PM-JAY, Tata Memorial's subsidised care, National Cancer Grid pooled prices and what CDSCO has approved.", regions: ["IN"] },
      { href: "/coverage/rankings/", label: "Coverage rankings", blurb: "US insurers and plan types ranked by one published metric at a time, UK NHS entitlement against private medical insurance, and how ten countries pay for cancer drugs." },
      { href: "/costs/", label: "Cutting cancer care costs", blurb: "Each cost driver paired with what is being done and the ideas that could do more: biosimilars, negotiation, dose optimisation, shorter courses, parity, prior authorisation." },
      { href: "/fronts/nutrition-lifestyle/", label: "Diet, exercise and lifestyle", blurb: "What people eat, drink, weigh and do: what the evidence says and what is hype." },
      { href: "/fronts/supportive-care/", label: "Supportive care", blurb: "Treating the person, not just the tumour: symptoms, side effects, nutrition, mental health." },
      { href: "/live/complementary/", label: "Complementary and supportive approaches", blurb: "Acupuncture, mindfulness, yoga, herbs, diets, cannabis, cold caps and more: what the trials show, graded honestly, and what to avoid or never use instead of treatment." },
      { href: "/live/hair/", label: "Hair loss and regrowth", blurb: "Scalp cooling and the regimens it suits, minoxidil for lasting thinning, eyebrows and lashes, wigs on the NHS and by prescription in the US, which drugs cause it and when hair returns." },
      { href: "/heroes/", label: "Heroes and heroines", blurb: "The patients, families, advocates and pioneers whose lives and cases changed cancer." },
    ],
  },
  {
    id: "learn", label: "Learn & contribute", href: "/learn/", blurb: "Curated paths through the material, how the site works, and how to make it better.",
    items: [
      { href: "/paths/", label: "Reading paths", blurb: "ADCs in 30 minutes, understanding a diagnosis, and more." },
      { href: "/about/", label: "About & methodology", blurb: "Rules for facts, ranking formulas, licence." },
      { href: "/roadmap/", label: "Roadmap", blurb: "Corpus health gauges, every idea by status, and how OnCo expands and stays current." },
      { href: "/gaps/", label: "Gaps to fill", blurb: "Objects and fields that need work." },
      { href: "/completeness/", label: "Completeness", blurb: "How much of what exists is in OnCo: each kind against a sourced count of the world, with the missing items named." },
      { href: "/review/", label: "Review queue", blurb: "Which pages most need a named reviewer, coverage by kind and track, translation coverage." },
      { href: "/reviewers/", label: "Reviewer roster", blurb: "Who has signed off pages, on which track, with declared conflicts of interest." },
      { href: "/contributors/", label: "Contributors", blurb: "Everyone who wrote or reviewed records, from the repository history." },
      { href: "/idea-votes/", label: "Idea votes", blurb: "Which ideas people want tested, and which have been picked up, with sources." },
      { href: "/teach/", label: "Teaching packs", blurb: "A slide deck and quiz per cancer and front; print to PDF." },
      { href: "/newsletter/", label: "Weekly issue", blurb: "What changed, regulatory events, upcoming readouts, what the journals said. No tracking." },
      { href: "/suggest/", label: "Suggest an edit", blurb: "Propose a correction; organisations can edit their own records." },
      { href: "/eval/", label: "Open evaluation", blurb: "100 questions, a rubric, and a public leaderboard." },
      { href: "/schema/", label: "Data dictionary", blurb: "Every kind, every field, its type and meaning, with a real example per kind." },
      { href: "/build/", label: "Build on OnCo", blurb: "Recipes, OpenAPI spec, TypeScript types, embeddable cards and the MCP server." },
      { href: "/api/", label: "Open API", blurb: "The corpus as JSON." },
      { href: "/data-sources/", label: "Open data", blurb: "Every open database OnCo pulls from, with licences and cadence, and the ones we could add next." },
      { href: "/open-tools/", label: "Open tools", blurb: "Open-source viewers, planners, pipelines and hardware you can use or build on, by front, from the Open Medical Registry." },
      { href: "/open-source/", label: "Open source in oncology", blurb: "Every open-source project the field runs on, from variant callers to planning systems and foundation models, with licence, openness and maintainer." },
      { href: "https://github.com/judegomila/OnCo", label: "GitHub", blurb: "Code and data. Propose changes through the issue forms." },
    ],
  },
];
