/**
 * Completeness against the NCI "A to Z List of Cancer Drugs" snapshot (src/data/universe-lists/nci-cancer-drugs-match.json,
 * regenerated by scripts/fetch-nci-drugs.ts). Every NCI drug page must map to a corpus product, or carry a documented
 * exclusion (regimen acronym, formulation of an existing molecule, or a non-oncology product the NCI lists for a
 * cancer-related condition). The matched ids recorded in the snapshot must still resolve to drug records.
 */
import { describe, expect, it } from "vitest";
import { graph } from "./graph";
import snapshot from "../data/universe-lists/nci-cancer-drugs-match.json";
import { NCI_EXCLUSIONS } from "../data/universe-lists/nci-exclusions";

type Entry = { slug: string; generic: string; type: "drug" | "regimen"; matchedIds: string[]; exclusion?: string };
const entries = snapshot.entries as Entry[];

describe("NCI A to Z list coverage", () => {
  const g = graph();

  it("the snapshot is non-trivial and dated", () => {
    expect(entries.length).toBeGreaterThan(300);
    expect(snapshot.source).toMatch(/^https:\/\/www\.cancer\.gov\//);
    expect(snapshot.checked).toMatch(/^\d{4}-\d{2}-\d{2}$/);
  });

  it("every NCI drug page has a matching product record or a documented exclusion", () => {
    const failures = entries.filter((e) => !e.matchedIds.length && !e.exclusion).map((e) => `${e.slug}: ${e.generic}`);
    expect(failures).toEqual([]);
  });

  it("matched ids resolve to drug records", () => {
    const failures: string[] = [];
    for (const e of entries) for (const id of e.matchedIds) {
      const ent = g.byId.get(id);
      if (!ent || ent.kind !== "drug") failures.push(`${e.slug} -> ${id}`);
    }
    expect(failures).toEqual([]);
  });

  it("exclusions are explained and not stale", () => {
    // Every hand-written exclusion refers to a slug that exists in the snapshot and still has no matching record.
    const bySlug = new Map(entries.map((e) => [e.slug, e]));
    for (const [slug, reason] of Object.entries(NCI_EXCLUSIONS)) {
      expect(reason.length, slug).toBeGreaterThan(20);
      const e = bySlug.get(slug);
      expect(e, `exclusion for unknown slug ${slug}`).toBeDefined();
      expect(e?.matchedIds ?? [], `${slug} now has a record; drop the exclusion`).toEqual([]);
    }
    // Automatic regimen exclusions only apply to all-caps acronyms.
    for (const e of entries) if (e.type === "regimen") expect(e.generic, e.slug).toMatch(/^[A-Z0-9][A-Z0-9-]*$/);
  });
});
