import type { Metadata } from "next";
import Link from "next/link";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { pageMeta } from "@/lib/seo";
import { Container, GroupKicker, PageHeader } from "@/components/ui";

export const metadata: Metadata = pageMeta({ title: "Weekly issue", description: "OnCo's weekly issue: what changed in the corpus, regulatory events, upcoming readouts and what the journals published, rendered from the data with no tracking.", path: "/newsletter/" });

/**
 * Signup endpoint for the email list. Leave empty until a Buttondown (https://buttondown.com/api/emails/embed-subscribe/<username>)
 * or Listmonk (<host>/subscription/form) endpoint exists; the page then offers the feed and archive only.
 * The form posts the address and nothing else: no pixels, no scripts, no third-party assets.
 */
const SIGNUP_ACTION = "";

type Issue = { date: string; title: string; path: string; summary: string; counts: Record<string, number> };
type IssueSection = { id: string; title: string; blurb: string; items: string[] };
type IssueJson = Issue & { sections: IssueSection[] };

const NL_DIR = join(process.cwd(), "public", "newsletter");
/** Archive entries, newest first. Legacy "<date>.html" paths are shown at their directory URL, which is the one static hosts serve. */
function readIndex(): Issue[] {
  const p = join(NL_DIR, "index.json");
  if (!existsSync(p)) return [];
  try {
    return (JSON.parse(readFileSync(p, "utf8")) as Issue[]).map((i) => ({ ...i, path: `/newsletter/${i.date}/` })).sort((a, b) => b.date.localeCompare(a.date));
  } catch { return []; }
}
function readIssue(date: string): IssueJson | null {
  const p = join(NL_DIR, `${date}.json`);
  if (!existsSync(p)) return null;
  try { return JSON.parse(readFileSync(p, "utf8")) as IssueJson; } catch { return null; }
}

/** The five headline sections every issue is built from, in reading order. Changelog sections carry a release-specific id. */
const HEADLINES: Array<{ match: (id: string) => boolean; title: string; quiet: string }> = [
  { match: (id) => id.startsWith("changelog"), title: "What changed", quiet: "No changelog entries this week." },
  { match: (id) => id === "regulatory", title: "Regulatory events", quiet: "No dated regulatory events were recorded on product pages in the past seven days." },
  { match: (id) => id === "calendar", title: "Upcoming readouts", quiet: "Nothing on the readout calendar in the next thirty days." },
  { match: (id) => id === "pulse", title: "What the journals said", quiet: "No pulse items in the past fourteen days." },
  { match: (id) => id === "corrections", title: "Corrections", quiet: "No corrections were logged this week." },
];

const COUNT_LABEL: Record<string, [string, string]> = { changes: ["changelog entry", "changelog entries"], regulatory: ["regulatory event", "regulatory events"], calendar: ["upcoming date", "upcoming dates"], pulse: ["publication", "publications"], corrections: ["correction", "corrections"] };
const countLine = (counts: Record<string, number>) => Object.entries(counts).filter(([, n]) => n > 0).map(([k, n]) => `${n} ${(COUNT_LABEL[k] ?? [k, k])[n === 1 ? 0 : 1]}`).join(" · ");
/** Issue HTML is generated by our own script from the corpus; links are made site-relative so previews work on any host. */
const local = (html: string) => html.replace(/href="https:\/\/onco\.cc\//g, 'href="/');

export default function NewsletterPage() {
  const issues = readIndex();
  const latest = issues[0];
  const issue = latest ? readIssue(latest.date) : null;
  const previous = issues.slice(1);

  return (
    <>
      <PageHeader kicker={<GroupKicker id="learn" />} title="Weekly issue"
        lede="One issue a week, generated from the corpus: what changed in OnCo, dated regulatory events, the readouts and decisions due in the next month, what the leading journals published, and any corrections. No tracking pixels, no click tracking, no third-party scripts. The latest issue is below; every issue is archived here and published as an Atom feed." />
      <Container className="pb-16 max-w-3xl">
        <section className="card p-5">
          <div className="kicker mb-1">Subscribe</div>
          {SIGNUP_ACTION ? (
            <form action={SIGNUP_ACTION} method="post" target="_blank" className="mt-2 flex flex-wrap gap-2 items-center">
              <label htmlFor="nl-email" className="sr-only">Email address</label>
              <input id="nl-email" name="email" type="email" required autoComplete="email" placeholder="you@example.org" className="rounded-lg border border-border bg-background px-3 py-2 text-sm min-w-[16rem]" />
              <button type="submit" className="btn btn-primary text-sm">Subscribe</button>
              <p className="text-xs text-muted basis-full">Your address is used only to send the weekly issue. Unsubscribe from any issue. No tracking.</p>
            </form>
          ) : (
            <p className="text-sm mt-1">There is no email list yet, so the simplest way to follow along is the <a className="underline font-medium" href="/newsletter/feed.xml">Atom feed</a>: add it to any feed reader and each new issue arrives in full. New issues are published here on Mondays, and the <Link className="underline" href="/changelog/">changelog</Link> carries the same changes as they land.</p>
          )}
        </section>

        {latest ? (
          <article className="mt-10">
            <div className="flex flex-wrap items-baseline justify-between gap-2 mb-1">
              <h2 className="text-2xl font-semibold tracking-tight">{latest.title}</h2>
              <span className="text-xs text-muted">latest issue · <a className="underline" href={latest.path}>standalone page</a></span>
            </div>
            <p className="text-sm text-muted mb-6">{countLine(latest.counts) || latest.summary}. Every item links to its OnCo page and, through it, to the primary source. Not medical advice.</p>

            {issue ? (
              <div className="space-y-8">
                {HEADLINES.map((h) => {
                  const parts = issue.sections.filter((s) => h.match(s.id));
                  return (
                    <section key={h.title} id={h.title.toLowerCase().replace(/\s+/g, "-")} className="scroll-mt-24">
                      <h3 className="text-lg font-semibold tracking-tight mb-1">{h.title}</h3>
                      {parts.length ? parts.map((s) => (
                        <div key={s.id} className="mb-3">
                          {s.title !== h.title && <p className="text-sm text-muted mb-2">{s.title}. {s.blurb}</p>}
                          <ul className="card divide-y divide-border text-sm">
                            {s.items.map((it, i) => <li key={i} className="p-3 leading-relaxed [&_a]:underline [&_code]:text-xs [&_code]:bg-foreground/5 [&_code]:rounded [&_code]:px-1 [&_.muted]:text-muted" dangerouslySetInnerHTML={{ __html: local(it) }} />)}
                          </ul>
                        </div>
                      )) : <p className="card p-3 text-sm text-muted">{h.quiet}</p>}
                    </section>
                  );
                })}
              </div>
            ) : (
              <p className="card p-4 text-sm">Read this issue on its <a className="underline" href={latest.path}>own page</a>.</p>
            )}
          </article>
        ) : (
          <section className="mt-10 card p-5 text-sm">
            <div className="kicker mb-1">First issue coming</div>
            <p>The first weekly issue is published on the next Monday. It will carry the week&apos;s changelog, dated regulatory events, the readouts and decisions due in the next thirty days, what the journals published and any corrections. Until then the <Link className="underline" href="/changelog/">changelog</Link>, <Link className="underline" href="/regulatory/">regulatory events</Link>, <Link className="underline" href="/calendar/">readout calendar</Link> and <Link className="underline" href="/pulse/">research pulse</Link> hold the same material, live.</p>
          </section>
        )}

        <section className="mt-12">
          <h2 className="text-xl font-semibold mb-3">Archive</h2>
          {issues.length ? (
            <ul className="card divide-y divide-border">
              {issues.map((i) => (
                <li key={i.date} className="p-4">
                  <div className="flex flex-wrap items-baseline justify-between gap-2">
                    <a className="font-medium underline" href={i.path}>{i.title}</a>
                    <span className="text-xs text-muted tabular-nums">{i.date}{i === latest ? " · latest" : ""}</span>
                  </div>
                  <p className="text-xs text-muted mt-1">{countLine(i.counts) || i.summary}</p>
                </li>
              ))}
            </ul>
          ) : (
            <p className="card p-4 text-sm text-muted">Issues appear here as they are published, newest first, each on its own page and in the <a className="underline" href="/newsletter/feed.xml">Atom feed</a>.</p>
          )}
          {previous.length === 0 && issues.length === 1 && <p className="text-xs text-muted mt-2">One issue so far; the archive grows by one every Monday.</p>}
          <p className="text-sm mt-3"><a className="underline" href="/newsletter/feed.xml">Atom feed of every issue</a></p>
        </section>

        <section className="mt-10 text-sm text-muted space-y-2">
          <h2 className="text-xl font-semibold text-foreground mb-1">How it is made</h2>
          <p>Each issue is rendered from the same data as the site: the <Link className="underline" href="/changelog/">changelog</Link> (the newsletter is the changelog, with context), products&apos; dated <Link className="underline" href="/regulatory/">regulatory events</Link> from the past week, the <Link className="underline" href="/calendar/">readout calendar</Link> for the next thirty days, the <Link className="underline" href="/pulse/">research pulse</Link>, and <Link className="underline" href="/corrections/">corrections</Link>. Nobody writes it by hand and nothing is added that is not already on a page here.</p>
          <p>Something wrong in an issue? It is wrong in the corpus too: fix it once via <Link className="underline" href="/suggest/">Suggest an edit</Link> and the next issue is right.</p>
        </section>
      </Container>
    </>
  );
}
