/**
 * Affected pages for a pull request: which records (and therefore which pages) a diff touches.
 *
 * Reads `git diff -U0 <base>...<head> -- src/data`, maps every changed line to the record whose
 * braces enclose it, and prints a Markdown list of page URLs. The label workflow
 * (.github/workflows/label.yml) posts the output as a PR comment so reviewers can open the pages.
 *
 * Run: npx tsx scripts/affected-pages.ts <base-sha> <head-sha> [--site https://onco.cc] [--max 60]
 */
import { execFileSync } from "node:child_process";
import { graph } from "../src/lib/graph";
import { routeFor } from "../src/lib/schema";
import { extractRecords } from "./history";

const root = process.cwd();
function git(args: string[]): string {
  return execFileSync("git", args, { cwd: root, encoding: "utf8", maxBuffer: 256 * 1024 * 1024, stdio: ["ignore", "pipe", "ignore"] });
}

/** Changed line numbers (in the new file) per data file, from a unified diff with zero context. */
export function changedLines(diff: string): Map<string, number[]> {
  const out = new Map<string, number[]>();
  let file: string | null = null;
  for (const line of diff.split("\n")) {
    const f = /^\+\+\+ b\/(.*)$/.exec(line);
    if (f) { file = f[1]; continue; }
    const h = /^@@ -\d+(?:,\d+)? \+(\d+)(?:,(\d+))? @@/.exec(line);
    if (h && file) {
      const start = Number(h[1]);
      const count = h[2] === undefined ? 1 : Number(h[2]);
      const list = out.get(file) ?? [];
      // A pure deletion has count 0; still record the position so the enclosing record is found.
      for (let i = 0; i < Math.max(count, 1); i++) list.push(start + i);
      out.set(file, list);
    }
  }
  return out;
}

/** Ids of the records whose source spans include any of the changed lines. */
export function affectedIds(source: string, lines: number[]): string[] {
  const offsets: number[] = [0];
  for (let i = 0; i < source.length; i++) if (source[i] === "\n") offsets.push(i + 1);
  const spans = extractRecords(source);
  const ranges = [...spans.entries()].map(([id, text]) => { const start = source.indexOf(text); return { id, start, end: start + text.length }; });
  const ids = new Set<string>();
  for (const ln of lines) {
    const pos = offsets[Math.min(ln - 1, offsets.length - 1)] ?? 0;
    for (const r of ranges) if (pos >= r.start && pos <= r.end) { ids.add(r.id); break; }
  }
  return [...ids];
}

if (process.argv[1]?.endsWith("affected-pages.ts")) {
  const [base, head] = process.argv.slice(2).filter((a) => !a.startsWith("--"));
  const arg = (name: string, dflt: string) => { const i = process.argv.indexOf(name); return i > 0 ? process.argv[i + 1] : dflt; };
  const site = arg("--site", "https://onco.cc").replace(/\/$/, "");
  const max = Number(arg("--max", "60"));
  if (!base || !head) { console.error("usage: affected-pages.ts <base> <head>"); process.exit(2); }
  const diff = git(["diff", "-U0", `${base}...${head}`, "--", "src/data"]);
  const changed = changedLines(diff);
  const ids = new Set<string>();
  for (const [file, lines] of changed) {
    if (!file.endsWith(".ts") || /\/(i18n|simple)\//.test(file)) continue;
    let src: string;
    try { src = git(["show", `${head}:${file}`]); } catch { continue; }
    for (const id of affectedIds(src, lines)) ids.add(id);
  }
  const g = graph();
  const known = [...ids].map((id) => g.get(id)).filter((e): e is NonNullable<typeof e> => !!e).sort((a, b) => a.kind.localeCompare(b.kind) || a.name.localeCompare(b.name));
  const unknown = [...ids].filter((id) => !g.get(id));
  if (!known.length && !unknown.length) { console.log("No entity records changed under `src/data/`."); process.exit(0); }
  console.log(`### Pages affected by this change\n`);
  console.log(`${known.length} record${known.length === 1 ? "" : "s"} touched${changed.size ? ` across ${changed.size} file${changed.size === 1 ? "" : "s"}` : ""}. Open each page and check the TL;DR, the changed fields and the sources.\n`);
  for (const e of known.slice(0, max)) console.log(`- **${e.kind}** [${e.name}](${site}${routeFor(e)}) · \`${e.id}\``);
  if (known.length > max) console.log(`- and ${known.length - max} more`);
  if (unknown.length) console.log(`\nRemoved or renamed ids: ${unknown.map((id) => `\`${id}\``).join(", ")}`);
  console.log(`\n_Generated by scripts/affected-pages.ts. Kinds touched: ${[...new Set(known.map((e) => e.kind))].join(", ")}._`);
}
