/**
 * Resolve every cell-line name in src/data/preclinical-models.ts against the Cellosaurus API and write
 * src/data/cell-line-ids.ts with the Cellosaurus accession, DepMap ACH id (when Cellosaurus lists one), NCIt disease
 * label and species. Names that do not resolve are reported and left out (the page then shows the name alone).
 *
 *   https://api.cellosaurus.org/search/cell-line?q=id:"NAME"&fields=id,ac,ox,di,dr&format=json
 *
 * Run: npx tsx scripts/fetch-cell-lines.ts   (network; one request per name)
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { allCellLineNames } from "../src/data/preclinical-models";

const UA = "OnCo/1.0 (https://github.com/judegomila/OnCo; cell-line identifiers)";
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

type CvclEntry = {
  "name-list"?: Array<{ type: string; value: string }>;
  "accession-list"?: Array<{ type: string; value: string }>;
  "species-list"?: Array<{ label: string }>;
  "disease-list"?: Array<{ label: string }>;
  "xref-list"?: Array<{ database: string; accession: string }>;
};

async function search(q: string): Promise<CvclEntry[]> {
  // Full-text search sorted by accession so the parent line (lowest CVCL number) comes before its derivatives.
  const url = `https://api.cellosaurus.org/search/cell-line?q=${encodeURIComponent(q)}&fields=id,ac,ox,di,dr&format=json&rows=200&sort=ac%20asc`;
  for (let i = 0; i < 4; i++) {
    try {
      const r = await fetch(url, { headers: { "User-Agent": UA, Accept: "application/json" } });
      if (r.status === 429 || r.status >= 500) { await sleep(1000 * (i + 1)); continue; }
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      const j = (await r.json()) as { Cellosaurus?: { "cell-line-list"?: CvclEntry[] } };
      return j.Cellosaurus?.["cell-line-list"] ?? [];
    } catch (e) {
      if (i === 3) throw e;
      await sleep(800 * (i + 1));
    }
  }
  return [];
}

/** Cellosaurus spells names with or without hyphens and spaces ("A-549", "HCT 116"); compare without them. */
const norm = (s: string) => s.toLowerCase().replace(/[\s\-_.]/g, "").replace(/\[.*?\]/g, "");

/** Names whose search ranking picks a relative; resolved by accession instead. */
const OVERRIDES: Record<string, string> = { "C4-2B": "CVCL_4784", "DLD-1 BRCA2-/-": "CVCL_HD56" };

async function byAccession(ac: string): Promise<CvclEntry | undefined> {
  const r = await fetch(`https://api.cellosaurus.org/cell-line/${ac}?format=json&fields=id,ac,ox,di,dr`, { headers: { "User-Agent": UA, Accept: "application/json" } });
  if (!r.ok) return undefined;
  const j = (await r.json()) as { Cellosaurus?: { "cell-line-list"?: CvclEntry[] } };
  return j.Cellosaurus?.["cell-line-list"]?.[0];
}

/** Names that are descriptive groups rather than one Cellosaurus entry; skipped. */
const SKIP = /derived lines|panels?$|mutants$| and |exon 20$|CD19$/i;

async function main() {
  const names = allCellLineNames();
  const out: Record<string, { cellosaurus: string; depmap?: string; disease?: string; species?: string }> = {};
  const missing: string[] = [];
  for (const name of names) {
    if (SKIP.test(name)) { missing.push(`${name} (group, skipped)`); continue; }
    const hits = OVERRIDES[name] ? [await byAccession(OVERRIDES[name])].filter((x): x is CvclEntry => !!x) : await search(`"${name}"`);
    await sleep(150);
    const exact = hits.find((h) => h["name-list"]?.some((n) => n.type === "identifier" && norm(n.value) === norm(name)));
    const synonym = hits.find((h) => h["name-list"]?.some((n) => norm(n.value) === norm(name)));
    const bracketed = hits.find((h) => h["name-list"]?.some((n) => n.type === "identifier" && norm(n.value.replace(/\s*\[.*\]$/, "")) === norm(name)));
    const withDepmap = hits.find((h) => h["xref-list"]?.some((x) => x.database === "DepMap"));
    const pick = OVERRIDES[name] ? hits[0] : exact ?? synonym ?? bracketed ?? withDepmap ?? hits[0];
    if (!pick) { missing.push(name); continue; }
    const ac = pick["accession-list"]?.find((a) => a.type === "primary")?.value;
    if (!ac) { missing.push(name); continue; }
    const depmap = pick["xref-list"]?.find((x) => x.database === "DepMap")?.accession;
    const disease = pick["disease-list"]?.[0]?.label;
    const species = pick["species-list"]?.[0]?.label?.replace(/\s*\(.*\)$/, "");
    out[name] = { cellosaurus: ac, depmap, disease, species };
    console.log(`${name} → ${ac}${depmap ? ` ${depmap}` : ""}${disease ? ` · ${disease}` : ""}${exact || synonym || bracketed || OVERRIDES[name] ? "" : " (nearest match, check)"}`);
  }
  const today = new Date().toISOString().slice(0, 10);
  const body = `/**
 * Cell-line identifiers keyed by Cellosaurus name. GENERATED by scripts/fetch-cell-lines.ts on ${today}
 * from the Cellosaurus API (accession, DepMap cross-reference, NCIt disease, species). Do not edit by hand.
 */
export type CellLineIds = { cellosaurus: string; depmap?: string; disease?: string; species?: string };

export const CELL_LINE_IDS_GENERATED = "${today}";

export const CELL_LINE_IDS: Record<string, CellLineIds> = ${JSON.stringify(out, null, 2)};
`;
  writeFileSync(join(process.cwd(), "src", "data", "cell-line-ids.ts"), body);
  console.log(`\ncell lines: ${Object.keys(out).length} resolved of ${names.length}; not resolved: ${missing.join(", ") || "none"}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
