/**
 * Resolves Wikidata QIDs for every record that carries an English Wikipedia link, by asking the Wikidata
 * API which item each Wikipedia article belongs to (wbgetentities with sites=enwiki). Nothing is guessed:
 * a QID is recorded only when Wikidata returns it for the exact article the record links to.
 *
 * Writes src/data/wikidata-ids.ts. Run occasionally; the output is committed.
 *
 *   npx tsx scripts/fetch-wikidata.ts
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { graph } from "../src/lib/graph";
import type { Kind } from "../src/lib/schema";

const KINDS: Kind[] = ["cancer", "drug", "target", "company", "institution", "technology", "pathway", "term", "journal", "person", "collection", "trial"];
const UA = "OnCo/0.4 (https://github.com/judegomila/OnCo; corpus cross-linking)";

function titleOf(url: string): string | null {
  const m = /^https?:\/\/en\.wikipedia\.org\/wiki\/([^#?]+)/.exec(url);
  return m ? decodeURIComponent(m[1]).replace(/_/g, " ") : null;
}

async function lookup(titles: string[]): Promise<Map<string, string>> {
  // Titles are matched exactly (the API only normalises single-title requests); the first letter is upper-cased as Wikipedia does.
  const p = new URLSearchParams({ action: "wbgetentities", sites: "enwiki", titles: titles.map((t) => t[0].toUpperCase() + t.slice(1)).join("|"), props: "info|sitelinks", format: "json" });
  const r = await fetch(`https://www.wikidata.org/w/api.php?${p}`, { headers: { "User-Agent": UA, Accept: "application/json" } });
  if (!r.ok) throw new Error(`Wikidata ${r.status}`);
  const j = (await r.json()) as { error?: { info?: string }; entities?: Record<string, { id?: string; missing?: string; sitelinks?: { enwiki?: { title?: string } } }> };
  if (j.error) throw new Error(j.error.info ?? "Wikidata error");
  const out = new Map<string, string>();
  for (const e of Object.values(j.entities ?? {})) {
    if (!e.id || e.missing !== undefined || !e.id.startsWith("Q")) continue;
    const t = e.sitelinks?.enwiki?.title;
    if (t) { out.set(t, e.id); out.set(t[0].toLowerCase() + t.slice(1), e.id); }
  }
  return out;
}

async function main() {
  const g = graph();
  const wanted: Array<{ id: string; title: string }> = [];
  for (const k of KINDS) for (const e of g.kind(k)) { const t = e.wikipedia ? titleOf(e.wikipedia) : null; if (t) wanted.push({ id: e.id, title: t }); }
  const result: Record<string, string> = {};
  const titles = [...new Set(wanted.map((w) => w.title))];
  for (let i = 0; i < titles.length; i += 50) {
    const batch = titles.slice(i, i + 50);
    let found: Map<string, string> | null = null;
    for (let attempt = 0; attempt < 3 && !found; attempt++) {
      try { found = await lookup(batch); } catch (e) { console.warn(`batch ${i}: ${e instanceof Error ? e.message : e}; retrying`); await new Promise((r) => setTimeout(r, 1500 * (attempt + 1))); }
    }
    if (!found) throw new Error(`Wikidata lookup failed for batch starting at ${i}`);
    for (const w of wanted) { const q = found.get(w.title); if (q && !result[w.id]) result[w.id] = q; }
    await new Promise((r) => setTimeout(r, 250));
  }
  const ids = Object.keys(result).sort();
  const lines = ids.map((id) => `  "${id}": "${result[id]}",`);
  const src = `/**
 * Wikidata item ids (QIDs) for OnCo records, keyed by record id.
 *
 * Generated by scripts/fetch-wikidata.ts on ${new Date().toISOString().slice(0, 10)}: each QID is the Wikidata item that owns the
 * English Wikipedia article the record links to in its \`wikipedia\` field. Records without a Wikipedia link, or
 * whose article Wikidata does not know, are absent. Nothing here is typed by hand. Used by scripts/build-triples.ts
 * for owl:sameAs links in public/api/v1/onco.nt and available to any page that wants a Wikidata link.
 */
export const wikidataIds: Record<string, string> = {
${lines.join("\n")}
};

export const wikidataUrl = (qid: string) => \`https://www.wikidata.org/wiki/\${qid}\`;
`;
  writeFileSync(join(process.cwd(), "src", "data", "wikidata-ids.ts"), src);
  console.log(`wikidata: ${ids.length} of ${wanted.length} records with a Wikipedia link resolved to a QID`);
}

main().catch((e) => { console.error(e); process.exit(1); });
