import { graph } from "../src/lib/graph";
const g = graph();
const IL_INST = new Set(g.kind("institution").filter((i) => (i as any).country === "IL").map((i) => i.id));
console.log("INSTITUTIONS:", [...IL_INST].join(", "));
console.log("COMPANIES:", g.kind("company").filter((c: any) => c.country === "IL").map((c) => `${c.id}(${c.hq})`).join(", "));
const ppl = g.kind("person").filter((p: any) => IL_INST.has(p.institutionId) || (p.institutions ?? []).some((x: string) => IL_INST.has(x)));
console.log("PEOPLE:", ppl.map((p) => p.id).join(", "));
const text = (e: any) => JSON.stringify(e).toLowerCase();
console.log("TRIALS mentioning Israel:", g.kind("trial").filter((t) => text(t).includes("israel")).map((t) => t.id).join(", "));
console.log("PAPERS mentioning Israel:", g.kind("paper").filter((t) => text(t).includes("israel")).map((t) => t.id).slice(0,40).join(", "));
