/**
 * Cell-line identifiers keyed by Cellosaurus name. GENERATED by scripts/fetch-cell-lines.ts on 2026-09-09
 * from the Cellosaurus API (accession, DepMap cross-reference, NCIt disease, species). Do not edit by hand.
 */
export type CellLineIds = { cellosaurus: string; depmap?: string; disease?: string; species?: string };

export const CELL_LINE_IDS_GENERATED = "2026-09-09";

export const CELL_LINE_IDS: Record<string, CellLineIds> = {
  "5637": {
    "cellosaurus": "CVCL_0126",
    "depmap": "ACH-000905",
    "disease": "Bladder carcinoma",
    "species": "Homo sapiens"
  },
  "143B": {
    "cellosaurus": "CVCL_2270",
    "depmap": "ACH-001001",
    "disease": "Osteosarcoma",
    "species": "Homo sapiens"
  },
  "22Rv1": {
    "cellosaurus": "CVCL_1045",
    "depmap": "ACH-000956",
    "disease": "Prostate carcinoma",
    "species": "Homo sapiens"
  },
  "4T1": {
    "cellosaurus": "CVCL_0125",
    "disease": "Malignant neoplasms of the mouse mammary gland",
    "species": "Mus musculus"
  },
  "5TGM1": {
    "cellosaurus": "CVCL_VI66",
    "disease": "Mouse multiple myeloma",
    "species": "Mus musculus"
  },
  "786-O": {
    "cellosaurus": "CVCL_1051",
    "depmap": "ACH-000649",
    "disease": "Renal cell carcinoma",
    "species": "Homo sapiens"
  },
  "8505C": {
    "cellosaurus": "CVCL_1054",
    "depmap": "ACH-001307",
    "disease": "Thyroid gland anaplastic carcinoma",
    "species": "Homo sapiens"
  },
  "A-375": {
    "cellosaurus": "CVCL_0132",
    "depmap": "ACH-000219",
    "disease": "Amelanotic melanoma",
    "species": "Homo sapiens"
  },
  "A-431": {
    "cellosaurus": "CVCL_0037",
    "depmap": "ACH-001328",
    "disease": "Skin squamous cell carcinoma",
    "species": "Homo sapiens"
  },
  "A-498": {
    "cellosaurus": "CVCL_1056",
    "depmap": "ACH-000555",
    "disease": "Renal cell carcinoma",
    "species": "Homo sapiens"
  },
  "A-673": {
    "cellosaurus": "CVCL_0080",
    "depmap": "ACH-000052",
    "disease": "Ewing sarcoma",
    "species": "Homo sapiens"
  },
  "A549": {
    "cellosaurus": "CVCL_0023",
    "depmap": "ACH-000681",
    "disease": "Lung adenocarcinoma",
    "species": "Homo sapiens"
  },
  "AGS": {
    "cellosaurus": "CVCL_0139",
    "depmap": "ACH-000880",
    "disease": "Gastric adenocarcinoma",
    "species": "Homo sapiens"
  },
  "AN3 CA": {
    "cellosaurus": "CVCL_0028",
    "depmap": "ACH-000940",
    "disease": "Acanthosis nigricans",
    "species": "Homo sapiens"
  },
  "ARK1": {
    "cellosaurus": "CVCL_IV72",
    "disease": "Endometrial serous adenocarcinoma",
    "species": "Homo sapiens"
  },
  "AsPC-1": {
    "cellosaurus": "CVCL_0152",
    "depmap": "ACH-000222",
    "disease": "Pancreatic ductal adenocarcinoma",
    "species": "Homo sapiens"
  },
  "B16-F10": {
    "cellosaurus": "CVCL_0159",
    "disease": "Mouse melanoma",
    "species": "Mus musculus"
  },
  "BCPAP": {
    "cellosaurus": "CVCL_0153",
    "depmap": "ACH-000456",
    "disease": "Poorly differentiated thyroid gland carcinoma",
    "species": "Homo sapiens"
  },
  "BT-474": {
    "cellosaurus": "CVCL_0179",
    "depmap": "ACH-000927",
    "disease": "Invasive breast carcinoma of no special type",
    "species": "Homo sapiens"
  },
  "BT142": {
    "cellosaurus": "CVCL_D718",
    "disease": "Oligoastrocytoma",
    "species": "Homo sapiens"
  },
  "Ba/F3": {
    "cellosaurus": "CVCL_0161",
    "species": "Mus musculus"
  },
  "BxPC-3": {
    "cellosaurus": "CVCL_0186",
    "depmap": "ACH-000535",
    "disease": "Pancreatic ductal adenocarcinoma",
    "species": "Homo sapiens"
  },
  "C-33 A": {
    "cellosaurus": "CVCL_1094",
    "depmap": "ACH-001333",
    "disease": "Human papillomavirus-independent cervical squamous cell carcinoma",
    "species": "Homo sapiens"
  },
  "C4-2": {
    "cellosaurus": "CVCL_4782",
    "disease": "Prostate carcinoma",
    "species": "Homo sapiens"
  },
  "C4-2B": {
    "cellosaurus": "CVCL_4784",
    "disease": "Prostate carcinoma",
    "species": "Homo sapiens"
  },
  "CAL 27": {
    "cellosaurus": "CVCL_1107",
    "depmap": "ACH-000832",
    "disease": "Tongue adenosquamous carcinoma",
    "species": "Homo sapiens"
  },
  "CAMA-1": {
    "cellosaurus": "CVCL_1115",
    "depmap": "ACH-000783",
    "disease": "Breast adenocarcinoma",
    "species": "Homo sapiens"
  },
  "COLO 205": {
    "cellosaurus": "CVCL_0218",
    "depmap": "ACH-001039",
    "disease": "Colon adenocarcinoma",
    "species": "Homo sapiens"
  },
  "COV362": {
    "cellosaurus": "CVCL_2420",
    "depmap": "ACH-000278",
    "disease": "High grade ovarian serous adenocarcinoma",
    "species": "Homo sapiens"
  },
  "CT-2A": {
    "cellosaurus": "CVCL_ZJ44",
    "disease": "Mouse glioblastoma",
    "species": "Mus musculus"
  },
  "CT26": {
    "cellosaurus": "CVCL_7254",
    "disease": "Mouse colon adenocarcinoma",
    "species": "Mus musculus"
  },
  "CaSki": {
    "cellosaurus": "CVCL_1100",
    "depmap": "ACH-001336",
    "disease": "Human papillomavirus-related cervical squamous cell carcinoma",
    "species": "Homo sapiens"
  },
  "Caki-1": {
    "cellosaurus": "CVCL_0234",
    "depmap": "ACH-000433",
    "disease": "Clear cell renal cell carcinoma",
    "species": "Homo sapiens"
  },
  "Calu-1": {
    "cellosaurus": "CVCL_0608",
    "depmap": "ACH-000511",
    "disease": "Lung squamous cell carcinoma",
    "species": "Homo sapiens"
  },
  "Calu-3": {
    "cellosaurus": "CVCL_0609",
    "depmap": "ACH-000392",
    "disease": "Lung adenocarcinoma",
    "species": "Homo sapiens"
  },
  "Capan-1": {
    "cellosaurus": "CVCL_0237",
    "depmap": "ACH-000354",
    "disease": "Pancreatic ductal adenocarcinoma",
    "species": "Homo sapiens"
  },
  "D283 Med": {
    "cellosaurus": "CVCL_1155",
    "depmap": "ACH-000055",
    "disease": "Medulloblastoma, non-WNT/non-SHH, group 3",
    "species": "Homo sapiens"
  },
  "D425 Med": {
    "cellosaurus": "CVCL_1275",
    "depmap": "ACH-001053",
    "disease": "Medulloblastoma, non-WNT/non-SHH, group 3",
    "species": "Homo sapiens"
  },
  "DLD-1": {
    "cellosaurus": "CVCL_0248",
    "depmap": "ACH-001061",
    "disease": "Colon adenocarcinoma",
    "species": "Homo sapiens"
  },
  "DLD-1 BRCA2-/-": {
    "cellosaurus": "CVCL_HD56",
    "disease": "Colon adenocarcinoma",
    "species": "Homo sapiens"
  },
  "DMS 114": {
    "cellosaurus": "CVCL_1174",
    "depmap": "ACH-000530",
    "disease": "Thoracic SMARCA4-deficient undifferentiated tumor",
    "species": "Homo sapiens"
  },
  "DU145": {
    "cellosaurus": "CVCL_0105",
    "depmap": "ACH-000979",
    "disease": "Prostate carcinoma",
    "species": "Homo sapiens"
  },
  "Daoy": {
    "cellosaurus": "CVCL_1167",
    "depmap": "ACH-000211",
    "disease": "Medulloblastoma, SHH-activated, TP53-mutant",
    "species": "Homo sapiens"
  },
  "Daudi": {
    "cellosaurus": "CVCL_0008",
    "depmap": "ACH-000786",
    "disease": "EBV-related Burkitt lymphoma",
    "species": "Homo sapiens"
  },
  "Detroit 562": {
    "cellosaurus": "CVCL_1171",
    "depmap": "ACH-000207",
    "disease": "Pharyngeal squamous cell carcinoma",
    "species": "Homo sapiens"
  },
  "EGI-1": {
    "cellosaurus": "CVCL_1193",
    "depmap": "ACH-001494",
    "disease": "Cholangiocarcinoma",
    "species": "Homo sapiens"
  },
  "EMT6": {
    "cellosaurus": "CVCL_1923",
    "disease": "Malignant neoplasms of the mouse mammary gland",
    "species": "Mus musculus"
  },
  "EW8": {
    "cellosaurus": "CVCL_1658",
    "depmap": "ACH-000499",
    "disease": "Ewing sarcoma",
    "species": "Homo sapiens"
  },
  "FLO-1": {
    "cellosaurus": "CVCL_2045",
    "depmap": "ACH-001500",
    "disease": "Barrett adenocarcinoma",
    "species": "Homo sapiens"
  },
  "FaDu": {
    "cellosaurus": "CVCL_1218",
    "depmap": "ACH-000846",
    "disease": "Hypopharyngeal squamous cell carcinoma",
    "species": "Homo sapiens"
  },
  "GIST-T1": {
    "cellosaurus": "CVCL_4976",
    "depmap": "ACH-002332",
    "disease": "Gastrointestinal stromal tumor",
    "species": "Homo sapiens"
  },
  "GIST430": {
    "cellosaurus": "CVCL_7040",
    "disease": "Gastrointestinal stromal tumor",
    "species": "Homo sapiens"
  },
  "GIST48": {
    "cellosaurus": "CVCL_7041",
    "disease": "Gastrointestinal stromal tumor",
    "species": "Homo sapiens"
  },
  "GIST882": {
    "cellosaurus": "CVCL_7044",
    "disease": "Gastrointestinal stromal tumor",
    "species": "Homo sapiens"
  },
  "GL261": {
    "cellosaurus": "CVCL_Y003",
    "disease": "Mouse glioblastoma",
    "species": "Mus musculus"
  },
  "HBL-1": {
    "cellosaurus": "CVCL_4213",
    "disease": "Diffuse large B-cell lymphoma activated B-cell type",
    "species": "Homo sapiens"
  },
  "HCC1806": {
    "cellosaurus": "CVCL_1258",
    "depmap": "ACH-000624",
    "disease": "Breast acantholytic squamous cell carcinoma",
    "species": "Homo sapiens"
  },
  "HCC1937": {
    "cellosaurus": "CVCL_0290",
    "depmap": "ACH-000223",
    "disease": "Breast ductal carcinoma",
    "species": "Homo sapiens"
  },
  "HCC1954": {
    "cellosaurus": "CVCL_1259",
    "depmap": "ACH-000859",
    "disease": "Breast ductal carcinoma",
    "species": "Homo sapiens"
  },
  "HCC4006": {
    "cellosaurus": "CVCL_1269",
    "depmap": "ACH-000066",
    "disease": "Lung adenocarcinoma",
    "species": "Homo sapiens"
  },
  "HCC827": {
    "cellosaurus": "CVCL_2063",
    "depmap": "ACH-000012",
    "disease": "Lung adenocarcinoma",
    "species": "Homo sapiens"
  },
  "HCT 116": {
    "cellosaurus": "CVCL_0291",
    "depmap": "ACH-000971",
    "disease": "Colon carcinoma",
    "species": "Homo sapiens"
  },
  "HEC-1-A": {
    "cellosaurus": "CVCL_0293",
    "depmap": "ACH-000954",
    "disease": "Type II endometrial adenocarcinoma",
    "species": "Homo sapiens"
  },
  "HG-3": {
    "cellosaurus": "CVCL_Y547",
    "depmap": "ACH-001520",
    "disease": "Chronic lymphocytic leukemia",
    "species": "Homo sapiens"
  },
  "HL-60": {
    "cellosaurus": "CVCL_0002",
    "depmap": "ACH-000002",
    "disease": "Adult acute myeloid leukemia with maturation",
    "species": "Homo sapiens"
  },
  "HMC-1": {
    "cellosaurus": "CVCL_0003",
    "disease": "Mast cell leukemia",
    "species": "Homo sapiens"
  },
  "HPAF-II": {
    "cellosaurus": "CVCL_0313",
    "depmap": "ACH-000094",
    "disease": "Pancreatic ductal adenocarcinoma",
    "species": "Homo sapiens"
  },
  "HT-1080": {
    "cellosaurus": "CVCL_0317",
    "depmap": "ACH-000054",
    "disease": "Fibrosarcoma",
    "species": "Homo sapiens"
  },
  "HT-29": {
    "cellosaurus": "CVCL_0320",
    "depmap": "ACH-000552",
    "disease": "Colon adenocarcinoma",
    "species": "Homo sapiens"
  },
  "HeLa": {
    "cellosaurus": "CVCL_0030",
    "depmap": "ACH-001086",
    "disease": "Human papillomavirus-related endocervical adenocarcinoma",
    "species": "Homo sapiens"
  },
  "Hep 3B": {
    "cellosaurus": "CVCL_0326",
    "depmap": "ACH-000625",
    "disease": "Childhood hepatocellular carcinoma",
    "species": "Homo sapiens"
  },
  "Hep-G2": {
    "cellosaurus": "CVCL_0027",
    "depmap": "ACH-000739",
    "disease": "Hepatoblastoma",
    "species": "Homo sapiens"
  },
  "Hepa 1-6": {
    "cellosaurus": "CVCL_0327",
    "disease": "Hepatocellular carcinoma of the mouse",
    "species": "Mus musculus"
  },
  "HuCCT1": {
    "cellosaurus": "CVCL_0324",
    "depmap": "ACH-000976",
    "disease": "Intrahepatic cholangiocarcinoma",
    "species": "Homo sapiens"
  },
  "Huh-7": {
    "cellosaurus": "CVCL_0336",
    "depmap": "ACH-000480",
    "disease": "Adult hepatocellular carcinoma",
    "species": "Homo sapiens"
  },
  "ID8": {
    "cellosaurus": "CVCL_IU14",
    "species": "Mus musculus"
  },
  "IMR-32": {
    "cellosaurus": "CVCL_0346",
    "depmap": "ACH-000310",
    "disease": "Neuroblastoma",
    "species": "Homo sapiens"
  },
  "Ishikawa": {
    "cellosaurus": "CVCL_2529",
    "depmap": "ACH-000961",
    "disease": "Type I endometrial adenocarcinoma",
    "species": "Homo sapiens"
  },
  "JIMT-1": {
    "cellosaurus": "CVCL_2077",
    "depmap": "ACH-000711",
    "disease": "Breast ductal carcinoma",
    "species": "Homo sapiens"
  },
  "JeKo-1": {
    "cellosaurus": "CVCL_1865",
    "depmap": "ACH-000357",
    "disease": "Mantle cell lymphoma",
    "species": "Homo sapiens"
  },
  "Jurkat": {
    "cellosaurus": "CVCL_0065",
    "depmap": "ACH-000995",
    "disease": "Childhood T acute lymphoblastic leukemia",
    "species": "Homo sapiens"
  },
  "K-562": {
    "cellosaurus": "CVCL_0004",
    "depmap": "ACH-000551",
    "disease": "Blast phase chronic myelogenous leukemia, BCR-ABL1 positive",
    "species": "Homo sapiens"
  },
  "K7M2": {
    "cellosaurus": "CVCL_V454",
    "disease": "Mouse osteosarcoma",
    "species": "Mus musculus"
  },
  "KATO III": {
    "cellosaurus": "CVCL_0371",
    "depmap": "ACH-000793",
    "disease": "Down syndrome",
    "species": "Homo sapiens"
  },
  "KCL-22": {
    "cellosaurus": "CVCL_2091",
    "depmap": "ACH-000983",
    "disease": "Chronic myelogenous leukemia, BCR-ABL1 positive",
    "species": "Homo sapiens"
  },
  "KLE": {
    "cellosaurus": "CVCL_1329",
    "depmap": "ACH-000293",
    "disease": "Type II endometrial adenocarcinoma",
    "species": "Homo sapiens"
  },
  "KMS-11": {
    "cellosaurus": "CVCL_2989",
    "depmap": "ACH-000714",
    "disease": "Plasma cell myeloma",
    "species": "Homo sapiens"
  },
  "KU812": {
    "cellosaurus": "CVCL_0379",
    "depmap": "ACH-000074",
    "disease": "Chronic myelogenous leukemia, BCR-ABL1 positive",
    "species": "Homo sapiens"
  },
  "KYSE-150": {
    "cellosaurus": "CVCL_1348",
    "depmap": "ACH-000855",
    "disease": "Esophageal squamous cell carcinoma",
    "species": "Homo sapiens"
  },
  "KYSE-30": {
    "cellosaurus": "CVCL_1351",
    "depmap": "ACH-000777",
    "disease": "Esophageal squamous cell carcinoma",
    "species": "Homo sapiens"
  },
  "Karpas-299": {
    "cellosaurus": "CVCL_1324",
    "depmap": "ACH-000053",
    "disease": "Anaplastic large cell lymphoma, ALK-positive",
    "species": "Homo sapiens"
  },
  "Karpas-422": {
    "cellosaurus": "CVCL_1325",
    "depmap": "ACH-000315",
    "disease": "Diffuse large B-cell lymphoma germinal center B-cell type",
    "species": "Homo sapiens"
  },
  "Kasumi-1": {
    "cellosaurus": "CVCL_0589",
    "depmap": "ACH-000263",
    "disease": "Childhood acute myeloid leukemia with maturation",
    "species": "Homo sapiens"
  },
  "Kelly": {
    "cellosaurus": "CVCL_2092",
    "depmap": "ACH-000259",
    "disease": "Neuroblastoma",
    "species": "Homo sapiens"
  },
  "Kuramochi": {
    "cellosaurus": "CVCL_1345",
    "depmap": "ACH-000524",
    "disease": "High grade ovarian serous adenocarcinoma",
    "species": "Homo sapiens"
  },
  "LAPC-4": {
    "cellosaurus": "CVCL_4744",
    "disease": "Prostate carcinoma",
    "species": "Homo sapiens"
  },
  "LL/2": {
    "cellosaurus": "CVCL_4358",
    "disease": "Malignant tumors of the mouse pulmonary system",
    "species": "Mus musculus"
  },
  "LN-229": {
    "cellosaurus": "CVCL_0393",
    "depmap": "ACH-000595",
    "disease": "Glioblastoma",
    "species": "Homo sapiens"
  },
  "LNCaP": {
    "cellosaurus": "CVCL_0395",
    "disease": "Prostate carcinoma",
    "species": "Homo sapiens"
  },
  "LS180": {
    "cellosaurus": "CVCL_0397",
    "depmap": "ACH-000957",
    "disease": "Colon adenocarcinoma",
    "species": "Homo sapiens"
  },
  "LoVo": {
    "cellosaurus": "CVCL_0399",
    "depmap": "ACH-000950",
    "disease": "Colon adenocarcinoma",
    "species": "Homo sapiens"
  },
  "MB49": {
    "cellosaurus": "CVCL_7076",
    "disease": "Mouse bladder transitional cell carcinoma",
    "species": "Mus musculus"
  },
  "MC38": {
    "cellosaurus": "CVCL_B288",
    "disease": "Mouse colon adenocarcinoma",
    "species": "Mus musculus"
  },
  "MCF-7": {
    "cellosaurus": "CVCL_0031",
    "depmap": "ACH-000019",
    "disease": "Invasive breast carcinoma of no special type",
    "species": "Homo sapiens"
  },
  "MDA PCa 2b": {
    "cellosaurus": "CVCL_4748",
    "depmap": "ACH-000952",
    "disease": "Prostate carcinoma",
    "species": "Homo sapiens"
  },
  "MDA-MB-134-VI": {
    "cellosaurus": "CVCL_0617",
    "depmap": "ACH-000044",
    "disease": "Invasive breast lobular carcinoma",
    "species": "Homo sapiens"
  },
  "MDA-MB-231": {
    "cellosaurus": "CVCL_0062",
    "depmap": "ACH-000768",
    "disease": "Breast adenocarcinoma",
    "species": "Homo sapiens"
  },
  "MDA-MB-361": {
    "cellosaurus": "CVCL_0620",
    "depmap": "ACH-000934",
    "disease": "Breast adenocarcinoma",
    "species": "Homo sapiens"
  },
  "MDA-MB-436": {
    "cellosaurus": "CVCL_0623",
    "depmap": "ACH-000573",
    "disease": "Invasive breast carcinoma of no special type",
    "species": "Homo sapiens"
  },
  "MDA-MB-453": {
    "cellosaurus": "CVCL_0418",
    "depmap": "ACH-000910",
    "disease": "Breast adenocarcinoma",
    "species": "Homo sapiens"
  },
  "MDA-MB-468": {
    "cellosaurus": "CVCL_0419",
    "depmap": "ACH-000849",
    "disease": "Breast adenocarcinoma",
    "species": "Homo sapiens"
  },
  "MEC-1": {
    "cellosaurus": "CVCL_1870",
    "depmap": "ACH-000405",
    "disease": "Chronic lymphocytic leukemia",
    "species": "Homo sapiens"
  },
  "MG-63": {
    "cellosaurus": "CVCL_0426",
    "depmap": "ACH-000359",
    "disease": "Osteosarcoma",
    "species": "Homo sapiens"
  },
  "MIA PaCa-2": {
    "cellosaurus": "CVCL_0428",
    "depmap": "ACH-000601",
    "disease": "Pancreatic undifferentiated carcinoma",
    "species": "Homo sapiens"
  },
  "MKN-45": {
    "cellosaurus": "CVCL_0434",
    "depmap": "ACH-000356",
    "disease": "Gastric adenocarcinoma",
    "species": "Homo sapiens"
  },
  "MM.1S": {
    "cellosaurus": "CVCL_8792",
    "depmap": "ACH-000763",
    "disease": "Plasma cell myeloma",
    "species": "Homo sapiens"
  },
  "MOC1": {
    "cellosaurus": "CVCL_ZD32",
    "disease": "Squamous cell carcinoma of the mouse oral cavity",
    "species": "Mus musculus"
  },
  "MOLM-13": {
    "cellosaurus": "CVCL_2119",
    "depmap": "ACH-000362",
    "disease": "Adult acute monocytic leukemia",
    "species": "Homo sapiens"
  },
  "MOLM-14": {
    "cellosaurus": "CVCL_7916",
    "depmap": "ACH-001574",
    "disease": "Adult acute myeloid leukemia",
    "species": "Homo sapiens"
  },
  "MSTO-211H": {
    "cellosaurus": "CVCL_1430",
    "depmap": "ACH-000335",
    "disease": "Pleural biphasic mesothelioma",
    "species": "Homo sapiens"
  },
  "MV4-11": {
    "cellosaurus": "CVCL_0064",
    "depmap": "ACH-000045",
    "disease": "Childhood acute monocytic leukemia",
    "species": "Homo sapiens"
  },
  "MZ-CRC-1": {
    "cellosaurus": "CVCL_A656",
    "disease": "Hereditary thyroid gland medullary carcinoma",
    "species": "Homo sapiens"
  },
  "NALM-6": {
    "cellosaurus": "CVCL_0092",
    "depmap": "ACH-000938",
    "disease": "Adult B acute lymphoblastic leukemia",
    "species": "Homo sapiens"
  },
  "NB-1": {
    "cellosaurus": "CVCL_1440",
    "depmap": "ACH-000804",
    "disease": "Neuroblastoma",
    "species": "Homo sapiens"
  },
  "NCI-H1299": {
    "cellosaurus": "CVCL_0060",
    "depmap": "ACH-000510",
    "disease": "Lung large cell carcinoma",
    "species": "Homo sapiens"
  },
  "NCI-H146": {
    "cellosaurus": "CVCL_1473",
    "depmap": "ACH-000506",
    "disease": "Lung small cell carcinoma",
    "species": "Homo sapiens"
  },
  "NCI-H1650": {
    "cellosaurus": "CVCL_1483",
    "depmap": "ACH-000035",
    "disease": "Minimally invasive lung adenocarcinoma",
    "species": "Homo sapiens"
  },
  "NCI-H1975": {
    "cellosaurus": "CVCL_1511",
    "depmap": "ACH-000587",
    "disease": "Lung adenocarcinoma",
    "species": "Homo sapiens"
  },
  "NCI-H2052": {
    "cellosaurus": "CVCL_1518",
    "depmap": "ACH-000153",
    "disease": "Pleural sarcomatoid mesothelioma",
    "species": "Homo sapiens"
  },
  "NCI-H2228": {
    "cellosaurus": "CVCL_1543",
    "depmap": "ACH-000447",
    "disease": "Lung adenocarcinoma",
    "species": "Homo sapiens"
  },
  "NCI-H226": {
    "cellosaurus": "CVCL_1544",
    "depmap": "ACH-000367",
    "disease": "Pleural epithelioid mesothelioma",
    "species": "Homo sapiens"
  },
  "NCI-H23": {
    "cellosaurus": "CVCL_1547",
    "depmap": "ACH-000900",
    "disease": "Lung adenocarcinoma",
    "species": "Homo sapiens"
  },
  "NCI-H28": {
    "cellosaurus": "CVCL_1555",
    "depmap": "ACH-000648",
    "disease": "Pleural malignant mesothelioma",
    "species": "Homo sapiens"
  },
  "NCI-H3122": {
    "cellosaurus": "CVCL_5160",
    "depmap": "ACH-000337",
    "disease": "Lung adenocarcinoma",
    "species": "Homo sapiens"
  },
  "NCI-H3255": {
    "cellosaurus": "CVCL_6831",
    "depmap": "ACH-000109",
    "disease": "Lung adenocarcinoma",
    "species": "Homo sapiens"
  },
  "NCI-H358": {
    "cellosaurus": "CVCL_1559",
    "depmap": "ACH-000860",
    "disease": "Minimally invasive lung adenocarcinoma",
    "species": "Homo sapiens"
  },
  "NCI-H460": {
    "cellosaurus": "CVCL_0459",
    "depmap": "ACH-000463",
    "disease": "Lung large cell carcinoma",
    "species": "Homo sapiens"
  },
  "NCI-H660": {
    "cellosaurus": "CVCL_1576",
    "depmap": "ACH-000177",
    "disease": "Prostate small cell carcinoma",
    "species": "Homo sapiens"
  },
  "NCI-H69": {
    "cellosaurus": "CVCL_1579",
    "depmap": "ACH-000358",
    "disease": "Lung small cell carcinoma",
    "species": "Homo sapiens"
  },
  "NCI-H82": {
    "cellosaurus": "CVCL_1591",
    "depmap": "ACH-000355",
    "disease": "Lung small cell carcinoma",
    "species": "Homo sapiens"
  },
  "NCI-H929": {
    "cellosaurus": "CVCL_1600",
    "depmap": "ACH-000050",
    "disease": "Plasma cell myeloma",
    "species": "Homo sapiens"
  },
  "NCI-N87": {
    "cellosaurus": "CVCL_1603",
    "depmap": "ACH-000427",
    "disease": "Gastric tubular adenocarcinoma",
    "species": "Homo sapiens"
  },
  "NUGC-3": {
    "cellosaurus": "CVCL_1612",
    "depmap": "ACH-000911",
    "disease": "Gastric adenocarcinoma",
    "species": "Homo sapiens"
  },
  "OCI-AML3": {
    "cellosaurus": "CVCL_1844",
    "depmap": "ACH-000336",
    "disease": "Adult acute myelomonocytic leukemia",
    "species": "Homo sapiens"
  },
  "OCI-LY1": {
    "cellosaurus": "CVCL_1879",
    "disease": "Diffuse large B-cell lymphoma",
    "species": "Homo sapiens"
  },
  "OCI-LY10": {
    "cellosaurus": "CVCL_8795",
    "depmap": "ACH-001146",
    "disease": "Diffuse large B-cell lymphoma activated B-cell type",
    "species": "Homo sapiens"
  },
  "OCI-LY3": {
    "cellosaurus": "CVCL_8800",
    "depmap": "ACH-000158",
    "disease": "Diffuse large B-cell lymphoma activated B-cell type",
    "species": "Homo sapiens"
  },
  "OE19": {
    "cellosaurus": "CVCL_1622",
    "depmap": "ACH-000679",
    "disease": "Esophageal adenocarcinoma",
    "species": "Homo sapiens"
  },
  "OE33": {
    "cellosaurus": "CVCL_0471",
    "depmap": "ACH-000383",
    "disease": "Barrett adenocarcinoma",
    "species": "Homo sapiens"
  },
  "OSU-CLL": {
    "cellosaurus": "CVCL_Y382",
    "disease": "Chronic lymphocytic leukemia",
    "species": "Homo sapiens"
  },
  "OVCAR-3": {
    "cellosaurus": "CVCL_0465",
    "depmap": "ACH-000001",
    "disease": "High grade ovarian serous adenocarcinoma",
    "species": "Homo sapiens"
  },
  "OVCAR-8": {
    "cellosaurus": "CVCL_1629",
    "depmap": "ACH-000696",
    "disease": "High grade ovarian serous adenocarcinoma",
    "species": "Homo sapiens"
  },
  "PANC-1": {
    "cellosaurus": "CVCL_0480",
    "depmap": "ACH-000164",
    "disease": "Pancreatic ductal adenocarcinoma",
    "species": "Homo sapiens"
  },
  "PC-3": {
    "cellosaurus": "CVCL_0035",
    "depmap": "ACH-000090",
    "disease": "Prostate carcinoma",
    "species": "Homo sapiens"
  },
  "PC-9": {
    "cellosaurus": "CVCL_B260",
    "depmap": "ACH-000779",
    "disease": "Lung adenocarcinoma",
    "species": "Homo sapiens"
  },
  "PEO1": {
    "cellosaurus": "CVCL_2686",
    "depmap": "ACH-001630",
    "disease": "BRCA2 syndrome",
    "species": "Homo sapiens"
  },
  "RBE": {
    "cellosaurus": "CVCL_4896",
    "depmap": "ACH-001856",
    "disease": "Intrahepatic cholangiocarcinoma",
    "species": "Homo sapiens"
  },
  "REC-1": {
    "cellosaurus": "CVCL_1884",
    "depmap": "ACH-000068",
    "disease": "Mantle cell lymphoma",
    "species": "Homo sapiens"
  },
  "REH": {
    "cellosaurus": "CVCL_1650",
    "depmap": "ACH-000960",
    "disease": "Childhood B acute lymphoblastic leukemia",
    "species": "Homo sapiens"
  },
  "RENCA": {
    "cellosaurus": "CVCL_2174",
    "disease": "Mouse kidney carcinoma",
    "species": "Mus musculus"
  },
  "RKO": {
    "cellosaurus": "CVCL_0504",
    "depmap": "ACH-000943",
    "disease": "Colon carcinoma",
    "species": "Homo sapiens"
  },
  "RPMI 8226": {
    "cellosaurus": "CVCL_0014",
    "depmap": "ACH-000817",
    "disease": "Plasma cell myeloma",
    "species": "Homo sapiens"
  },
  "RS4;11": {
    "cellosaurus": "CVCL_0093",
    "depmap": "ACH-000874",
    "disease": "Adult B acute lymphoblastic leukemia",
    "species": "Homo sapiens"
  },
  "RT112": {
    "cellosaurus": "CVCL_1670",
    "depmap": "ACH-000473",
    "disease": "Bladder carcinoma",
    "species": "Homo sapiens"
  },
  "RT4": {
    "cellosaurus": "CVCL_0036",
    "depmap": "ACH-000242",
    "disease": "Bladder carcinoma",
    "species": "Homo sapiens"
  },
  "Raji": {
    "cellosaurus": "CVCL_0511",
    "depmap": "ACH-000654",
    "disease": "EBV-related Burkitt lymphoma",
    "species": "Homo sapiens"
  },
  "SEM": {
    "cellosaurus": "CVCL_0095",
    "depmap": "ACH-000782",
    "disease": "Childhood B acute lymphoblastic leukemia",
    "species": "Homo sapiens"
  },
  "SH-SY5Y": {
    "cellosaurus": "CVCL_0019",
    "depmap": "ACH-001188",
    "disease": "Neuroblastoma",
    "species": "Homo sapiens"
  },
  "SJSA-1": {
    "cellosaurus": "CVCL_1697",
    "depmap": "ACH-000748",
    "disease": "Osteosarcoma",
    "species": "Homo sapiens"
  },
  "SK-BR-3": {
    "cellosaurus": "CVCL_0033",
    "depmap": "ACH-000017",
    "disease": "Breast adenocarcinoma",
    "species": "Homo sapiens"
  },
  "SK-MEL-2": {
    "cellosaurus": "CVCL_0069",
    "depmap": "ACH-001190",
    "disease": "Melanoma",
    "species": "Homo sapiens"
  },
  "SK-MEL-28": {
    "cellosaurus": "CVCL_0526",
    "depmap": "ACH-000615",
    "disease": "Cutaneous melanoma",
    "species": "Homo sapiens"
  },
  "SK-N-AS": {
    "cellosaurus": "CVCL_1700",
    "depmap": "ACH-000260",
    "disease": "Neuroblastoma",
    "species": "Homo sapiens"
  },
  "SK-N-MC": {
    "cellosaurus": "CVCL_0530",
    "depmap": "ACH-000039",
    "disease": "Askin tumor",
    "species": "Homo sapiens"
  },
  "SK-OV-3": {
    "cellosaurus": "CVCL_0532",
    "depmap": "ACH-000811",
    "disease": "Ovarian serous cystadenocarcinoma",
    "species": "Homo sapiens"
  },
  "SNU-1079": {
    "cellosaurus": "CVCL_5008",
    "depmap": "ACH-000209",
    "disease": "Intrahepatic cholangiocarcinoma",
    "species": "Homo sapiens"
  },
  "SNU-16": {
    "cellosaurus": "CVCL_0076",
    "depmap": "ACH-000581",
    "disease": "Gastric adenocarcinoma",
    "species": "Homo sapiens"
  },
  "SNU-449": {
    "cellosaurus": "CVCL_0454",
    "depmap": "ACH-000420",
    "disease": "Adult hepatocellular carcinoma",
    "species": "Homo sapiens"
  },
  "SNU-601": {
    "cellosaurus": "CVCL_0101",
    "depmap": "ACH-000736",
    "disease": "Gastric signet ring cell adenocarcinoma",
    "species": "Homo sapiens"
  },
  "SU-DHL-1": {
    "cellosaurus": "CVCL_0538",
    "depmap": "ACH-000664",
    "disease": "Anaplastic large cell lymphoma, ALK-positive",
    "species": "Homo sapiens"
  },
  "SU-DHL-4": {
    "cellosaurus": "CVCL_0539",
    "depmap": "ACH-000365",
    "disease": "Diffuse large B-cell lymphoma germinal center B-cell type",
    "species": "Homo sapiens"
  },
  "SU-DHL-6": {
    "cellosaurus": "CVCL_2206",
    "depmap": "ACH-000611",
    "disease": "Diffuse large B-cell lymphoma germinal center B-cell type",
    "species": "Homo sapiens"
  },
  "SUM149PT": {
    "cellosaurus": "CVCL_3422",
    "depmap": "ACH-001390",
    "disease": "Breast inflammatory carcinoma",
    "species": "Homo sapiens"
  },
  "SUP-B15": {
    "cellosaurus": "CVCL_0103",
    "depmap": "ACH-000059",
    "disease": "Childhood B acute lymphoblastic leukemia with t(9;22)(q34.1;q11.2) BCR-ABL1",
    "species": "Homo sapiens"
  },
  "SW1353": {
    "cellosaurus": "CVCL_0543",
    "depmap": "ACH-000418",
    "disease": "Primary central chondrosarcoma",
    "species": "Homo sapiens"
  },
  "SW1573": {
    "cellosaurus": "CVCL_1720",
    "depmap": "ACH-000677",
    "disease": "Minimally invasive lung adenocarcinoma",
    "species": "Homo sapiens"
  },
  "SW480": {
    "cellosaurus": "CVCL_0546",
    "depmap": "ACH-000842",
    "disease": "Colon adenocarcinoma",
    "species": "Homo sapiens"
  },
  "SW620": {
    "cellosaurus": "CVCL_0547",
    "depmap": "ACH-000651",
    "disease": "Colon adenocarcinoma",
    "species": "Homo sapiens"
  },
  "Saos-2": {
    "cellosaurus": "CVCL_0548",
    "depmap": "ACH-000410",
    "disease": "Osteosarcoma",
    "species": "Homo sapiens"
  },
  "SiHa": {
    "cellosaurus": "CVCL_0032",
    "depmap": "ACH-000556",
    "disease": "Human papillomavirus-related cervical squamous cell carcinoma",
    "species": "Homo sapiens"
  },
  "T-47D": {
    "cellosaurus": "CVCL_0553",
    "depmap": "ACH-000147",
    "disease": "Invasive breast carcinoma of no special type",
    "species": "Homo sapiens"
  },
  "T24": {
    "cellosaurus": "CVCL_0554",
    "depmap": "ACH-000018",
    "disease": "Bladder carcinoma",
    "species": "Homo sapiens"
  },
  "T98G": {
    "cellosaurus": "CVCL_0556",
    "depmap": "ACH-000571",
    "disease": "Glioblastoma",
    "species": "Homo sapiens"
  },
  "TC-1": {
    "cellosaurus": "CVCL_4699",
    "species": "Mus musculus"
  },
  "TC-71": {
    "cellosaurus": "CVCL_2213",
    "depmap": "ACH-000424",
    "disease": "Ewing sarcoma",
    "species": "Homo sapiens"
  },
  "THP-1": {
    "cellosaurus": "CVCL_0006",
    "depmap": "ACH-000146",
    "disease": "Childhood acute monocytic leukemia",
    "species": "Homo sapiens"
  },
  "TMD8": {
    "cellosaurus": "CVCL_A442",
    "disease": "Diffuse large B-cell lymphoma activated B-cell type",
    "species": "Homo sapiens"
  },
  "TPC-1": {
    "cellosaurus": "CVCL_6298",
    "disease": "Thyroid gland papillary carcinoma",
    "species": "Homo sapiens"
  },
  "TS603": {
    "cellosaurus": "CVCL_A5HW",
    "disease": "Anaplastic oligodendroglioma",
    "species": "Homo sapiens"
  },
  "TT": {
    "cellosaurus": "CVCL_1774",
    "depmap": "ACH-001321",
    "disease": "Hereditary thyroid gland medullary carcinoma",
    "species": "Homo sapiens"
  },
  "U-251MG": {
    "cellosaurus": "CVCL_0021",
    "depmap": "ACH-000232",
    "disease": "Astrocytoma",
    "species": "Homo sapiens"
  },
  "U-87MG ATCC": {
    "cellosaurus": "CVCL_0022",
    "depmap": "ACH-000075",
    "disease": "Glioblastoma",
    "species": "Homo sapiens"
  },
  "U266": {
    "cellosaurus": "CVCL_0566",
    "depmap": "ACH-000626",
    "disease": "Plasma cell myeloma",
    "species": "Homo sapiens"
  },
  "U2OS": {
    "cellosaurus": "CVCL_0042",
    "depmap": "ACH-000364",
    "disease": "Osteosarcoma",
    "species": "Homo sapiens"
  },
  "UM-SCC-47": {
    "cellosaurus": "CVCL_7759",
    "disease": "Tongue squamous cell carcinoma",
    "species": "Homo sapiens"
  },
  "UM-UC-3": {
    "cellosaurus": "CVCL_1783",
    "depmap": "ACH-000522",
    "disease": "Bladder carcinoma",
    "species": "Homo sapiens"
  },
  "UWB1.289": {
    "cellosaurus": "CVCL_B079",
    "depmap": "ACH-001418",
    "disease": "BRCA1 syndrome",
    "species": "Homo sapiens"
  },
  "VCaP": {
    "cellosaurus": "CVCL_2235",
    "depmap": "ACH-000115",
    "disease": "Prostate carcinoma",
    "species": "Homo sapiens"
  },
  "WM-266-4": {
    "cellosaurus": "CVCL_2765",
    "depmap": "ACH-001239",
    "disease": "Melanoma",
    "species": "Homo sapiens"
  },
  "YUMM1.7": {
    "cellosaurus": "CVCL_JK16",
    "disease": "Mouse melanoma",
    "species": "Mus musculus"
  },
  "YUMMER1.7": {
    "cellosaurus": "CVCL_A2AX",
    "disease": "Mouse melanoma",
    "species": "Mus musculus"
  },
  "ZR-75-1": {
    "cellosaurus": "CVCL_0588",
    "depmap": "ACH-000097",
    "disease": "Invasive breast carcinoma of no special type",
    "species": "Homo sapiens"
  }
};
