/**
 * Open-source projects relevant to oncology from the Open Medical Registry (https://openmedical.sh/), mapped to OnCo
 * fronts, technologies and cancers. GENERATED by scripts/fetch-openmedical.ts on 2026-09-10 from
 * https://openmedical.sh/v1/registry.json; the mapping lives in that script. Do not edit by hand.
 *
 * The registry corpus is MIT-licensed; each project keeps its own licence, which the registry reports as best it
 * could verify. `verified` means a person at the registry checked the record, not that OnCo has. Blurbs are one
 * sentence of the registry summary with punctuation normalised.
 */
export type OpenMedicalEntry = {
  id: string; name: string; url: string; homepage: string; category: string; licence: string; verified: boolean;
  blurb: string; sections: string[]; technologies?: string[]; cancers?: string[]; fetched: string;
};

export const OPENMEDICAL_GENERATED = "2026-09-10";
export const OPENMEDICAL_SITE = "https://openmedical.sh/";

export const openmedical: OpenMedicalEntry[] = [
  {
    "id": "3d-slicer",
    "name": "3D Slicer",
    "url": "https://openmedical.sh/registry/software/3d-slicer/",
    "homepage": "https://www.slicer.org",
    "category": "software",
    "licence": "Slicer-1.0",
    "verified": true,
    "blurb": "Desktop platform for medical image visualisation, segmentation, registration, and image-guided therapy research.",
    "sections": [
      "imaging",
      "surgery"
    ],
    "technologies": [
      "ct",
      "mri"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "ai4elife",
    "name": "ai4elife",
    "url": "https://openmedical.sh/registry/software/ai4elife/",
    "homepage": "https://github.com/KibromBerihu/ai4elife",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "This data-centric AI repository implements a robust deep learning method (LFBNet) for fully automated tumor segmentation in whole-body [18]F-FDG PET/CT images.",
    "sections": [
      "imaging",
      "radiopharma",
      "ai-computation"
    ],
    "technologies": [
      "fdg-pet",
      "pet-ct"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "arriba",
    "name": "arriba",
    "url": "https://openmedical.sh/registry/software/arriba/",
    "homepage": "https://github.com/suhrig/arriba",
    "category": "software",
    "licence": "GPL-3.0",
    "verified": false,
    "blurb": "Fast and accurate gene fusion detection from RNA-Seq data",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "rna-seq"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "balsamic",
    "name": "BALSAMIC",
    "url": "https://openmedical.sh/registry/software/balsamic/",
    "homepage": "https://balsamic.readthedocs.io/",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Bioinformatic Analysis pipeLine for SomAtic Mutations In Cancer",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "cgp",
      "wes-wgs"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "bart",
    "name": "BART (Berkeley Advanced Reconstruction Toolbox)",
    "url": "https://openmedical.sh/registry/software/bart/",
    "homepage": "https://mrirecon.codeberg.page/",
    "category": "software",
    "licence": "BSD-3-Clause",
    "verified": true,
    "blurb": "Toolbox for computational magnetic resonance imaging, providing calibration and iterative reconstruction methods.",
    "sections": [
      "imaging"
    ],
    "technologies": [
      "mri"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "brats-toolkit",
    "name": "BraTS-Toolkit",
    "url": "https://openmedical.sh/registry/software/brats-toolkit/",
    "homepage": "https://www.frontiersin.org/articles/10.3389/fnins.2020.00125/full",
    "category": "software",
    "licence": "AGPL-3.0",
    "verified": false,
    "blurb": "Code to preprocess, segment, and fuse glioma MRI scans based on the BraTS Toolkit manuscript.",
    "sections": [
      "imaging",
      "ai-computation"
    ],
    "technologies": [
      "mri"
    ],
    "cancers": [
      "glioblastoma"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "breast-cancer-classifier",
    "name": "breast_cancer_classifier",
    "url": "https://openmedical.sh/registry/software/breast-cancer-classifier/",
    "homepage": "https://ieeexplore.ieee.org/document/8861376",
    "category": "software",
    "licence": "AGPL-3.0",
    "verified": false,
    "blurb": "Deep Neural Networks Improve Radiologists' Performance in Breast Cancer Screening",
    "sections": [
      "early-detection",
      "ai-computation"
    ],
    "technologies": [
      "mammography",
      "radiology-ai-screening"
    ],
    "cancers": [
      "tnbc",
      "breast-hr-positive",
      "breast-her2-positive"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "calculate-suv",
    "name": "calculate-suv",
    "url": "https://openmedical.sh/registry/software/calculate-suv/",
    "homepage": "https://cornerstonejs.org",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Tiny library for calculating Standardized Uptake Value for Nuclear Medicine (i.e.",
    "sections": [
      "imaging",
      "radiopharma"
    ],
    "technologies": [
      "pet",
      "spect"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "camicroscope",
    "name": "caMicroscope",
    "url": "https://openmedical.sh/registry/devices/camicroscope/",
    "homepage": "https://github.com/camicroscope/caMicroscope",
    "category": "devices",
    "licence": "BSD-3-Clause",
    "verified": false,
    "blurb": "Digital pathology image viewer with support for human/machine generated annotations and markups.",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "histopathology-ihc"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "cancer-report-validator",
    "name": "cancer-report-validator",
    "url": "https://openmedical.sh/registry/data/cancer-report-validator/",
    "homepage": "https://github.com/CDCgov/cancer-report-validator",
    "category": "data",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "The Cancer Report Validator (CRV) is an interactive tool for validating the content of electronic submissions of cancer-related medical information prior to...",
    "sections": [
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "cancerfoundation",
    "name": "CancerFoundation",
    "url": "https://openmedical.sh/registry/software/cancerfoundation/",
    "homepage": "https://github.com/BoevaLab/CancerFoundation",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "CancerFoundation: A single-cell RNA sequencing foundation model to decipher drug resistance in cancer",
    "sections": [
      "ai-computation",
      "targeted-therapy"
    ],
    "technologies": [
      "single-cell-spatial"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "cellpyability",
    "name": "CellPyAbility",
    "url": "https://openmedical.sh/registry/therapeutics/cellpyability/",
    "homepage": "https://github.com/bindralab/CellPyAbility",
    "category": "therapeutics",
    "licence": "MIT",
    "verified": false,
    "blurb": "Software for the automated analysis of in cellulo high-throughput drug screening",
    "sections": [
      "drug-discovery"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "cellvit",
    "name": "CellViT",
    "url": "https://openmedical.sh/registry/software/cellvit/",
    "homepage": "https://doi.org/10.1016/j.media.2024.103143",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "CellViT: Vision Transformers for Precise Cell Segmentation and Classification",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "technologies": [
      "digital-pathology-ai"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "chembl-webresource-client",
    "name": "chembl_webresource_client",
    "url": "https://openmedical.sh/registry/therapeutics/chembl-webresource-client/",
    "homepage": "https://www.ebi.ac.uk/chembl/api/data/docs",
    "category": "therapeutics",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "Official Python client for accessing ChEMBL API",
    "sections": [
      "drug-discovery"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "circdna",
    "name": "circdna",
    "url": "https://openmedical.sh/registry/software/circdna/",
    "homepage": "https://nf-co.re/circdna",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Pipeline for the identification of extrachromosomal circular DNA (ecDNA) from Circle-seq, WGS, and ATAC-seq data that were generated from cancer and other...",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "wes-wgs"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "clairs",
    "name": "ClairS",
    "url": "https://openmedical.sh/registry/software/clairs/",
    "homepage": "https://github.com/HKU-BAL/ClairS",
    "category": "software",
    "licence": "BSD-3-Clause",
    "verified": false,
    "blurb": "ClairS: a deep-learning method for long-read tumor, normal pair somatic small variant calling",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "technologies": [
      "wes-wgs"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "clam",
    "name": "CLAM",
    "url": "https://openmedical.sh/registry/software/clam/",
    "homepage": "http://clam.mahmoodlab.org",
    "category": "software",
    "licence": "GPL-3.0",
    "verified": false,
    "blurb": "Open source tools for computational pathology - Nature BME",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "technologies": [
      "digital-pathology-ai"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "clinical-and-functional-outcomes-of-patient-specific-3d-prin",
    "name": "CLINICAL AND FUNCTIONAL OUTCOMES OF PATIENT-SPECIFIC 3D-PRINTED TITANIUM IMPLANTS IN RECO…",
    "url": "https://openmedical.sh/registry/manufacturing/clinical-and-functional-outcomes-of-patient-specific-3d-prin/",
    "homepage": "https://zenodo.org/records/19562531",
    "category": "manufacturing",
    "licence": "CC-BY-4.0",
    "verified": false,
    "blurb": "Extensive mandibular defects caused by malignant tumors, trauma, or severe inflammatory diseases represent one of the most complex challenges in modern...",
    "sections": [
      "surgery"
    ],
    "cancers": [
      "head-and-neck"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "comet",
    "name": "COMET",
    "url": "https://openmedical.sh/registry/software/comet/",
    "homepage": "https://chavi.ai",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "This is a repository to host the Contour Metrics (COMET) application for computing spatial overlap metrics for segmentations",
    "sections": [
      "radiation",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "cornerstone3d",
    "name": "cornerstone3D",
    "url": "https://openmedical.sh/registry/software/cornerstone3d/",
    "homepage": "https://cornerstonejs.org",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Cornerstone is a set of JavaScript libraries that can be used to build web-based medical imaging applications.",
    "sections": [
      "imaging",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "cytkit",
    "name": "Cytkit",
    "url": "https://openmedical.sh/registry/devices/cytkit/",
    "homepage": "https://cytkit.com/",
    "category": "devices",
    "licence": "CERN-OHL-S-2.0",
    "verified": true,
    "blurb": "Kit-form open-source spectral flow cytometer for volumetric cell counting and fluorescence panels of up to roughly ten colours.",
    "sections": [
      "diagnostics",
      "devices"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "cytomine",
    "name": "cytomine",
    "url": "https://openmedical.sh/registry/software/cytomine/",
    "homepage": "https://uliege.cytomine.org/",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "A web platform for collaborative analysis of very large bio-medical images",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "histopathology-ihc"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "dcm4che",
    "name": "dcm4che",
    "url": "https://openmedical.sh/registry/software/dcm4che/",
    "homepage": "https://www.dcm4che.org",
    "category": "software",
    "licence": "MPL-1.1",
    "verified": true,
    "blurb": "Collection of DICOM implementations and clinical imaging archive tooling used in production PACS deployments.",
    "sections": [
      "imaging"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "dcmqi",
    "name": "dcmqi",
    "url": "https://openmedical.sh/registry/software/dcmqi/",
    "homepage": "https://qiicr.gitbook.io/dcmqi-guide/",
    "category": "software",
    "licence": "BSD-3-Clause",
    "verified": false,
    "blurb": "dcmqi (DICOM for Quantitative Imaging) is a C++ library for conversion between imaging research formats and the standard DICOM representation for image...",
    "sections": [
      "imaging",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "decider",
    "name": "decider",
    "url": "https://openmedical.sh/registry/software/decider/",
    "homepage": "https://boehringer-ingelheim.github.io/decider/",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "The decider R package: decision making in multiple-arm oncology dose escalation trials with logistic regression",
    "sections": [
      "drug-discovery",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "deepsomatic",
    "name": "deepsomatic",
    "url": "https://openmedical.sh/registry/software/deepsomatic/",
    "homepage": "https://github.com/google/deepsomatic",
    "category": "software",
    "licence": "BSD-3-Clause",
    "verified": false,
    "blurb": "DeepSomatic is an analysis pipeline that uses a deep neural network to call somatic variants from tumor-normal and tumor-only sequencing data.",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "technologies": [
      "wes-wgs"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "deepspot",
    "name": "DeepSpot",
    "url": "https://openmedical.sh/registry/software/deepspot/",
    "homepage": "https://www.medrxiv.org/content/10.1101/2025.02.09.25321567v3",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "DeepSpot: Deep learning model for predicting spatial transcriptomics from H&E histopathology images.",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "technologies": [
      "single-cell-spatial",
      "digital-pathology-ai"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "dicom-microscopy-viewer",
    "name": "dicom-microscopy-viewer",
    "url": "https://openmedical.sh/registry/software/dicom-microscopy-viewer/",
    "homepage": "https://imagingdatacommons.github.io/dicom-microscopy-viewer/",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Web-based DICOM slide microscopy viewer library",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "histopathology-ihc"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "dicomautomaton",
    "name": "DICOMautomaton",
    "url": "https://openmedical.sh/registry/software/dicomautomaton/",
    "homepage": "https://halclark.ca",
    "category": "software",
    "licence": "GPL-3.0",
    "verified": false,
    "blurb": "A multipurpose tool for medical physics.",
    "sections": [
      "radiation",
      "imaging"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "dicoogle",
    "name": "dicoogle",
    "url": "https://openmedical.sh/registry/software/dicoogle/",
    "homepage": "http://www.dicoogle.com/",
    "category": "software",
    "licence": "GPL-3.0",
    "verified": false,
    "blurb": "Dicoogle - Open Source PACS",
    "sections": [
      "imaging"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "discover",
    "name": "DISCOVER",
    "url": "https://openmedical.sh/registry/software/discover/",
    "homepage": "https://github.com/NKI-CCB/DISCOVER",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "DISCOVER co-occurrence and mutual exclusivity analysis for cancer genomics data",
    "sections": [
      "diagnostics"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "dnafusion",
    "name": "DNAfusion",
    "url": "https://openmedical.sh/registry/software/dnafusion/",
    "homepage": "https://github.com/CTrierMaansson/DNAfusion",
    "category": "software",
    "licence": "AGPL-3.0",
    "verified": false,
    "blurb": "Identification of gene-fusions, including EML4-ALK",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "liquid-biopsy"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "echomods",
    "name": "echOmods",
    "url": "https://openmedical.sh/registry/devices/echomods/",
    "homepage": "https://un0rick.cc",
    "category": "devices",
    "licence": "TAPR-OHL-1.0",
    "verified": true,
    "blurb": "Open-source ultrasound processing modules and building blocks, analogue front ends, FPGA acquisition and pulser boards for do-it-yourself echography.",
    "sections": [
      "imaging",
      "devices"
    ],
    "technologies": [
      "ultrasound"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "epimethex",
    "name": "EpiMethEx",
    "url": "https://openmedical.sh/registry/data/epimethex/",
    "homepage": "https://github.com/giupardeb/EpiMethEx",
    "category": "data",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "EpiMethEx (Epigenetic Methylation and Expression), a R package to perform a large-scale integrated analysis by cyclic correlation analyses between...",
    "sections": [
      "epigenetics",
      "diagnostics"
    ],
    "technologies": [
      "methylation-profiling"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "eva",
    "name": "eva",
    "url": "https://openmedical.sh/registry/software/eva/",
    "homepage": "https://kaiko-ai.github.io/eva/",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "Evaluation framework for oncology foundation models (FMs)",
    "sections": [
      "ai-computation",
      "imaging",
      "diagnostics"
    ],
    "technologies": [
      "pathology-foundation-model"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "foundation-cancer-image-biomarker",
    "name": "foundation-cancer-image-biomarker",
    "url": "https://openmedical.sh/registry/software/foundation-cancer-image-biomarker/",
    "homepage": "https://aim-harvard.github.io/foundation-cancer-image-biomarker/",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Code and evaluation repository for the paper",
    "sections": [
      "imaging",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "gadgetron",
    "name": "Gadgetron",
    "url": "https://openmedical.sh/registry/software/gadgetron/",
    "homepage": "http://gadgetron.github.io/",
    "category": "software",
    "licence": "Gadgetron-1.0",
    "verified": true,
    "blurb": "Streaming framework for medical image reconstruction, used widely for MRI reconstruction pipelines.",
    "sections": [
      "imaging"
    ],
    "technologies": [
      "mri"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "galaxy",
    "name": "galaxy",
    "url": "https://openmedical.sh/registry/software/galaxy/",
    "homepage": "https://galaxyproject.org",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Data intensive science for everyone.",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "gate",
    "name": "Gate",
    "url": "https://openmedical.sh/registry/software/gate/",
    "homepage": "http://www.opengatecollaboration.org",
    "category": "software",
    "licence": "LGPL-3.0",
    "verified": false,
    "blurb": "Official public repository of Gate",
    "sections": [
      "radiation",
      "radiopharma",
      "imaging"
    ],
    "technologies": [
      "pet",
      "spect"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "gatelabr",
    "name": "GateLabR",
    "url": "https://openmedical.sh/registry/software/gatelabr/",
    "homepage": "https://david-priest.github.io/GateLabR",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Interactive flow and mass cytometry gating in R/Shiny on SingleCellExperiment objects, with Gating-ML round-trip.",
    "sections": [
      "diagnostics"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "gatk",
    "name": "gatk",
    "url": "https://openmedical.sh/registry/software/gatk/",
    "homepage": "https://software.broadinstitute.org/gatk",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "Official code repository for GATK versions 4 and up",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "wes-wgs"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "gatk-sv",
    "name": "gatk-sv",
    "url": "https://openmedical.sh/registry/software/gatk-sv/",
    "homepage": "https://broadinstitute.github.io/gatk-sv/",
    "category": "software",
    "licence": "BSD-3-Clause",
    "verified": false,
    "blurb": "A structural variation pipeline for short-read sequencing",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "wes-wgs"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "genomics-operations",
    "name": "genomics-operations",
    "url": "https://openmedical.sh/registry/data/genomics-operations/",
    "homepage": "https://fhir-gen-ops.herokuapp.com/",
    "category": "data",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "A public reference implementation of HL7 FHIR Genomics Operations (http://build.fhir.org/ig/HL7/genomics-reporting/operations.html)",
    "sections": [
      "ai-computation",
      "diagnostics"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "glass-ai",
    "name": "GLASS-AI",
    "url": "https://openmedical.sh/registry/software/glass-ai/",
    "homepage": "https://github.com/jlockhar/GLASS-AI",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Machine learning tool for analysis of lung adenocarcinoma tumors",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "technologies": [
      "digital-pathology-ai"
    ],
    "cancers": [
      "nsclc"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "gmic",
    "name": "GMIC",
    "url": "https://openmedical.sh/registry/software/gmic/",
    "homepage": "https://doi.org/10.1016/j.media.2020.101908",
    "category": "software",
    "licence": "AGPL-3.0",
    "verified": false,
    "blurb": "An interpretable classifier for high-resolution breast cancer screening images utilizing weakly supervised localization",
    "sections": [
      "early-detection",
      "ai-computation"
    ],
    "technologies": [
      "mammography",
      "radiology-ai-screening"
    ],
    "cancers": [
      "tnbc",
      "breast-hr-positive",
      "breast-her2-positive"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "hi-uni",
    "name": "hi-UNI",
    "url": "https://openmedical.sh/registry/software/hi-uni/",
    "homepage": "https://doi.org/10.1093/bioinformatics/btaf059",
    "category": "software",
    "licence": "GPL-3.0",
    "verified": false,
    "blurb": "Official code for Prediction of molecular subtypes for endometrial cancer based on hierarchical foundation model.",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "technologies": [
      "pathology-foundation-model"
    ],
    "cancers": [
      "endometrial"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "highdicom",
    "name": "highdicom",
    "url": "https://openmedical.sh/registry/software/highdicom/",
    "homepage": "https://highdicom.readthedocs.io",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "High-level DICOM abstractions for the Python programming language",
    "sections": [
      "imaging",
      "diagnostics"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "hips",
    "name": "HiPS",
    "url": "https://openmedical.sh/registry/software/hips/",
    "homepage": "https://github.com/PathologyDataScience/HiPS",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Histomic Prognostic Signature (HiPS): A population-level computational histologic signature for invasive breast cancer prognosis",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "technologies": [
      "digital-pathology-ai"
    ],
    "cancers": [
      "tnbc",
      "breast-hr-positive",
      "breast-her2-positive"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "fhir",
    "name": "HL7 FHIR",
    "url": "https://openmedical.sh/registry/data/fhir/",
    "homepage": "https://hl7.org/fhir",
    "category": "data",
    "licence": "not stated",
    "verified": true,
    "blurb": "Standard for exchanging healthcare information electronically, defining resources and a REST API for clinical data.",
    "sections": [
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "honeychrome",
    "name": "honeychrome",
    "url": "https://openmedical.sh/registry/software/honeychrome/",
    "homepage": "https://honeychrome.cytkit.com/",
    "category": "software",
    "licence": "LGPL-3.0",
    "verified": false,
    "blurb": "Open Source GUI App for Cytometry Acquisition and Analysis",
    "sections": [
      "diagnostics"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "human-papillomavirus-hpv-detection-in-vaginal-self-samples",
    "name": "Human papillomavirus (HPV) detection in vaginal self-samples: evaluation of eNat® as an a…",
    "url": "https://openmedical.sh/registry/software/human-papillomavirus-hpv-detection-in-vaginal-self-samples/",
    "homepage": "https://zenodo.org/records/6969054",
    "category": "software",
    "licence": "CC-BY-4.0",
    "verified": false,
    "blurb": "Human Papillomavirus (HPV) testing on self-collected samples allows for improved coverage rates of cervical cancer (CC) screening programs.",
    "sections": [
      "early-detection"
    ],
    "cancers": [
      "cervical"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "human-against-machine",
    "name": "human-against-machine",
    "url": "https://openmedical.sh/registry/software/human-against-machine/",
    "homepage": "https://tmfreiberg.github.io/human-against-machine/",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Deep learning on dermatoscopic images, with a browser demo that lets you try the task against the model.",
    "sections": [
      "early-detection",
      "ai-computation"
    ],
    "cancers": [
      "melanoma"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "immunopy",
    "name": "immunopy",
    "url": "https://openmedical.sh/registry/software/immunopy/",
    "homepage": "https://github.com/radioxoma/immunopy",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "IHC image real time analyzer",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "histopathology-ihc"
    ],
    "cancers": [
      "tnbc",
      "breast-hr-positive",
      "breast-her2-positive"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "invesalius3",
    "name": "invesalius3",
    "url": "https://openmedical.sh/registry/software/invesalius3/",
    "homepage": "https://invesalius.github.io/",
    "category": "software",
    "licence": "GPL-2.0",
    "verified": false,
    "blurb": "3D medical imaging reconstruction software",
    "sections": [
      "imaging",
      "surgery"
    ],
    "technologies": [
      "ct",
      "mri"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "itk",
    "name": "ITK",
    "url": "https://openmedical.sh/registry/software/itk/",
    "homepage": "https://itk.org",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "Insight Toolkit (ITK) -- Official Repository.",
    "sections": [
      "imaging",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "karnak",
    "name": "karnak",
    "url": "https://openmedical.sh/registry/software/karnak/",
    "homepage": "http://karnak.weasis.org",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "DICOM gateway for de-identification or tag morphing",
    "sections": [
      "imaging"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "kg4sl",
    "name": "KG4SL",
    "url": "https://openmedical.sh/registry/therapeutics/kg4sl/",
    "homepage": "https://github.com/JieZheng-ShanghaiTech/KG4SL",
    "category": "therapeutics",
    "licence": "MIT",
    "verified": false,
    "blurb": "Synthetic lethality (SL) is a promising gold mine for the discovery of anti-cancer drug targets.",
    "sections": [
      "drug-discovery",
      "targeted-therapy"
    ],
    "technologies": [
      "synthetic-lethality-approaches"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "legliv",
    "name": "legliv",
    "url": "https://openmedical.sh/registry/data/legliv/",
    "homepage": "https://github.com/steno-aarhus/legliv",
    "category": "data",
    "licence": "MIT",
    "verified": false,
    "blurb": "Substitution of red meat with legumes and risk of primary liver cancer in UK Biobank participants: A prospective cohort study",
    "sections": [
      "nutrition-lifestyle",
      "prevention"
    ],
    "cancers": [
      "hcc"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "linaqa",
    "name": "LinaQA",
    "url": "https://openmedical.sh/registry/software/linaqa/",
    "homepage": "https://github.com/alanphys/LinaQA",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "LinaQA (pronounced Linakwa) is a medical physics toolkit for radiotherapy, diagnostic radiology and nuclear medicine based on pylinac and pydicom.",
    "sections": [
      "radiation",
      "imaging",
      "radiopharma"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "maftools",
    "name": "maftools",
    "url": "https://openmedical.sh/registry/software/maftools/",
    "homepage": "http://bioconductor.org/packages/release/bioc/html/maftools.html",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Summarize, Analyze and Visualize MAF files from TCGA or in-house studies.",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "mammography-metarepository",
    "name": "mammography_metarepository",
    "url": "https://openmedical.sh/registry/software/mammography-metarepository/",
    "homepage": "https://arxiv.org/abs/2108.04800",
    "category": "software",
    "licence": "BSD-2-Clause",
    "verified": false,
    "blurb": "Meta-repository of screening mammography classifiers",
    "sections": [
      "early-detection",
      "ai-computation"
    ],
    "technologies": [
      "mammography",
      "radiology-ai-screening"
    ],
    "cancers": [
      "tnbc",
      "breast-hr-positive",
      "breast-her2-positive"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "marcos-server",
    "name": "MaRCoS Server",
    "url": "https://openmedical.sh/registry/devices/marcos-server/",
    "homepage": "https://github.com/vnegnev/marcos_server",
    "category": "devices",
    "licence": "MIT",
    "verified": true,
    "blurb": "Embedded server component of the MaRCoS open magnetic resonance control system, running on the scanner hardware.",
    "sections": [
      "imaging",
      "devices"
    ],
    "technologies": [
      "mri"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "mcmicro",
    "name": "mcmicro",
    "url": "https://openmedical.sh/registry/software/mcmicro/",
    "homepage": "https://nf-co.re/mcmicro",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "An end-to-end processing pipeline that transforms multi-channel whole-slide images into single-cell data.",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "single-cell-spatial"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "mercure",
    "name": "mercure",
    "url": "https://openmedical.sh/registry/software/mercure/",
    "homepage": "https://mercure-imaging.org",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "mercure DICOM Orchestrator",
    "sections": [
      "imaging",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "metro",
    "name": "METRO",
    "url": "https://openmedical.sh/registry/therapeutics/metro/",
    "homepage": "https://ccbr.github.io/METRO/",
    "category": "therapeutics",
    "licence": "MIT",
    "verified": false,
    "blurb": "Mouse nEoanTigen pRedictOr",
    "sections": [
      "immunotherapy",
      "drug-discovery"
    ],
    "technologies": [
      "neoantigen-mrna-vaccine"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "mgp1000",
    "name": "mgp1000",
    "url": "https://openmedical.sh/registry/software/mgp1000/",
    "homepage": "https://pblaney.github.io/mgp1000-docs/",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Nextflow bioinformatics pipeline for large-scale analysis of Multiple Myeloma genomes",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "wes-wgs"
    ],
    "cancers": [
      "multiple-myeloma"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "mipsegmentatorv1",
    "name": "MIPsegmentatorV1",
    "url": "https://openmedical.sh/registry/software/mipsegmentatorv1/",
    "homepage": "https://github.com/KibromBerihu/MIPsegmentatorV1",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "A 3D lesion segmentation method on whole-body PET images including automated quality control.",
    "sections": [
      "imaging",
      "radiopharma",
      "ai-computation"
    ],
    "technologies": [
      "pet"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "mitk",
    "name": "MITK",
    "url": "https://openmedical.sh/registry/software/mitk/",
    "homepage": "http://www.mitk.org",
    "category": "software",
    "licence": "BSD-3-Clause",
    "verified": false,
    "blurb": "The Medical Imaging Interaction Toolkit.",
    "sections": [
      "imaging"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "mlsym",
    "name": "MLSym",
    "url": "https://openmedical.sh/registry/software/mlsym/",
    "homepage": "https://github.com/lindvalllab/MLSym",
    "category": "software",
    "licence": "GPL-2.0",
    "verified": false,
    "blurb": "Deep learning for cancer symptoms monitoring on the basis of EHR unstructured clinical notes",
    "sections": [
      "supportive-care",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "monai-deploy-app-sdk",
    "name": "monai-deploy-app-sdk",
    "url": "https://openmedical.sh/registry/software/monai-deploy-app-sdk/",
    "homepage": "https://github.com/Project-MONAI/monai-deploy-app-sdk",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "MONAI Deploy App SDK offers a framework and associated tools to design, develop and verify AI-driven applications in the healthcare imaging domain.",
    "sections": [
      "imaging",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "monailabel",
    "name": "MONAILabel",
    "url": "https://openmedical.sh/registry/software/monailabel/",
    "homepage": "https://monai.readthedocs.io/projects/label/en/latest/",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "MONAI Label is an intelligent open source image labeling and learning tool.",
    "sections": [
      "imaging",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "moozy",
    "name": "MOOZY",
    "url": "https://openmedical.sh/registry/software/moozy/",
    "homepage": "https://atlasanalyticslab.github.io/MOOZY/",
    "category": "software",
    "licence": "CC-BY-NC-SA-4.0",
    "verified": false,
    "blurb": "A Patient-First Foundation Model for Computational Pathology",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "technologies": [
      "pathology-foundation-model"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "mtb-cbioportal",
    "name": "MTB-cbioportal",
    "url": "https://openmedical.sh/registry/data/mtb-cbioportal/",
    "homepage": "https://www.medizininformatik-initiative.de/de/pm4onco-personalized-medicine-oncology",
    "category": "data",
    "licence": "AGPL-3.0",
    "verified": false,
    "blurb": "cBioPortal is a data visualization tool for cancer genomics.",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "mutils-panoptic",
    "name": "MuTILs_Panoptic",
    "url": "https://openmedical.sh/registry/data/mutils-panoptic/",
    "homepage": "https://www.medrxiv.org/content/10.1101/2022.01.08.22268814v3",
    "category": "data",
    "licence": "MIT",
    "verified": false,
    "blurb": "A panoptic segmentation approach for tumor-infiltrating lymphocyte assessment: development of the MuTILs model and PanopTILs dataset.",
    "sections": [
      "diagnostics",
      "immunotherapy",
      "ai-computation"
    ],
    "technologies": [
      "digital-pathology-ai"
    ],
    "cancers": [
      "tnbc",
      "breast-hr-positive",
      "breast-her2-positive"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "nbia-toolkit",
    "name": "nbia-toolkit",
    "url": "https://openmedical.sh/registry/data/nbia-toolkit/",
    "homepage": "https://nbia-toolkit.readthedocs.io/en/latest/",
    "category": "data",
    "licence": "MIT",
    "verified": false,
    "blurb": "Python package for programmatic access to the National Biomedical Imaging Archive (NBIA) and The Cancer Imaging Archive (TCIA)",
    "sections": [
      "imaging",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "ocra",
    "name": "OCRA",
    "url": "https://openmedical.sh/registry/devices/ocra/",
    "homepage": "https://github.com/OpenMRI/ocra",
    "category": "devices",
    "licence": "GPL-3.0",
    "verified": true,
    "blurb": "Open-source MRI console built on low-cost Zynq FPGA hardware, providing spectrometer and acquisition control.",
    "sections": [
      "imaging",
      "devices"
    ],
    "technologies": [
      "mri"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "ohdsi-atlas",
    "name": "OHDSI ATLAS",
    "url": "https://openmedical.sh/registry/software/ohdsi-atlas/",
    "homepage": "http://atlas-demo.ohdsi.org/",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": true,
    "blurb": "Web application for designing and executing observational studies against OMOP-standardised patient data.",
    "sections": [
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "ohif-viewers",
    "name": "OHIF Viewer",
    "url": "https://openmedical.sh/registry/software/ohif-viewers/",
    "homepage": "https://docs.ohif.org/",
    "category": "software",
    "licence": "MIT",
    "verified": true,
    "blurb": "Zero-footprint web-based DICOM viewer for radiology and clinical research workflows.",
    "sections": [
      "imaging"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "omop-cdm",
    "name": "OMOP Common Data Model",
    "url": "https://openmedical.sh/registry/data/omop-cdm/",
    "homepage": "https://ohdsi.github.io/CommonDataModel",
    "category": "data",
    "licence": "not stated",
    "verified": true,
    "blurb": "Standardised relational model and DDLs for representing observational health data across institutions.",
    "sections": [
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "oncofiles",
    "name": "oncofiles",
    "url": "https://openmedical.sh/registry/software/oncofiles/",
    "homepage": "https://oncofiles.com",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Medical records scattered across Gmail and Google Drive?",
    "sections": [
      "supportive-care"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "onconova",
    "name": "onconova",
    "url": "https://openmedical.sh/registry/software/onconova/",
    "homepage": "https://onconova.github.io/docs/latest/",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Onconova is an open-source data platform aiming to enable reliable, structured data collection and analysis in precision oncology.",
    "sections": [
      "ai-computation",
      "diagnostics"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "oncoteam",
    "name": "oncoteam",
    "url": "https://openmedical.sh/registry/software/oncoteam/",
    "homepage": "https://oncoteam.cloud",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "AI patient advocacy tool for cancer treatment.",
    "sections": [
      "supportive-care"
    ],
    "technologies": [
      "ai-trial-matching"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "open-cravat",
    "name": "open-cravat",
    "url": "https://openmedical.sh/registry/software/open-cravat/",
    "homepage": "https://github.com/KarchinLab/open-cravat",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "A modular annotation tool for genomic variants",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "cgp"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "open-kbp",
    "name": "open-kbp",
    "url": "https://openmedical.sh/registry/software/open-kbp/",
    "homepage": "https://github.com/ababier/open-kbp",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Develop dose prediction models for knowledge-based planning in radiotherapy",
    "sections": [
      "radiation",
      "ai-computation"
    ],
    "technologies": [
      "imrt-igrt"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "openflexure-microscope",
    "name": "OpenFlexure Microscope",
    "url": "https://openmedical.sh/registry/devices/openflexure-microscope/",
    "homepage": "https://openflexure.org",
    "category": "devices",
    "licence": "CERN-OHL-1.2",
    "verified": true,
    "blurb": "3D-printed automated laboratory microscope with a monolithic flexure stage, designed to be built locally for a fraction of the cost of a commercial instrument.",
    "sections": [
      "diagnostics",
      "devices"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "openmrs",
    "name": "OpenMRS",
    "url": "https://openmedical.sh/registry/software/openmrs/",
    "homepage": "https://openmrs.org",
    "category": "software",
    "licence": "MPL-2.0",
    "verified": true,
    "blurb": "Modular, extensible electronic medical record platform designed for low-resource settings.",
    "sections": [
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "openoncology",
    "name": "openoncology",
    "url": "https://openmedical.sh/registry/software/openoncology/",
    "homepage": "https://github.com/immortal71/openoncology",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Open-source precision oncology platform that ranks FDA-approved and repurposing drug candidates from a patient's variant profile using OncoKB...",
    "sections": [
      "targeted-therapy",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "openscpca-analysis",
    "name": "OpenScPCA-analysis",
    "url": "https://openmedical.sh/registry/software/openscpca-analysis/",
    "homepage": "https://github.com/AlexsLemonade/OpenScPCA-analysis",
    "category": "software",
    "licence": "CC-BY-4.0 / BSD-3-Clause",
    "verified": false,
    "blurb": "An open, collaborative project to analyze data from the Single-cell Pediatric Cancer Atlas (ScPCA) Portal",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "technologies": [
      "single-cell-spatial"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "opentrons",
    "name": "Opentrons",
    "url": "https://openmedical.sh/registry/software/opentrons/",
    "homepage": "https://opentrons.com",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": true,
    "blurb": "Software for authoring and running protocols on Opentrons liquid-handling laboratory robots.",
    "sections": [
      "drug-discovery"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "uc2-git",
    "name": "openUC2",
    "url": "https://openmedical.sh/registry/devices/uc2-git/",
    "homepage": "https://openuc2.com",
    "category": "devices",
    "licence": "CERN-OHL-1.2 / MIT",
    "verified": true,
    "blurb": "Modular open-science microscope system built from 3D-printed cubes on a magnetic baseplate, reconfigurable for brightfield, fluorescence and light-sheet...",
    "sections": [
      "diagnostics",
      "devices"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "oral-cancer-speech-corpus-for-the-paper-objective-speech-ou",
    "name": "Oral cancer speech corpus for the paper \"Objective speech outcomes after surgical treatme…",
    "url": "https://openmedical.sh/registry/data/oral-cancer-speech-corpus-for-the-paper-objective-speech-ou/",
    "homepage": "https://zenodo.org/records/6401713",
    "category": "data",
    "licence": "CC-BY-4.0",
    "verified": false,
    "blurb": "Dataset accompanying the paper Objective speech outcomes after surgical treatment for oral cancer: An acoustic analysis of a spontaneous speech corpus...",
    "sections": [
      "supportive-care",
      "surgery"
    ],
    "cancers": [
      "head-and-neck"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "osii-mri",
    "name": "OSI² MRI (Utrecht ultra-low-field build)",
    "url": "https://openmedical.sh/registry/devices/osii-mri/",
    "homepage": "https://github.com/LilisProtoLab/osii_MRI",
    "category": "devices",
    "licence": "CERN-OHL-S-2.0 / CERN-OHL-W-2.0 / CERN-OHL-P-2.0",
    "verified": true,
    "blurb": "Build documentation for an open-source ultra-low-field MRI scanner constructed at Utrecht University, following the Open Source Imaging Initiative design.",
    "sections": [
      "imaging",
      "devices"
    ],
    "technologies": [
      "mri"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "osi2-one",
    "name": "OSI² ONE",
    "url": "https://openmedical.sh/registry/devices/osi2-one/",
    "homepage": "https://www.opensourceimaging.org/project/osii-one/",
    "category": "devices",
    "licence": "CERN-OHL-W-2.0 / GPL-3.0",
    "verified": true,
    "blurb": "Open-source low-field MRI scanner using a 50 mT permanent magnet, portable at roughly 150 kg, for head and extremity imaging.",
    "sections": [
      "imaging",
      "devices"
    ],
    "technologies": [
      "mri"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "pathml",
    "name": "pathml",
    "url": "https://openmedical.sh/registry/software/pathml/",
    "homepage": "https://pathml.org",
    "category": "software",
    "licence": "GPL-2.0",
    "verified": false,
    "blurb": "Tools for computational pathology",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "technologies": [
      "digital-pathology-ai"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "pharmoncox",
    "name": "pharmOncoX",
    "url": "https://openmedical.sh/registry/therapeutics/pharmoncox/",
    "homepage": "https://sigven.github.io/pharmOncoX/",
    "category": "therapeutics",
    "licence": "MIT",
    "verified": false,
    "blurb": "Targeted and non-targeted anticancer drugs and drug regimens",
    "sections": [
      "targeted-therapy",
      "chemotherapy",
      "drug-discovery"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "phenoncox",
    "name": "phenOncoX",
    "url": "https://openmedical.sh/registry/data/phenoncox/",
    "homepage": "https://sigven.github.io/phenOncoX",
    "category": "data",
    "licence": "MIT",
    "verified": false,
    "blurb": "Crossmapped phenotype ontologies for the oncology domain",
    "sections": [
      "ai-computation",
      "diagnostics"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "picai-prep",
    "name": "picai_prep",
    "url": "https://openmedical.sh/registry/data/picai-prep/",
    "homepage": "https://pi-cai.grand-challenge.org/",
    "category": "data",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "Preprocessing 3D medical images and image archives, geared towards prostate cancer detection in MRI.",
    "sections": [
      "imaging",
      "early-detection"
    ],
    "technologies": [
      "mri"
    ],
    "cancers": [
      "prostate"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "portpy",
    "name": "PortPy",
    "url": "https://openmedical.sh/registry/software/portpy/",
    "homepage": "https://github.com/PortPy-Project/PortPy",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "Opensource Python project for cancer radiation treatment planning [AAPM'23]",
    "sections": [
      "radiation",
      "ai-computation"
    ],
    "technologies": [
      "imrt-igrt"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "prostate-cancer-detection",
    "name": "prostate-cancer-detection",
    "url": "https://openmedical.sh/registry/software/prostate-cancer-detection/",
    "homepage": "https://github.com/DrHB/prostate-cancer-detection",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "CNN ensemble for prostate cancer Gleason grading",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "technologies": [
      "digital-pathology-ai"
    ],
    "cancers": [
      "prostate"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "pydicom",
    "name": "pydicom",
    "url": "https://openmedical.sh/registry/software/pydicom/",
    "homepage": "https://pydicom.github.io/pydicom/dev",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Read, modify and write DICOM files with python code",
    "sections": [
      "imaging",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "pymedphys",
    "name": "pymedphys",
    "url": "https://openmedical.sh/registry/software/pymedphys/",
    "homepage": "https://docs.pymedphys.com",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "A community effort to develop an open standard library for Medical Physics in Python.",
    "sections": [
      "radiation"
    ],
    "technologies": [
      "imrt-igrt"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "pyradiomics",
    "name": "pyradiomics",
    "url": "https://openmedical.sh/registry/software/pyradiomics/",
    "homepage": "http://pyradiomics.readthedocs.io/",
    "category": "software",
    "licence": "BSD-3-Clause",
    "verified": false,
    "blurb": "Open-source python package for the extraction of Radiomics features from 2D and 3D images and binary masks.",
    "sections": [
      "imaging",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "pyradise",
    "name": "pyradise",
    "url": "https://openmedical.sh/registry/software/pyradise/",
    "homepage": "https://pyradise.readthedocs.io/en/latest/index.html",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "PyRaDiSe: A Python package for DICOM-RT-based auto-segmentation pipeline construction and DICOM-RT data conversion",
    "sections": [
      "radiation",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "qupath",
    "name": "qupath",
    "url": "https://openmedical.sh/registry/software/qupath/",
    "homepage": "https://qupath.github.io",
    "category": "software",
    "licence": "GPL-3.0",
    "verified": false,
    "blurb": "QuPath - Open-source bioimage analysis for research",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "histopathology-ihc",
      "digital-pathology-ai"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "radcomp",
    "name": "RadComp",
    "url": "https://openmedical.sh/registry/software/radcomp/",
    "homepage": "https://radcomp.streamlit.app/",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Online Radiation Therapy BED EQD2 comparision schemes and Reirradiation analysis based on Python and Streamlit",
    "sections": [
      "radiation"
    ],
    "technologies": [
      "imrt-igrt",
      "brachytherapy"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "raidionics",
    "name": "Raidionics",
    "url": "https://openmedical.sh/registry/software/raidionics/",
    "homepage": "https://raidionics.github.io/",
    "category": "software",
    "licence": "BSD-2-Clause",
    "verified": false,
    "blurb": "Software for automatic segmentation and generation of standardized clinical reports of brain tumors from MRI volumes",
    "sections": [
      "imaging",
      "ai-computation"
    ],
    "technologies": [
      "mri"
    ],
    "cancers": [
      "glioblastoma"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "rgb-based-behavior-cloning-dataset-for-surgical-robotics-99",
    "name": "RGB-Based Behavior Cloning Dataset for Surgical Robotics: 99,522 Episodes of Optimal Demo…",
    "url": "https://openmedical.sh/registry/data/rgb-based-behavior-cloning-dataset-for-surgical-robotics-99/",
    "homepage": "https://zenodo.org/records/13830810",
    "category": "data",
    "licence": "CC-BY-4.0",
    "verified": false,
    "blurb": "Dataset Description : This dataset contains 99,522 episodes of RGB-based state-action-reward expert demonstrations collected from a reaching task within a...",
    "sections": [
      "surgery",
      "ai-computation"
    ],
    "technologies": [
      "robotic-surgery"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "robustnpc",
    "name": "RobustNPC",
    "url": "https://openmedical.sh/registry/software/robustnpc/",
    "homepage": "https://www.sciencedirect.com/science/article/pii/S016781402300018X",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Deep learning-based accurate delineation of primary gross tumor volume of nasopharyngeal carcinoma on heterogeneous magnetic resonance imaging: a...",
    "sections": [
      "radiation",
      "imaging",
      "ai-computation"
    ],
    "technologies": [
      "mri"
    ],
    "cancers": [
      "head-and-neck"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "rt-utils",
    "name": "rt-utils",
    "url": "https://openmedical.sh/registry/software/rt-utils/",
    "homepage": "https://github.com/qurit/rt-utils",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "A minimal Python library to facilitate the creation and manipulation of DICOM RTStructs.",
    "sections": [
      "radiation",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "sarek",
    "name": "sarek",
    "url": "https://openmedical.sh/registry/software/sarek/",
    "homepage": "https://nf-co.re/sarek",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Analysis pipeline to detect germline or somatic variants (pre-processing, variant calling and annotation) from WGS / targeted sequencing",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "wes-wgs",
      "cgp"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "scevan",
    "name": "SCEVAN",
    "url": "https://openmedical.sh/registry/software/scevan/",
    "homepage": "https://www.nature.com/articles/s41467-023-36790-9",
    "category": "software",
    "licence": "GPL-3.0",
    "verified": false,
    "blurb": "R package that automatically classifies the cells in the scRNA data by segregating non-malignant cells of tumor microenviroment from the malignant cells.",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "single-cell-spatial"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "sigprofilerextractor",
    "name": "SigProfilerExtractor",
    "url": "https://openmedical.sh/registry/software/sigprofilerextractor/",
    "homepage": "https://github.com/SigProfilerSuite/SigProfilerExtractor",
    "category": "software",
    "licence": "BSD-2-Clause",
    "verified": false,
    "blurb": "SigProfilerExtractor allows de novo extraction of mutational signatures from data generated in a matrix format.",
    "sections": [
      "diagnostics"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "sigprofilermatrixgenerator",
    "name": "SigProfilerMatrixGenerator",
    "url": "https://openmedical.sh/registry/software/sigprofilermatrixgenerator/",
    "homepage": "https://github.com/SigProfilerSuite/SigProfilerMatrixGenerator",
    "category": "software",
    "licence": "BSD-2-Clause",
    "verified": false,
    "blurb": "SigProfilerMatrixGenerator creates mutational matrices for all types of somatic mutations.",
    "sections": [
      "diagnostics"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "silicone-breast-phantoms-for-use-with-digital-imaging-elasto",
    "name": "Silicone Breast Phantoms for use with Digital Imaging Elasto-Tomography Breast Cancer Scr…",
    "url": "https://openmedical.sh/registry/software/silicone-breast-phantoms-for-use-with-digital-imaging-elasto/",
    "homepage": "https://doi.org/10.1016/j.ohx.2025.e00707",
    "category": "software",
    "licence": "not stated",
    "verified": false,
    "blurb": "Silicone Breast Phantoms for use with Digital Imaging Elasto-Tomography Breast Cancer Screening",
    "sections": [
      "early-detection",
      "devices"
    ],
    "cancers": [
      "tnbc",
      "breast-hr-positive",
      "breast-her2-positive"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "slicerradreirradiation",
    "name": "SlicerRadReirradiation",
    "url": "https://openmedical.sh/registry/software/slicerradreirradiation/",
    "homepage": "https://radcomp.streamlit.app/",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "3D Slicer extension for Radiotherapy clinical re-irradiation analysis.",
    "sections": [
      "radiation"
    ],
    "technologies": [
      "imrt-igrt",
      "brachytherapy"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "slim",
    "name": "slim",
    "url": "https://openmedical.sh/registry/software/slim/",
    "homepage": "https://imagingdatacommons.github.io/slim/",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "Interoperable web-based DICOM slide microscopy viewer and annotation tool",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "histopathology-ihc"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "stamp",
    "name": "STAMP",
    "url": "https://openmedical.sh/registry/software/stamp/",
    "homepage": "https://github.com/KatherLab/STAMP",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Solid Tumor Associative Modeling in Pathology",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "technologies": [
      "digital-pathology-ai"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "star",
    "name": "STAR",
    "url": "https://openmedical.sh/registry/software/star/",
    "homepage": "https://doi.org/10.1088/2057-1976/ade9cb",
    "category": "software",
    "licence": "GPL-3.0",
    "verified": false,
    "blurb": "Statistical Toolkit for Analysis of Radiotherapy DICOM Data",
    "sections": [
      "radiation"
    ],
    "technologies": [
      "imrt-igrt"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "state-cancer-profile-scraper",
    "name": "state-cancer-profile-scraper",
    "url": "https://openmedical.sh/registry/software/state-cancer-profile-scraper/",
    "homepage": "https://github.com/seandavi/state-cancer-profile-scraper/releases",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Bulk access and download state cancer profiles data.",
    "sections": [
      "prevention",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "survivmil-compayl",
    "name": "SurvivMIL_COMPAYL",
    "url": "https://openmedical.sh/registry/software/survivmil-compayl/",
    "homepage": "https://github.com/reednaidoo/SurvivMIL_COMPAYL",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "SurvivMIL: A multimodal, Multiple Instance Learning pipeline for survival outcome of Neuroblastoma Patients",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "technologies": [
      "digital-pathology-ai"
    ],
    "cancers": [
      "neuroblastoma"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "synprotx",
    "name": "SynProtX",
    "url": "https://openmedical.sh/registry/therapeutics/synprotx/",
    "homepage": "https://github.com/manbaritone/SynProtX",
    "category": "therapeutics",
    "licence": "MIT",
    "verified": false,
    "blurb": "SynProtX is a deep learning model leveraging large-scale proteomics, molecular graphs, and fingerprints to enhance the prediction of synergistic effects in...",
    "sections": [
      "drug-discovery",
      "ai-computation"
    ],
    "technologies": [
      "ai-drug-design"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "tcia-notebooks",
    "name": "TCIA_Notebooks",
    "url": "https://openmedical.sh/registry/data/tcia-notebooks/",
    "homepage": "https://cancerimagingarchive.net",
    "category": "data",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "Notebooks for working with The Cancer Imaging Archive datasets.",
    "sections": [
      "imaging",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "tiatoolbox",
    "name": "tiatoolbox",
    "url": "https://openmedical.sh/registry/software/tiatoolbox/",
    "homepage": "https://warwick.ac.uk/tia",
    "category": "software",
    "licence": "BSD-3-Clause",
    "verified": false,
    "blurb": "Computational Pathology Toolbox developed by TIA Centre, University of Warwick.",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "technologies": [
      "digital-pathology-ai"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "totalsegmentator-osirix-horos-plugin",
    "name": "TotalSegmentator-OsiriX-Horos-Plugin",
    "url": "https://openmedical.sh/registry/software/totalsegmentator-osirix-horos-plugin/",
    "homepage": "https://github.com/ThalesMMS/TotalSegmentator-OsiriX-Horos-Plugin",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "Swift Horos/OsiriX plugin that exports active CT/MR series, provisions an isolated Python TotalSegmentator environment, runs segmentation, and imports...",
    "sections": [
      "imaging",
      "ai-computation"
    ],
    "technologies": [
      "ct"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "trialmatchai",
    "name": "TrialMatchAI",
    "url": "https://openmedical.sh/registry/software/trialmatchai/",
    "homepage": "https://cbib.github.io/TrialMatchAI/",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "TrialMatchAI leverages large language models to streamline clinical trial matching by evaluating patient-specific clinical characteristics against trial...",
    "sections": [
      "ai-computation"
    ],
    "technologies": [
      "ai-trial-matching"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "trusglandsegmentation",
    "name": "TRUSGlandSegmentation",
    "url": "https://openmedical.sh/registry/software/trusglandsegmentation/",
    "homepage": "https://pubmed.ncbi.nlm.nih.gov/36148705/",
    "category": "software",
    "licence": "CC0-1.0",
    "verified": false,
    "blurb": "Domain Generalization for Prostate Segmentation in Transrectal Ultrasound Images: A Multi-center Study",
    "sections": [
      "imaging"
    ],
    "technologies": [
      "ultrasound"
    ],
    "cancers": [
      "prostate"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "ucscxenatools",
    "name": "UCSCXenaTools",
    "url": "https://openmedical.sh/registry/software/ucscxenatools/",
    "homepage": "https://docs.ropensci.org/UCSCXenaTools",
    "category": "software",
    "licence": "GPL-3.0",
    "verified": false,
    "blurb": "package: An R package for accessing genomics data from UCSC Xena platform, from cancer multi-omics to single-cell RNA-seq...",
    "sections": [
      "diagnostics",
      "ai-computation"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "umiseq-variant-calling",
    "name": "UMIseq_variant_calling",
    "url": "https://openmedical.sh/registry/software/umiseq-variant-calling/",
    "homepage": "https://github.com/BesenbacherLab/UMIseq_variant_calling",
    "category": "software",
    "licence": "MIT",
    "verified": false,
    "blurb": "Detect somatic SNVs from deep targeted UMI-seq cfDNA",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "liquid-biopsy"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "un0rick",
    "name": "un0rick",
    "url": "https://openmedical.sh/registry/devices/un0rick/",
    "homepage": "http://un0rick.cc",
    "category": "devices",
    "licence": "TAPR-OHL-1.0",
    "verified": true,
    "blurb": "Compact iCE40 FPGA and Raspberry Pi ultrasound board providing pulse-echo acquisition for imaging and non-destructive testing.",
    "sections": [
      "imaging",
      "devices"
    ],
    "technologies": [
      "ultrasound"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "vcf2fhir",
    "name": "vcf2fhir",
    "url": "https://openmedical.sh/registry/data/vcf2fhir/",
    "homepage": "https://github.com/elimuinformatics/vcf2fhir",
    "category": "data",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "vcf2fhir: a utility to convert VCF files into HL7 FHIR format for genomics-EHR integration",
    "sections": [
      "ai-computation",
      "diagnostics"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "victre-pipeline",
    "name": "VICTRE_PIPELINE",
    "url": "https://openmedical.sh/registry/software/victre-pipeline/",
    "homepage": "https://didsr.github.io/VICTRE_PIPELINE/",
    "category": "software",
    "licence": "CC0-1.0",
    "verified": false,
    "blurb": "Home for the unified VICTRE pipeline for in silico breast imaging.",
    "sections": [
      "early-detection",
      "imaging"
    ],
    "technologies": [
      "mammography"
    ],
    "cancers": [
      "tnbc",
      "breast-hr-positive",
      "breast-her2-positive"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "weasis",
    "name": "Weasis",
    "url": "https://openmedical.sh/registry/software/weasis/",
    "homepage": "https://weasis.org",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "Weasis is a web-based DICOM viewer for advanced medical imaging and seamless PACS integration.",
    "sections": [
      "imaging"
    ],
    "fetched": "2026-09-10"
  },
  {
    "id": "wsidicom",
    "name": "wsidicom",
    "url": "https://openmedical.sh/registry/software/wsidicom/",
    "homepage": "https://github.com/imi-bigpicture/wsidicom",
    "category": "software",
    "licence": "Apache-2.0",
    "verified": false,
    "blurb": "Python package for reading DICOM WSI file sets.",
    "sections": [
      "diagnostics"
    ],
    "technologies": [
      "histopathology-ihc"
    ],
    "fetched": "2026-09-10"
  }
];
