/**
 * Preclinical model availability: which cell lines, patient-derived xenografts (PDX), genetically engineered mouse
 * models (GEMMs) and organoid banks exist for each cancer and for the targets where genotype matters.
 *
 * Cell-line identifiers (Cellosaurus accession, DepMap ACH id, NCIt disease) are resolved by name from the
 * Cellosaurus API into `src/data/cell-line-ids.ts` (generated by scripts/fetch-cell-lines.ts); nothing is typed by
 * hand. Cell-line names follow Cellosaurus spelling. Repository links point at the portal, not at a specific model,
 * because model catalogues change weekly. GEMM rows cite the paper that described the model or the Mouse Tumor
 * Biology database entry.
 *
 * Rendered at /preclinical-models/ and on target dossiers.
 */
import { CELL_LINE_IDS, type CellLineIds } from "./cell-line-ids";

export type CellLine = { name: string; note: string; /** Target ids whose genotype this line models. */ targets?: string[] };
export type Repository = { name: string; url: string; note: string };
export type Gemm = { name: string; alleles: string; note: string; source: { label: string; url: string } };
export type ModelEntry = {
  /** Cancer id or target id. */
  subject: string;
  cellLines: CellLine[];
  pdx: Repository[];
  gemms: Gemm[];
  organoids: Repository[];
  caveats?: string[];
};

const doi = (d: string, label: string) => ({ label, url: `https://doi.org/${d}` });
const pmid = (id: string, label: string) => ({ label, url: `https://pubmed.ncbi.nlm.nih.gov/${id}/` });
const MTB = { label: "Mouse Tumor Biology database (JAX)", url: "https://tumor.informatics.jax.org/mtbwi/index.do" };

/** Shared repositories. */
export const REPOS = {
  pdmr: { name: "NCI Patient-Derived Models Repository (PDMR)", url: "https://pdmr.cancer.gov/", note: "Free-to-academics PDX, organoid and cell-line models with clinical annotation and sequencing." },
  pdxnet: { name: "PDXNet", url: "https://www.pdxnetwork.org/", note: "NCI consortium coordinating PDX development and co-clinical trials across US centres." },
  europdx: { name: "EurOPDX", url: "https://www.europdx.eu/", note: "European PDX consortium; models discoverable through the PDCM Finder." },
  champions: { name: "Champions Oncology", url: "https://www.championsoncology.com/", note: "Commercial bank of over 1,500 characterised PDX models (Lumin platform)." },
  jax: { name: "JAX PDX resource", url: "https://tumor.informatics.jax.org/mtbwi/pdxSearch.do", note: "Jackson Laboratory PDX collection with searchable genomics." },
  pdcm: { name: "PDCM Finder (cancermodels.org)", url: "https://www.cancermodels.org/", note: "EMBL-EBI and JAX meta-catalogue of PDX, organoid and cell-line models from dozens of providers." },
  hcmi: { name: "Human Cancer Models Initiative (HCMI)", url: "https://hcmi-searchable-catalog.nci.nih.gov/", note: "Next-generation organoid and conditionally reprogrammed models distributed through ATCC with matched sequencing." },
  hub: { name: "HUB Organoids", url: "https://www.huborganoids.nl/", note: "Hubrecht-founded biobank of patient-derived organoids across tumour types; academic and commercial access." },
  sanger: { name: "Sanger Cell Model Passports", url: "https://cellmodelpassports.sanger.ac.uk/", note: "Genomic and phenotypic passports for over 2,000 cell lines and organoids, including the Sanger organoid collection." },
  depmap: { name: "DepMap portal", url: "https://depmap.org/portal/", note: "Genome-wide CRISPR dependency and drug-sensitivity data on over 1,000 cell lines; the first place to check whether a target is essential in a lineage." },
  ccle: { name: "CCLE / DepMap omics", url: "https://depmap.org/portal/data_page/", note: "Expression, mutation, copy number and proteomics for the DepMap cell-line set." },
} satisfies Record<string, Repository>;

const STANDARD_PDX = [REPOS.pdmr, REPOS.pdcm, REPOS.champions];
const STANDARD_ORGANOIDS = [REPOS.hcmi, REPOS.hub, REPOS.sanger];

export const preclinicalModels: ModelEntry[] = [
  // ============================== Cancers ==============================
  {
    subject: "nsclc",
    cellLines: [
      { name: "A549", note: "KRAS G12S, STK11-null adenocarcinoma; the default lung line for everything and therefore representative of little.", targets: ["kras"] },
      { name: "NCI-H358", note: "KRAS G12C adenocarcinoma; the workhorse line for sotorasib and adagrasib pharmacology.", targets: ["kras"] },
      { name: "NCI-H23", note: "KRAS G12C, TP53 mutant.", targets: ["kras"] },
      { name: "NCI-H1975", note: "EGFR L858R plus T790M; the osimertinib development line.", targets: ["egfr"] },
      { name: "PC-9", note: "EGFR exon 19 deletion; used for every generation of EGFR TKI and for persister biology.", targets: ["egfr"] },
      { name: "HCC827", note: "EGFR exon 19 deletion with amplification; MET-amplified resistant derivatives exist.", targets: ["egfr", "met"] },
      { name: "NCI-H3122", note: "EML4-ALK variant 1 adenocarcinoma.", targets: ["alk"] },
      { name: "NCI-H2228", note: "EML4-ALK variant 3.", targets: ["alk"] },
      { name: "NCI-H460", note: "KRAS Q61H large-cell carcinoma.", targets: ["kras"] },
      { name: "Calu-3", note: "HER2-amplified adenocarcinoma.", targets: ["her2"] },
    ],
    pdx: [...STANDARD_PDX, REPOS.europdx],
    gemms: [
      { name: "Kras LSL-G12D (K)", alleles: "Kras G12D activated by inhaled Cre", note: "Adenomas progressing to adenocarcinoma; the base model for lung GEMMs.", source: doi("10.1101/gad.943001", "Jackson et al., Genes Dev 2001") },
      { name: "KP", alleles: "Kras G12D; Trp53 flox/flox", note: "Adds p53 loss for faster, metastatic adenocarcinoma.", source: doi("10.1038/nprot.2009.95", "DuPage et al., Nat Protoc 2009") },
      { name: "EGFR L858R / T790M (tet-inducible)", alleles: "CCSP-rtTA; TetO-EGFR L858R or L858R+T790M", note: "Doxycycline-inducible mutant EGFR; tumours regress when the transgene is switched off.", source: doi("10.1101/gad.1417406", "Politi et al., Genes Dev 2006") },
      { name: "Eml4-Alk (CRISPR)", alleles: "In vivo Cas9-induced Eml4-Alk inversion", note: "Endogenous fusion, crizotinib-sensitive tumours.", source: doi("10.1038/nature13902", "Maddalo et al., Nature 2014") },
    ],
    organoids: STANDARD_ORGANOIDS,
    caveats: ["Most immortalised lung lines are KRAS or EGFR driven; rarer drivers (RET, ROS1, MET exon 14) have one or two lines each and PDX models are the realistic option."],
  },
  {
    subject: "sclc",
    cellLines: [
      { name: "NCI-H69", note: "Classic (ASCL1-high) SCLC; grows as floating aggregates." },
      { name: "NCI-H82", note: "Variant (NEUROD1/MYC-driven) SCLC." },
      { name: "NCI-H146", note: "ASCL1 subtype, DLL3-expressing; used for tarlatamab and rovalpituzumab work.", targets: ["dll3"] },
      { name: "DMS 114", note: "Adherent SCLC line; SLFN11-expressing, used for TOP1 and PARP sensitivity." },
    ],
    pdx: [...STANDARD_PDX, REPOS.europdx],
    gemms: [
      { name: "RP", alleles: "Rb1 flox; Trp53 flox (Ad-Cre)", note: "The original SCLC GEMM; long latency (about 9 months).", source: doi("10.1016/S1535-6108(03)00220-4", "Meuwissen et al., Cancer Cell 2003") },
      { name: "RPM", alleles: "Rb1; Trp53; Myc T58A", note: "Fast, MYC-driven variant subtype; models NEUROD1 transition.", source: doi("10.1016/j.ccell.2016.12.005", "Mollaoglu et al., Cancer Cell 2017") },
    ],
    organoids: [REPOS.hcmi, REPOS.pdcm],
    caveats: ["Circulating tumour cell-derived explants (CDX) are a distinctive SCLC resource because biopsies are rarely large enough for PDX."],
  },
  {
    subject: "breast-hr-positive",
    cellLines: [
      { name: "MCF-7", note: "ER-positive luminal A, PIK3CA E545K; the reference line for endocrine therapy and CDK4/6 inhibitors.", targets: ["estrogen-receptor", "pik3ca", "cdk4-6"] },
      { name: "T-47D", note: "ER-positive, PIK3CA H1047R, progesterone-receptor high.", targets: ["estrogen-receptor", "pik3ca", "cdk4-6"] },
      { name: "ZR-75-1", note: "ER-positive luminal line with wild-type PIK3CA.", targets: ["estrogen-receptor"] },
      { name: "CAMA-1", note: "ER-positive with CDH1 loss (lobular-like).", targets: ["estrogen-receptor"] },
      { name: "MDA-MB-361", note: "ER-positive, HER2-amplified, PIK3CA E545K.", targets: ["estrogen-receptor", "her2", "pik3ca"] },
    ],
    pdx: [...STANDARD_PDX, REPOS.europdx],
    gemms: [
      { name: "MMTV-PyMT", alleles: "Polyoma middle T under the MMTV promoter", note: "Fast luminal-like tumours with lung metastases; ER expression is lost with progression.", source: pmid("1312220", "Guy et al., Mol Cell Biol 1992") },
    ],
    organoids: STANDARD_ORGANOIDS,
    caveats: ["ER-positive disease is under-represented in PDX banks because engraftment needs oestrogen supplementation and is slow; ESR1-mutant models are mostly CRISPR knock-ins into MCF-7 or long-term oestrogen-deprived (LTED) derivatives."],
  },
  {
    subject: "breast-her2-positive",
    cellLines: [
      { name: "SK-BR-3", note: "HER2-amplified, ER-negative; trastuzumab-sensitive.", targets: ["her2"] },
      { name: "BT-474", note: "HER2-amplified, ER-positive, PIK3CA K111N; the T-DM1 and T-DXd xenograft standard.", targets: ["her2"] },
      { name: "HCC1954", note: "HER2-amplified, PIK3CA H1047R; intrinsically trastuzumab-resistant.", targets: ["her2", "pik3ca"] },
      { name: "JIMT-1", note: "HER2-amplified, trastuzumab-resistant from the outset (PIK3CA H1047R, low PTEN).", targets: ["her2"] },
    ],
    pdx: STANDARD_PDX,
    gemms: [
      { name: "MMTV-Neu", alleles: "Rat Neu (Erbb2) under the MMTV promoter", note: "HER2-driven mammary tumours; used for anti-HER2 antibody and vaccine work.", source: doi("10.1073/pnas.89.22.10578", "Guy et al., PNAS 1992") },
    ],
    organoids: STANDARD_ORGANOIDS,
  },
  {
    subject: "tnbc",
    cellLines: [
      { name: "MDA-MB-231", note: "Mesenchymal-like TNBC, KRAS G13D, BRAF G464V; highly metastatic in mice.", targets: ["kras"] },
      { name: "MDA-MB-468", note: "Basal-like, EGFR-amplified, PTEN-null, TP53 R273H; TROP2-high.", targets: ["trop2", "tp53", "egfr"] },
      { name: "HCC1937", note: "BRCA1 5382insC germline line.", targets: ["brca"] },
      { name: "MDA-MB-436", note: "BRCA1-mutant; PARP-inhibitor sensitive.", targets: ["brca", "parp"] },
      { name: "SUM149PT", note: "BRCA1-mutant inflammatory breast cancer line.", targets: ["brca"] },
      { name: "HCC1806", note: "Basal-like, TROP2-high; used for sacituzumab govitecan.", targets: ["trop2"] },
      { name: "4T1", note: "Mouse (BALB/c) syngeneic TNBC-like line; spontaneous lung metastasis; the standard immunotherapy model for breast.", targets: ["pd1"] },
    ],
    pdx: [...STANDARD_PDX, REPOS.europdx],
    gemms: [
      { name: "Brca1 / Trp53 conditional", alleles: "K14-Cre; Brca1 flox; Trp53 flox", note: "Basal-like tumours mirroring BRCA1 carriers; PARP-inhibitor resistance models derive from it.", source: doi("10.1073/pnas.0702969104", "Liu et al., PNAS 2007") },
      { name: "C3(1)-Tag", alleles: "SV40 large T under the C3(1) promoter", note: "Basal-like mammary carcinoma.", source: MTB },
    ],
    organoids: STANDARD_ORGANOIDS,
  },
  {
    subject: "colorectal",
    cellLines: [
      { name: "HCT 116", note: "KRAS G13D, PIK3CA H1047R, MSI-high; the most used CRC line and the basis of many isogenic knock-out pairs (TP53, KRAS).", targets: ["kras", "pik3ca", "tp53"] },
      { name: "SW480", note: "KRAS G12V, TP53 R273H/P309S, APC-truncated; MSS.", targets: ["kras", "tp53"] },
      { name: "SW620", note: "Lymph-node metastasis from the same patient as SW480; matched primary-metastasis pair.", targets: ["kras"] },
      { name: "HT-29", note: "BRAF V600E, TP53 R273H, MSS.", targets: ["braf", "tp53"] },
      { name: "RKO", note: "BRAF V600E, MSI-high, CIMP-high.", targets: ["braf"] },
      { name: "DLD-1", note: "KRAS G13D, MSI-high; used for PARP and mismatch-repair work.", targets: ["kras"] },
      { name: "LoVo", note: "KRAS G13D, MSI-high.", targets: ["kras"] },
      { name: "LS180", note: "KRAS G12D, MSI-high.", targets: ["kras"] },
      { name: "MC38", note: "Mouse (C57BL/6) MSI-like, immunogenic colon line; the most used syngeneic checkpoint-inhibitor model.", targets: ["pd1", "pdl1"] },
      { name: "CT26", note: "Mouse (BALB/c) KRAS G12D colon line; MSS-like, moderately immunogenic.", targets: ["pd1", "kras"] },
    ],
    pdx: [...STANDARD_PDX, REPOS.europdx],
    gemms: [
      { name: "Apc Min", alleles: "Apc Min/+ (germline truncation)", note: "Dozens of small-intestinal adenomas; few progress to carcinoma and few are colonic.", source: doi("10.1126/science.2296722", "Moser et al., Science 1990") },
      { name: "Organoid-derived orthotopic (AKP)", alleles: "Apc; Kras G12D; Trp53 engineered organoids transplanted into the colon", note: "Invasive, metastatic colon cancer in weeks; combines GEMM genetics with organoid speed.", source: doi("10.1038/nbt.3837", "O'Rourke et al., Nat Biotechnol 2017") },
    ],
    organoids: [...STANDARD_ORGANOIDS, REPOS.pdmr],
    caveats: ["Most CRC lines are MSI-high, the opposite of the clinic (about 85% MSS); check MSI status before generalising."],
  },
  {
    subject: "pancreatic",
    cellLines: [
      { name: "PANC-1", note: "KRAS G12D, TP53 R273H, CDKN2A-null; quasi-mesenchymal.", targets: ["kras", "tp53"] },
      { name: "MIA PaCa-2", note: "KRAS G12C; one of the few G12C pancreatic lines.", targets: ["kras"] },
      { name: "AsPC-1", note: "KRAS G12D, ascites-derived; TROP2- and CLDN18.2-expressing.", targets: ["kras", "trop2"] },
      { name: "BxPC-3", note: "KRAS wild-type, TP53 Y220C; the control line for KRAS studies and the Y220C reactivator line.", targets: ["tp53"] },
      { name: "Capan-1", note: "KRAS G12V, BRCA2 6174delT; PARP-inhibitor model.", targets: ["kras", "brca"] },
      { name: "HPAF-II", note: "KRAS G12D, well differentiated, classical subtype.", targets: ["kras"] },
      { name: "KPC-derived lines", note: "Murine lines from the KPC GEMM (Kras G12D; Trp53 R172H) used for syngeneic immunotherapy studies.", targets: ["kras", "pd1"] },
    ],
    pdx: [...STANDARD_PDX, REPOS.europdx],
    gemms: [
      { name: "KPC", alleles: "Pdx1-Cre; Kras LSL-G12D; Trp53 LSL-R172H", note: "The reference PDAC model: stroma-rich, metastatic, immune-excluded; median survival about 5 months.", source: doi("10.1016/j.ccr.2005.04.023", "Hingorani et al., Cancer Cell 2005") },
      { name: "KC", alleles: "Pdx1-Cre; Kras LSL-G12D", note: "PanIN precursor lesions with slow progression; used for interception and prevention studies.", source: doi("10.1016/S1535-6108(03)00309-X", "Hingorani et al., Cancer Cell 2003") },
    ],
    organoids: [...STANDARD_ORGANOIDS, REPOS.pdmr],
    caveats: ["Organoids grow well from PDAC biopsies and fine-needle aspirates; the field has more organoid than cell-line diversity here."],
  },
  {
    subject: "prostate",
    cellLines: [
      { name: "LNCaP", note: "AR T878A, PTEN-null, PSMA-high; androgen-sensitive. The parent of C4-2 and C4-2B castration-resistant sublines.", targets: ["androgen-receptor", "psma", "akt"] },
      { name: "VCaP", note: "AR-amplified, TMPRSS2-ERG fusion, wild-type AR ligand-binding domain.", targets: ["androgen-receptor"] },
      { name: "22Rv1", note: "Expresses AR-V7 splice variant; enzalutamide-resistant; moderate PSMA.", targets: ["androgen-receptor", "psma"] },
      { name: "LAPC-4", note: "Wild-type AR, androgen-dependent.", targets: ["androgen-receptor"] },
      { name: "PC-3", note: "AR-negative, PSMA-negative, PTEN-null; used as the negative control and (engineered PC-3 PIP) as a PSMA-positive pair.", targets: ["psma"] },
      { name: "DU145", note: "AR-negative, brain-metastasis derived.", targets: [] },
      { name: "NCI-H660", note: "Neuroendocrine prostate cancer line; AR-negative, DLL3-positive.", targets: ["dll3"] },
    ],
    pdx: [...STANDARD_PDX, REPOS.europdx],
    gemms: [
      { name: "TRAMP", alleles: "Probasin-SV40 T antigen", note: "Aggressive, often neuroendocrine tumours; historic immunotherapy model.", source: doi("10.1073/pnas.92.8.3439", "Greenberg et al., PNAS 1995") },
      { name: "Pten conditional", alleles: "PB-Cre4; Pten flox/flox", note: "Invasive adenocarcinoma with slow progression; models the commonest human lesion.", source: doi("10.1016/S1535-6108(03)00215-0", "Wang et al., Cancer Cell 2003") },
      { name: "Pten / Trp53", alleles: "PB-Cre4; Pten flox; Trp53 flox", note: "Lethal, invasive disease with lineage plasticity under castration.", source: doi("10.1038/nature03918", "Chen et al., Nature 2005") },
    ],
    organoids: [REPOS.hcmi, REPOS.pdcm],
    caveats: ["Prostate cancer engrafts poorly; the LuCaP PDX series (University of Washington) and MDA PCa lines are the main patient-derived resource and are shared by request."],
  },
  {
    subject: "melanoma",
    cellLines: [
      { name: "A-375", note: "BRAF V600E; the standard vemurafenib and dabrafenib line.", targets: ["braf"] },
      { name: "SK-MEL-28", note: "BRAF V600E, CDK4 R24C.", targets: ["braf", "cdk4-6"] },
      { name: "WM-266-4", note: "BRAF V600D metastatic line.", targets: ["braf"] },
      { name: "SK-MEL-2", note: "NRAS Q61R; the MEK-inhibitor and NRAS control.", targets: [] },
      { name: "B16-F10", note: "Mouse (C57BL/6) poorly immunogenic melanoma; the classic checkpoint-resistant syngeneic model.", targets: ["pd1", "ctla4"] },
      { name: "YUMM1.7", note: "Mouse Braf V600E; Pten-/-; Cdkn2a-/- line derived from the GEMM, syngeneic in C57BL/6.", targets: ["braf", "pd1"] },
    ],
    pdx: [...STANDARD_PDX, REPOS.europdx],
    gemms: [
      { name: "Braf V600E / Pten", alleles: "Tyr-CreERT2; Braf CA; Pten flox", note: "Tamoxifen-inducible melanoma with metastasis; the reference model for BRAF/MEK inhibition and immunotherapy combinations.", source: doi("10.1038/ng.356", "Dankort et al., Nat Genet 2009") },
      { name: "YUMM lines", alleles: "Braf V600E; Pten-/-; Cdkn2a-/- (and variants)", note: "Genetically defined syngeneic lines; YUMMER1.7 is a UV-irradiated immunogenic derivative.", source: doi("10.1111/pcmr.12498", "Meeth et al., Pigment Cell Melanoma Res 2016") },
    ],
    organoids: [REPOS.hcmi, REPOS.pdcm],
  },
  {
    subject: "glioblastoma",
    cellLines: [
      { name: "U-87MG ATCC", note: "The most cited glioma line; of uncertain origin (not the original Uppsala U-87MG) and poorly representative of GBM.", targets: [] },
      { name: "U-251MG", note: "TP53 R273H, PTEN-null; invasive in orthotopic models.", targets: ["tp53"] },
      { name: "T98G", note: "Hyperpentaploid, temozolomide-resistant (MGMT-positive).", targets: [] },
      { name: "LN-229", note: "TP53-mutant, PTEN wild-type.", targets: [] },
      { name: "GL261", note: "Mouse (C57BL/6) syngeneic glioma; immunogenic, so it overstates immunotherapy effects.", targets: ["pd1"] },
      { name: "CT-2A", note: "Mouse syngeneic glioma with stem-like features; less immunogenic than GL261.", targets: ["pd1"] },
    ],
    pdx: [...STANDARD_PDX],
    gemms: [
      { name: "RCAS / tv-a", alleles: "Somatic delivery of PDGFB, Kras or other oncogenes to Nestin- or GFAP-expressing cells", note: "Flexible somatic model reproducing proneural and other subtypes.", source: doi("10.1038/75596", "Holland et al., Nat Genet 2000") },
    ],
    organoids: [REPOS.hcmi, REPOS.pdcm],
    caveats: ["Serum-grown glioma lines lose the GBM transcriptional programme; glioma stem-cell cultures (neurosphere or laminin-adherent) and the Mayo GBM PDX panel are the accepted standards.", "Paediatric diffuse midline glioma (H3 K27M) has its own culture collections (SU-DIPG series) not covered here."],
  },
  {
    subject: "ovarian",
    cellLines: [
      { name: "OVCAR-3", note: "High-grade serous, TP53 R248Q, CCNE1-amplified; platinum-resistant patient.", targets: ["tp53"] },
      { name: "OVCAR-8", note: "High-grade serous-like; used in NCI-60.", targets: [] },
      { name: "Kuramochi", note: "Ranked among the most HGSOC-like lines (TP53, BRCA2 mutant, KRAS amplification).", targets: ["brca", "tp53"] },
      { name: "COV362", note: "BRCA1-mutant high-grade serous line.", targets: ["brca", "parp"] },
      { name: "PEO1", note: "BRCA2-mutant; PEO4 from the same patient carries a BRCA2 reversion, an isogenic PARP-inhibitor resistance pair.", targets: ["brca", "parp"] },
      { name: "UWB1.289", note: "BRCA1-null line with a BRCA1-restored derivative.", targets: ["brca", "parp"] },
      { name: "SK-OV-3", note: "TP53-null, PIK3CA H1047R, HER2-expressing; widely used and not serous-like.", targets: ["pik3ca", "her2"] },
      { name: "ID8", note: "Mouse (C57BL/6) ovarian surface epithelial line; ID8 Trp53-/- Brca2-/- derivatives model HGSOC for immunotherapy.", targets: ["pd1", "brca"] },
    ],
    pdx: [...STANDARD_PDX, REPOS.europdx],
    gemms: [
      { name: "Fallopian-tube Trp53 / Brca1 / Pten", alleles: "Pax8-rtTA; TetO-Cre; Trp53; Brca1; Pten", note: "Serous tubal intraepithelial carcinoma progressing to HGSOC, supporting the fallopian-tube origin.", source: doi("10.1016/j.ccr.2013.10.013", "Perets et al., Cancer Cell 2013") },
      { name: "ID8 syngeneic", alleles: "Spontaneously transformed C57BL/6 ovarian surface epithelium", note: "Intraperitoneal disease with ascites; the standard immunotherapy model.", source: doi("10.1093/carcin/21.4.585", "Roby et al., Carcinogenesis 2000") },
    ],
    organoids: [...STANDARD_ORGANOIDS],
    caveats: ["Several historically popular lines (SK-OV-3, A2780) do not resemble high-grade serous cancer genomically; Domcke et al. (Nat Commun 2013) ranks lines by fidelity."],
  },
  {
    subject: "gastric",
    cellLines: [
      { name: "NCI-N87", note: "HER2-amplified gastric adenocarcinoma; the T-DXd and zanidatamab xenograft standard.", targets: ["her2"] },
      { name: "AGS", note: "KRAS G12D, PIK3CA E453K, CDH1-mutant; diffuse-like.", targets: ["kras", "pik3ca"] },
      { name: "SNU-16", note: "FGFR2-amplified; bemarituzumab model.", targets: ["fgfr2"] },
      { name: "KATO III", note: "FGFR2-amplified, CDH1-mutant signet-ring line.", targets: ["fgfr2"] },
      { name: "SNU-601", note: "CLDN18.2-expressing; used for zolbetuximab and CLDN18.2 ADCs.", targets: ["cldn18-2"] },
      { name: "MKN-45", note: "MET-amplified; capmatinib and MET ADC model.", targets: ["met"] },
    ],
    pdx: [...STANDARD_PDX, REPOS.europdx],
    gemms: [],
    organoids: [...STANDARD_ORGANOIDS],
    caveats: ["No widely adopted gastric adenocarcinoma GEMM; Helicobacter-infected INS-GAS mice model gastritis-to-cancer progression. Patient-derived organoid biobanks (Yan et al., Cell Stem Cell 2018) cover the molecular subtypes."],
  },
  {
    subject: "hcc",
    cellLines: [
      { name: "Hep-G2", note: "Hepatoblastoma-derived (not HCC) despite universal use; NRAS Q61L, wild-type TP53.", targets: [] },
      { name: "Huh-7", note: "TP53 Y220C HCC line; also the hepatitis C replicon host.", targets: ["tp53"] },
      { name: "Hep 3B", note: "HBV-integrated, TP53-null HCC.", targets: ["tp53"] },
      { name: "SNU-449", note: "Mesenchymal-like, GPC3-low HCC.", targets: [] },
      { name: "HepG2-GPC3 and JHH-7", note: "GPC3-high models used for GPC3 CAR-T and bispecifics.", targets: ["gpc3"] },
      { name: "Hepa 1-6", note: "Mouse (C57L) syngeneic hepatoma; orthotopic immunotherapy model.", targets: ["pd1"] },
    ],
    pdx: [...STANDARD_PDX],
    gemms: [
      { name: "Hydrodynamic transposon models", alleles: "Myc, Ctnnb1 or Akt transposons with or without sgTrp53 delivered by hydrodynamic tail-vein injection", note: "Weeks to tumours in immunocompetent mice; genotype chosen per experiment.", source: MTB },
    ],
    organoids: [REPOS.hcmi, REPOS.hub, REPOS.pdcm],
  },
  {
    subject: "aml",
    cellLines: [
      { name: "MOLM-13", note: "FLT3-ITD, MLL-AF9 (KMT2A::MLLT3); the standard FLT3 and menin inhibitor line.", targets: ["flt3", "kmt2a", "menin"] },
      { name: "MV4-11", note: "FLT3-ITD homozygous, MLL-AF4; highly FLT3-dependent.", targets: ["flt3", "kmt2a", "menin"] },
      { name: "OCI-AML3", note: "NPM1c, DNMT3A R882C; the NPM1-mutant menin inhibitor model.", targets: ["npm1", "menin"] },
      { name: "Kasumi-1", note: "RUNX1::RUNX1T1, KIT N822K; CD33-high.", targets: ["kit", "cd33"] },
      { name: "HL-60", note: "NRAS Q61L, CDKN2A-deleted promyelocytic line; TP53-null.", targets: [] },
      { name: "THP-1", note: "MLL-AF9 monocytic line; CD123-expressing.", targets: ["kmt2a", "cd123"] },
      { name: "Ba/F3", note: "Mouse pro-B line made IL-3 independent by any kinase driver; the universal engine for kinase and resistance mutation panels.", targets: ["flt3", "bcr-abl", "alk", "egfr", "kit"] },
    ],
    pdx: [REPOS.pdmr, REPOS.pdcm, { name: "PRoXe (Public Repository of Xenografts)", url: "https://www.proxe.org/", note: "Dana-Farber bank of leukaemia and lymphoma patient-derived xenografts." }],
    gemms: [
      { name: "MLL-AF9 retroviral", alleles: "Retroviral MLL-AF9 in haematopoietic progenitors transplanted into recipients", note: "Rapid, transplantable AML that defined leukaemia stem-cell biology.", source: doi("10.1038/nature04980", "Krivtsov et al., Nature 2006") },
      { name: "Flt3-ITD knock-in", alleles: "Flt3 ITD at the endogenous locus", note: "Myeloproliferative disease; co-operates with Npm1c or Dnmt3a loss to give AML.", source: doi("10.1016/j.ccr.2007.08.031", "Lee et al., Cancer Cell 2007") },
    ],
    organoids: [],
  },
  {
    subject: "cll",
    cellLines: [
      { name: "MEC-1", note: "CLL-derived line in prolymphocytoid transformation; TP53-mutant; the most used CLL line.", targets: ["btk"] },
      { name: "HG-3", note: "EBV-transformed CLL line with unmutated IGHV.", targets: [] },
      { name: "OSU-CLL", note: "EBV-transformed CLL line from Ohio State.", targets: ["btk"] },
    ],
    pdx: [REPOS.pdcm],
    gemms: [
      { name: "Eμ-TCL1", alleles: "Human TCL1 under the immunoglobulin heavy-chain enhancer", note: "CD5-positive B-cell leukaemia at about 12 months; transplantable; the model used for ibrutinib and venetoclax preclinical work.", source: doi("10.1073/pnas.102181599", "Bichi et al., PNAS 2002") },
    ],
    organoids: [],
    caveats: ["Primary CLL cells do not proliferate in culture without stromal or CD40L support; most mechanistic work uses primary samples and the Eμ-TCL1 mouse rather than lines."],
  },
  {
    subject: "dlbcl",
    cellLines: [
      { name: "SU-DHL-4", note: "GCB, BCL2-translocated; venetoclax and CD20 antibody model.", targets: ["bcl2", "cd20", "cd19"] },
      { name: "SU-DHL-6", note: "GCB, EZH2 Y641N; tazemetostat model.", targets: ["ezh2", "cd20"] },
      { name: "OCI-LY1", note: "GCB, BCL2-translocated, EZH2 Y641N.", targets: ["bcl2", "ezh2"] },
      { name: "OCI-LY3", note: "ABC, CARD11 and MYD88 L265P; NF-kB dependent.", targets: [] },
      { name: "OCI-LY10", note: "ABC, MYD88 L265P; ibrutinib-sensitive.", targets: ["btk"] },
      { name: "TMD8", note: "ABC, CD79B Y196 and MYD88 L265P; the reference BTK-inhibitor line.", targets: ["btk", "cd79b"] },
      { name: "HBL-1", note: "ABC, CD79B and MYD88 mutant.", targets: ["btk", "cd79b"] },
      { name: "Karpas-422", note: "GCB, EZH2 Y641N.", targets: ["ezh2"] },
      { name: "Raji", note: "Burkitt line used for CD19 and CD20 targeting; CD19 CAR-T standard.", targets: ["cd19", "cd20"] },
    ],
    pdx: [REPOS.pdcm, { name: "PRoXe (Public Repository of Xenografts)", url: "https://www.proxe.org/", note: "Dana-Farber bank of leukaemia and lymphoma patient-derived xenografts." }],
    gemms: [
      { name: "Eμ-Myc", alleles: "Myc under the immunoglobulin heavy-chain enhancer", note: "Pre-B and B-cell lymphoma; the classic apoptosis and BCL2-family model.", source: doi("10.1038/318533a0", "Adams et al., Nature 1985") },
    ],
    organoids: [],
  },
  {
    subject: "multiple-myeloma",
    cellLines: [
      { name: "MM.1S", note: "Dexamethasone-sensitive; BCMA-high; the standard CAR-T and bispecific line.", targets: ["bcma", "gprc5d", "cd38"] },
      { name: "NCI-H929", note: "t(4;14), NRAS G13D; BCMA and GPRC5D expressing.", targets: ["bcma", "gprc5d"] },
      { name: "RPMI 8226", note: "BCMA-positive; used for belantamab and proteasome-inhibitor resistance.", targets: ["bcma", "cd38"] },
      { name: "U266", note: "IL-6 autocrine line; BCMA-low relative to MM.1S.", targets: ["bcma"] },
      { name: "KMS-11", note: "t(4;14) FGFR3 Y373C; TP53-null.", targets: ["bcma"] },
      { name: "5TGM1", note: "Mouse (KaLwRij) myeloma; the syngeneic bone-disease model.", targets: [] },
    ],
    pdx: [REPOS.pdcm],
    gemms: [
      { name: "Vk*MYC", alleles: "Sporadic MYC activation in germinal-centre B cells", note: "Indolent monoclonal gammopathy progressing to myeloma in old mice; predicts single-agent clinical activity unusually well.", source: doi("10.1016/j.ccr.2008.01.007", "Chesi et al., Cancer Cell 2008") },
    ],
    organoids: [],
  },
  {
    subject: "all-leukemia",
    cellLines: [
      { name: "NALM-6", note: "Pre-B ALL, DUX4-rearranged; CD19- and CD22-positive; the CD19 CAR-T reference line.", targets: ["cd19", "cd22"] },
      { name: "REH", note: "ETV6::RUNX1 pre-B ALL.", targets: ["cd19"] },
      { name: "SEM", note: "KMT2A::AFF1 (MLL-AF4) infant ALL; menin inhibitor model.", targets: ["kmt2a", "menin", "cd19"] },
      { name: "RS4;11", note: "KMT2A::AFF1, BCL2-dependent.", targets: ["kmt2a", "bcl2", "cd19"] },
      { name: "SUP-B15", note: "BCR::ABL1 (p190) Ph-positive ALL.", targets: ["bcr-abl", "cd19"] },
      { name: "Jurkat", note: "T-ALL; the T-cell signalling workhorse and CD7-positive target line.", targets: ["cd7", "cd3"] },
    ],
    pdx: [REPOS.pdcm, { name: "PRoXe (Public Repository of Xenografts)", url: "https://www.proxe.org/", note: "Dana-Farber bank of leukaemia and lymphoma patient-derived xenografts." }],
    gemms: [],
    organoids: [],
    caveats: ["ALL engrafts efficiently in NSG mice, so patient-derived xenografts largely replaced GEMMs for drug testing."],
  },
  {
    subject: "urothelial",
    cellLines: [
      { name: "RT4", note: "FGFR3::TACC3 fusion, low grade; erdafitinib model.", targets: ["fgfr2"] },
      { name: "RT112", note: "FGFR3::TACC3, luminal papillary.", targets: ["fgfr2"] },
      { name: "UM-UC-3", note: "KRAS G12C, basal, Nectin-4 expressing.", targets: ["kras", "nectin4"] },
      { name: "T24", note: "HRAS G12V, TP53 mutant; basal-like.", targets: ["tp53"] },
      { name: "5637", note: "Basal/squamous-like, Nectin-4 high; enfortumab vedotin model.", targets: ["nectin4"] },
      { name: "MB49", note: "Mouse (C57BL/6) syngeneic bladder line; intravesical immunotherapy model.", targets: ["pd1"] },
    ],
    pdx: [...STANDARD_PDX],
    gemms: [
      { name: "BBN carcinogen model", alleles: "N-butyl-N-(4-hydroxybutyl)nitrosamine in drinking water", note: "Muscle-invasive, basal-like tumours with a human-like mutational spectrum after about 20 weeks.", source: MTB },
      { name: "Upk3a-CreERT2; Trp53; Pten", alleles: "Urothelium-specific Trp53 and Pten loss", note: "Invasive urothelial carcinoma.", source: doi("10.1101/gad.1772909", "Puzio-Kuter et al., Genes Dev 2009") },
    ],
    organoids: [REPOS.hcmi, REPOS.hub, REPOS.pdcm],
  },
  {
    subject: "rcc",
    cellLines: [
      { name: "786-O", note: "VHL-null, HIF-2alpha dependent clear-cell line; the belzutifan model.", targets: ["hif2a"] },
      { name: "A-498", note: "VHL-null, HIF-2alpha expressing.", targets: ["hif2a"] },
      { name: "Caki-1", note: "VHL wild-type clear-cell line (metastasis-derived).", targets: [] },
      { name: "RENCA", note: "Mouse (BALB/c) renal carcinoma; syngeneic immunotherapy model, not VHL-driven.", targets: ["pd1"] },
    ],
    pdx: [...STANDARD_PDX],
    gemms: [
      { name: "Vhl / Trp53 / Rb1", alleles: "Ksp1.3-CreERT2; Vhl; Trp53; Rb1 flox", note: "Clear-cell RCC arising from proximal tubule in mice, which single Vhl loss does not produce.", source: doi("10.1038/nm.4343", "Harlander et al., Nat Med 2017") },
    ],
    organoids: [REPOS.hcmi, REPOS.pdcm],
  },
  {
    subject: "head-and-neck",
    cellLines: [
      { name: "FaDu", note: "Hypopharyngeal SCC, HPV-negative, TP53 R248L; EGFR-high.", targets: ["egfr", "tp53"] },
      { name: "Detroit 562", note: "Pharyngeal SCC, HPV-negative.", targets: ["egfr"] },
      { name: "CAL 27", note: "Tongue SCC, HPV-negative, TP53 H193L.", targets: ["egfr", "tp53"] },
      { name: "UM-SCC-47", note: "HPV16-positive oral SCC.", targets: [] },
      { name: "MOC1", note: "Mouse (C57BL/6) carcinogen-induced oral SCC; immunogenic syngeneic model.", targets: ["pd1"] },
    ],
    pdx: [...STANDARD_PDX],
    gemms: [
      { name: "4-NQO carcinogen model", alleles: "4-nitroquinoline 1-oxide in drinking water", note: "Oral dysplasia to SCC over months with tobacco-like mutations.", source: MTB },
    ],
    organoids: [REPOS.hub, REPOS.hcmi],
  },
  {
    subject: "neuroblastoma",
    cellLines: [
      { name: "SH-SY5Y", note: "ALK F1174L, MYCN non-amplified subclone of SK-N-SH; GD2-positive.", targets: ["alk", "gd2"] },
      { name: "Kelly", note: "MYCN-amplified, ALK F1174L.", targets: ["alk", "gd2"] },
      { name: "IMR-32", note: "MYCN-amplified, ALK wild-type; GD2-high.", targets: ["gd2"] },
      { name: "NB-1", note: "ALK-amplified.", targets: ["alk"] },
      { name: "SK-N-AS", note: "MYCN non-amplified, NRAS Q61K.", targets: [] },
    ],
    pdx: [REPOS.pdmr, REPOS.pdcm, { name: "Childhood Solid Tumour Network (St. Jude)", url: "https://cstn.stjude.cloud/", note: "Free paediatric solid-tumour orthotopic PDX models with genomics." }],
    gemms: [
      { name: "TH-MYCN", alleles: "MYCN under the tyrosine hydroxylase promoter", note: "Sympathoadrenal tumours in weeks (homozygous); the standard neuroblastoma GEMM.", source: doi("10.1093/emboj/16.11.2985", "Weiss et al., EMBO J 1997") },
      { name: "TH-ALK F1174L; TH-MYCN", alleles: "Mutant ALK co-expressed with MYCN", note: "Accelerated, lethal disease showing ALK-MYCN co-operation.", source: doi("10.1016/j.ccr.2012.06.001", "Berry et al., Cancer Cell 2012") },
    ],
    organoids: [REPOS.pdcm],
  },
  {
    subject: "ewing-sarcoma",
    cellLines: [
      { name: "A-673", note: "EWSR1::FLI1 type 1, BRAF V600E (unusual), CDKN2A-null.", targets: ["ewsr1-fli1", "braf"] },
      { name: "TC-71", note: "EWSR1::FLI1 type 1, TP53 R213X.", targets: ["ewsr1-fli1", "tp53"] },
      { name: "SK-N-MC", note: "EWSR1::FLI1 (misclassified historically as neuroblastoma).", targets: ["ewsr1-fli1"] },
      { name: "EW8", note: "EWSR1::FLI1, used for IGF1R and PARP work.", targets: ["ewsr1-fli1"] },
    ],
    pdx: [REPOS.pdmr, REPOS.pdcm, { name: "Childhood Solid Tumour Network (St. Jude)", url: "https://cstn.stjude.cloud/", note: "Free paediatric solid-tumour orthotopic PDX models with genomics." }],
    gemms: [],
    organoids: [],
    caveats: ["No faithful GEMM exists: expressing EWSR1::FLI1 in mouse cells is toxic and the cell of origin is uncertain, which is one reason Ewing drug development leans on PDX and zebrafish models."],
  },
  {
    subject: "osteosarcoma",
    cellLines: [
      { name: "U2OS", note: "TP53 wild-type, RB1 wild-type, ATRX-null; more a cell-biology tool than a disease model.", targets: [] },
      { name: "Saos-2", note: "TP53-null, RB1-null; osteoblastic.", targets: ["tp53"] },
      { name: "MG-63", note: "TP53-null, CDKN2A-deleted.", targets: ["tp53"] },
      { name: "143B", note: "Highly metastatic KRAS-transformed derivative of HOS.", targets: ["kras"] },
      { name: "K7M2", note: "Mouse (BALB/c) metastatic osteosarcoma; syngeneic lung-metastasis model.", targets: [] },
    ],
    pdx: [REPOS.pdmr, REPOS.pdcm, { name: "Childhood Solid Tumour Network (St. Jude)", url: "https://cstn.stjude.cloud/", note: "Free paediatric solid-tumour orthotopic PDX models with genomics." }],
    gemms: [
      { name: "Osx-Cre; Trp53; Rb1", alleles: "Osteoblast-lineage deletion of Trp53 and Rb1", note: "Highly penetrant, metastatic osteosarcoma resembling the human disease.", source: doi("10.1101/gad.1656808", "Walkley et al., Genes Dev 2008") },
    ],
    organoids: [],
  },
  {
    subject: "mesothelioma",
    cellLines: [
      { name: "MSTO-211H", note: "Biphasic mesothelioma; CDKN2A-deleted.", targets: ["mesothelin"] },
      { name: "NCI-H2052", note: "Sarcomatoid-like, NF2-mutant.", targets: [] },
      { name: "NCI-H226", note: "Epithelioid, mesothelin-high; the mesothelin CAR-T and ADC standard.", targets: ["mesothelin"] },
      { name: "NCI-H28", note: "BAP1-mutant epithelioid line.", targets: [] },
      { name: "AB1 and AE17", note: "Mouse asbestos-induced syngeneic lines (BALB/c and C57BL/6).", targets: ["pd1"] },
    ],
    pdx: [...STANDARD_PDX],
    gemms: [
      { name: "Asbestos-exposed Nf2 / Cdkn2a", alleles: "Intraperitoneal asbestos in Nf2+/- and Cdkn2a-deficient mice", note: "Accelerated mesothelioma with human-like genetics.", source: doi("10.1016/j.ccr.2008.06.006", "Jongsma et al., Cancer Cell 2008") },
    ],
    organoids: [REPOS.pdcm],
  },
  {
    subject: "cholangiocarcinoma",
    cellLines: [
      { name: "HuCCT1", note: "Intrahepatic, KRAS G12D, TP53-mutant.", targets: ["kras", "tp53"] },
      { name: "RBE", note: "Intrahepatic with IDH1 R132S; the ivosidenib cholangiocarcinoma line.", targets: ["idh"] },
      { name: "ICC13-7 and CCLP-1", note: "FGFR2-fusion (ICC13-7) and FGFR2-dependent lines used for pemigatinib and futibatinib resistance studies.", targets: ["fgfr2"] },
      { name: "EGI-1", note: "Extrahepatic, KRAS G12D.", targets: ["kras"] },
    ],
    pdx: [...STANDARD_PDX],
    gemms: [
      { name: "Idh2 R172K; Kras G12D", alleles: "Albumin-Cre; Idh2 R172K; Kras LSL-G12D", note: "Mutant IDH blocks hepatocyte differentiation and co-operates with Kras to give intrahepatic cholangiocarcinoma.", source: doi("10.1038/nature13441", "Saha et al., Nature 2014") },
    ],
    organoids: [REPOS.hub, REPOS.hcmi, REPOS.pdcm],
  },
  {
    subject: "gist",
    cellLines: [
      { name: "GIST-T1", note: "KIT exon 11 deletion; imatinib-sensitive; the parent of several resistant derivatives.", targets: ["kit"] },
      { name: "GIST882", note: "KIT K642E (exon 13), imatinib-sensitive.", targets: ["kit"] },
      { name: "GIST430", note: "KIT exon 11 plus V654A secondary mutation; imatinib-resistant.", targets: ["kit"] },
      { name: "GIST48", note: "KIT exon 11 plus D820A secondary mutation; imatinib-resistant.", targets: ["kit"] },
    ],
    pdx: [REPOS.pdcm, REPOS.champions],
    gemms: [
      { name: "Kit V558del knock-in", alleles: "Kit exon 11 deletion at the endogenous locus", note: "Caecal GIST with interstitial-cell hyperplasia; imatinib-responsive.", source: MTB },
    ],
    organoids: [],
    caveats: ["GIST lines are rare and slow-growing; SDH-deficient and PDGFRA D842V GIST have almost no stable lines, so PDX and primary cultures are used."],
  },
  {
    subject: "endometrial",
    cellLines: [
      { name: "Ishikawa", note: "Endometrioid, ER-positive, PTEN-null, PIK3R1-mutant; the endocrine and PI3K model.", targets: ["estrogen-receptor", "akt"] },
      { name: "HEC-1-A", note: "Endometrioid, KRAS G12D, PIK3CA G1049R; MSI-high.", targets: ["kras", "pik3ca"] },
      { name: "AN3 CA", note: "FGFR2 N550K, PTEN-null; the FGFR2 endometrial line.", targets: ["fgfr2"] },
      { name: "KLE", note: "TP53-mutant, copy-number high (serous-like).", targets: ["tp53"] },
      { name: "ARK1", note: "Uterine serous carcinoma, HER2-amplified.", targets: ["her2", "tp53"] },
    ],
    pdx: [...STANDARD_PDX],
    gemms: [
      { name: "Pten conditional", alleles: "Progesterone-receptor-Cre; Pten flox", note: "Endometrial hyperplasia to carcinoma; models the commonest human lesion.", source: MTB },
    ],
    organoids: [REPOS.hub, REPOS.hcmi],
  },
  {
    subject: "cervical",
    cellLines: [
      { name: "HeLa", note: "HPV18 adenocarcinoma; the first human cell line and the most contaminating one.", targets: [] },
      { name: "SiHa", note: "HPV16 squamous carcinoma.", targets: [] },
      { name: "CaSki", note: "HPV16 (and HPV18 sequences) squamous line.", targets: [] },
      { name: "C-33 A", note: "HPV-negative cervical carcinoma with RB1 and TP53 mutations.", targets: ["tp53"] },
      { name: "TC-1", note: "Mouse (C57BL/6) HPV16 E6/E7-transformed lung epithelial line; the standard HPV therapeutic-vaccine model.", targets: ["pd1"] },
    ],
    pdx: [...STANDARD_PDX],
    gemms: [
      { name: "K14-HPV16 E6/E7", alleles: "HPV16 early genes under the keratin-14 promoter, oestrogen-treated", note: "Cervical intraepithelial neoplasia to invasive carcinoma.", source: MTB },
    ],
    organoids: [REPOS.hub],
  },
  {
    subject: "esophageal",
    cellLines: [
      { name: "OE33", note: "Oesophageal adenocarcinoma, HER2-amplified, TP53-mutant.", targets: ["her2", "tp53"] },
      { name: "OE19", note: "Junctional adenocarcinoma, HER2-amplified.", targets: ["her2"] },
      { name: "FLO-1", note: "Oesophageal adenocarcinoma, TP53-mutant, HER2-negative.", targets: ["tp53"] },
      { name: "KYSE-150", note: "Oesophageal squamous carcinoma; EGFR-expressing.", targets: ["egfr"] },
      { name: "KYSE-30", note: "Oesophageal squamous carcinoma, EGFR-amplified.", targets: ["egfr"] },
    ],
    pdx: [...STANDARD_PDX],
    gemms: [
      { name: "L2-IL1β", alleles: "Interleukin-1beta under the Epstein-Barr L2 promoter", note: "Barrett's-like metaplasia progressing to adenocarcinoma with bile acid; the main Barrett's GEMM.", source: doi("10.1016/j.ccr.2011.12.004", "Quante et al., Cancer Cell 2012") },
    ],
    organoids: [REPOS.hub, REPOS.hcmi],
  },
  {
    subject: "thyroid",
    cellLines: [
      { name: "TPC-1", note: "Papillary carcinoma with CCDC6::RET fusion; the RET inhibitor line.", targets: ["ret"] },
      { name: "BCPAP", note: "Papillary carcinoma, BRAF V600E, TP53-mutant.", targets: ["braf", "tp53"] },
      { name: "8505C", note: "Anaplastic carcinoma, BRAF V600E, TP53 R248G.", targets: ["braf", "tp53"] },
      { name: "TT", note: "Medullary carcinoma, RET C634W; the selpercatinib and vandetanib model.", targets: ["ret"] },
      { name: "MZ-CRC-1", note: "Medullary carcinoma, RET M918T.", targets: ["ret"] },
    ],
    pdx: [REPOS.pdmr, REPOS.pdcm],
    gemms: [
      { name: "TPO-Cre; Braf V600E", alleles: "Thyroid-specific Braf V600E", note: "Papillary carcinoma with loss of iodine uptake, restored by MAPK inhibition (the basis of redifferentiation trials).", source: MTB },
    ],
    organoids: [REPOS.pdcm],
    caveats: ["Many historic thyroid lines were shown to be redundant or misidentified (Schweppe et al., JCEM 2008); use authenticated stocks."],
  },
  {
    subject: "medulloblastoma",
    cellLines: [
      { name: "Daoy", note: "SHH-like, TP53-mutant; the most used medulloblastoma line but not group-representative.", targets: ["smoothened", "tp53"] },
      { name: "D283 Med", note: "Group 3/4-like, MYC-expressing.", targets: [] },
      { name: "D425 Med", note: "Group 3, MYC-amplified; aggressive orthotopic model.", targets: [] },
    ],
    pdx: [REPOS.pdmr, { name: "Childhood Solid Tumour Network (St. Jude)", url: "https://cstn.stjude.cloud/", note: "Free paediatric solid-tumour orthotopic PDX models with genomics." }, { name: "Brain Tumor Resource Lab (Olson)", url: "https://research.fredhutch.org/olson/en/btrl.html", note: "Fred Hutch collection of paediatric brain tumour PDX lines shared free of charge." }],
    gemms: [
      { name: "Ptch1 +/-", alleles: "Heterozygous Patched-1 loss", note: "SHH-subgroup medulloblastoma in about 15% of mice; the founding SHH model.", source: doi("10.1126/science.277.5329.1109", "Goodrich et al., Science 1997") },
      { name: "Math1-Cre; SmoM2", alleles: "Constitutively active Smoothened in granule-neuron precursors", note: "Fully penetrant SHH medulloblastoma; used for vismodegib resistance.", source: MTB },
    ],
    organoids: [],
  },

  // ============================== Targets ==============================
  {
    subject: "kras",
    cellLines: [
      { name: "NCI-H358", note: "Lung, G12C; the sotorasib and adagrasib reference line.", targets: ["kras"] },
      { name: "MIA PaCa-2", note: "Pancreatic, G12C.", targets: ["kras"] },
      { name: "NCI-H23", note: "Lung, G12C.", targets: ["kras"] },
      { name: "SW1573", note: "Lung, G12C.", targets: ["kras"] },
      { name: "Calu-1", note: "Lung, G12C.", targets: ["kras"] },
      { name: "AsPC-1", note: "Pancreatic, G12D.", targets: ["kras"] },
      { name: "PANC-1", note: "Pancreatic, G12D.", targets: ["kras"] },
      { name: "HPAF-II", note: "Pancreatic, G12D.", targets: ["kras"] },
      { name: "LS180", note: "Colorectal, G12D.", targets: ["kras"] },
      { name: "SW480", note: "Colorectal, G12V.", targets: ["kras"] },
      { name: "Capan-1", note: "Pancreatic, G12V.", targets: ["kras"] },
      { name: "HCT 116", note: "Colorectal, G13D.", targets: ["kras"] },
      { name: "NCI-H460", note: "Lung, Q61H.", targets: ["kras"] },
      { name: "A549", note: "Lung, G12S.", targets: ["kras"] },
      { name: "CT26", note: "Mouse colon, G12D; syngeneic.", targets: ["kras"] },
    ],
    pdx: [REPOS.pdmr, REPOS.pdcm, REPOS.champions],
    gemms: [
      { name: "Kras LSL-G12D", alleles: "Conditional G12D allele used across lung, pancreas and colon models", note: "The founding conditional Kras allele.", source: doi("10.1101/gad.943001", "Jackson et al., Genes Dev 2001") },
      { name: "Kras LSL-G12C", alleles: "Conditional G12C allele", note: "Lung tumours that respond to covalent G12C inhibitors, enabling immunocompetent combination studies.", source: doi("10.1038/s41586-019-1694-1", "Canon et al., Nature 2019") },
    ],
    organoids: [REPOS.hcmi, REPOS.hub],
    caveats: ["Allele matters: G12C lines respond to covalent inhibitors, G12D lines do not; check the allele in DepMap or Cellosaurus before choosing."],
  },
  {
    subject: "egfr",
    cellLines: [
      { name: "PC-9", note: "Exon 19 deletion; persister and resistance derivatives (PC-9/ER, PC-9/OR) are widely shared.", targets: ["egfr"] },
      { name: "HCC827", note: "Exon 19 deletion, amplified; MET-amplified resistant sublines (HCC827 GR).", targets: ["egfr", "met"] },
      { name: "NCI-H1975", note: "L858R plus T790M; osimertinib-sensitive, first-generation-resistant.", targets: ["egfr"] },
      { name: "NCI-H3255", note: "L858R with amplification.", targets: ["egfr"] },
      { name: "HCC4006", note: "Exon 19 deletion; EMT-type resistance models.", targets: ["egfr"] },
      { name: "NCI-H1650", note: "Exon 19 deletion with PTEN loss; intrinsically TKI-resistant.", targets: ["egfr"] },
      { name: "A-431", note: "Vulval squamous line with massive EGFR amplification; the antibody and ADC binding standard.", targets: ["egfr"] },
      { name: "Ba/F3 EGFR panels", note: "Engineered exon 20 insertion, C797S and other alleles in the IL-3-dependent Ba/F3 background.", targets: ["egfr"] },
    ],
    pdx: [REPOS.pdmr, REPOS.pdcm, REPOS.champions],
    gemms: [
      { name: "EGFR L858R / T790M (tet-inducible)", alleles: "CCSP-rtTA; TetO-EGFR", note: "Inducible mutant EGFR lung tumours.", source: doi("10.1101/gad.1417406", "Politi et al., Genes Dev 2006") },
    ],
    organoids: [REPOS.hcmi],
  },
  {
    subject: "her2",
    cellLines: [
      { name: "SK-BR-3", note: "Breast, HER2-amplified.", targets: ["her2"] },
      { name: "BT-474", note: "Breast, HER2-amplified, ER-positive; ADC xenograft standard.", targets: ["her2"] },
      { name: "HCC1954", note: "Breast, HER2-amplified, trastuzumab-resistant.", targets: ["her2"] },
      { name: "NCI-N87", note: "Gastric, HER2-amplified.", targets: ["her2"] },
      { name: "OE19", note: "Oesophagogastric junction, HER2-amplified.", targets: ["her2"] },
      { name: "MDA-MB-453", note: "Breast, HER2-low (IHC 1+ to 2+); used for HER2-low ADC bystander studies.", targets: ["her2"] },
      { name: "MCF-7", note: "HER2-low breast line used as the HER2-low or negative comparator.", targets: ["her2"] },
      { name: "Ba/F3 ERBB2 exon 20", note: "Engineered YVMA insertion lines for zongertinib- and sevabertinib-type TKIs.", targets: ["her2"] },
    ],
    pdx: [REPOS.pdmr, REPOS.pdcm, REPOS.champions],
    gemms: [
      { name: "MMTV-Neu", alleles: "Rat Neu under the MMTV promoter", note: "HER2-driven mammary tumours.", source: doi("10.1073/pnas.89.22.10578", "Guy et al., PNAS 1992") },
    ],
    organoids: [REPOS.hcmi, REPOS.hub],
  },
  {
    subject: "braf",
    cellLines: [
      { name: "A-375", note: "Melanoma, V600E.", targets: ["braf"] },
      { name: "SK-MEL-28", note: "Melanoma, V600E.", targets: ["braf"] },
      { name: "HT-29", note: "Colorectal, V600E; the model for EGFR co-blockade.", targets: ["braf"] },
      { name: "RKO", note: "Colorectal, V600E, MSI-high.", targets: ["braf"] },
      { name: "COLO 205", note: "Colorectal, V600E.", targets: ["braf"] },
      { name: "WM-266-4", note: "Melanoma, V600D.", targets: ["braf"] },
      { name: "8505C", note: "Anaplastic thyroid, V600E.", targets: ["braf"] },
      { name: "MDA-MB-231", note: "Breast, G464V (class III).", targets: ["braf"] },
    ],
    pdx: [REPOS.pdmr, REPOS.pdcm, REPOS.champions],
    gemms: [
      { name: "Braf CA (V600E) conditional", alleles: "Cre-activated Braf V600E used in melanoma, lung, thyroid and colon models", note: "The shared conditional allele.", source: doi("10.1038/ng.356", "Dankort et al., Nat Genet 2009") },
    ],
    organoids: [REPOS.hcmi, REPOS.hub],
  },
  {
    subject: "alk",
    cellLines: [
      { name: "NCI-H3122", note: "Lung, EML4::ALK variant 1.", targets: ["alk"] },
      { name: "NCI-H2228", note: "Lung, EML4::ALK variant 3.", targets: ["alk"] },
      { name: "Karpas-299", note: "Anaplastic large-cell lymphoma, NPM1::ALK.", targets: ["alk", "cd30"] },
      { name: "SU-DHL-1", note: "Anaplastic large-cell lymphoma, NPM1::ALK.", targets: ["alk", "cd30"] },
      { name: "Kelly", note: "Neuroblastoma, ALK F1174L.", targets: ["alk"] },
      { name: "SH-SY5Y", note: "Neuroblastoma, ALK F1174L.", targets: ["alk"] },
      { name: "NB-1", note: "Neuroblastoma, ALK-amplified.", targets: ["alk"] },
      { name: "Ba/F3 EML4-ALK mutants", note: "G1202R, L1196M, compound mutations; the lorlatinib and neladalkib profiling panel.", targets: ["alk"] },
    ],
    pdx: [REPOS.pdmr, REPOS.pdcm],
    gemms: [
      { name: "Eml4-Alk (CRISPR)", alleles: "Somatic Cas9-induced inversion", note: "Endogenous fusion lung tumours.", source: doi("10.1038/nature13902", "Maddalo et al., Nature 2014") },
    ],
    organoids: [REPOS.hcmi],
  },
  {
    subject: "estrogen-receptor",
    cellLines: [
      { name: "MCF-7", note: "ER-positive; CRISPR knock-in Y537S and D538G derivatives model ESR1-mutant disease.", targets: ["estrogen-receptor"] },
      { name: "T-47D", note: "ER-positive, PR-high.", targets: ["estrogen-receptor"] },
      { name: "ZR-75-1", note: "ER-positive.", targets: ["estrogen-receptor"] },
      { name: "CAMA-1", note: "ER-positive, CDH1-null.", targets: ["estrogen-receptor"] },
      { name: "MDA-MB-134-VI", note: "ER-positive lobular carcinoma line.", targets: ["estrogen-receptor"] },
      { name: "Ishikawa", note: "ER-positive endometrial line.", targets: ["estrogen-receptor"] },
    ],
    pdx: [REPOS.pdmr, REPOS.pdcm, REPOS.champions],
    gemms: [],
    organoids: [REPOS.hcmi, REPOS.hub],
    caveats: ["No spontaneous GEMM is ER-dependent in the way human luminal breast cancer is; oestrogen-supplemented PDX (e.g. the Washington University WHIM series) are the closest models."],
  },
  {
    subject: "tp53",
    cellLines: [
      { name: "HCT 116", note: "Wild-type parent with isogenic TP53-/- derivative (Vogelstein laboratory).", targets: ["tp53"] },
      { name: "NCI-H1299", note: "TP53-null lung line used to re-express mutant alleles.", targets: ["tp53"] },
      { name: "Saos-2", note: "TP53-null osteosarcoma; classic reconstitution host.", targets: ["tp53"] },
      { name: "MDA-MB-468", note: "R273H.", targets: ["tp53"] },
      { name: "SK-BR-3", note: "R175H.", targets: ["tp53"] },
      { name: "Huh-7", note: "Y220C; the reactivator line.", targets: ["tp53"] },
      { name: "BxPC-3", note: "Y220C.", targets: ["tp53"] },
      { name: "NUGC-3", note: "Y220C gastric line.", targets: ["tp53"] },
      { name: "MCF-7", note: "Wild-type TP53; MDM2-inhibitor sensitive control.", targets: ["tp53", "mdm2"] },
      { name: "SJSA-1", note: "MDM2-amplified osteosarcoma; the MDM2-inhibitor standard.", targets: ["mdm2", "tp53"] },
    ],
    pdx: [REPOS.pdmr, REPOS.pdcm],
    gemms: [
      { name: "Trp53 R172H and R270H knock-ins", alleles: "Murine equivalents of human R175H and R273H", note: "Gain-of-function alleles with a metastatic phenotype beyond simple loss.", source: doi("10.1016/j.cell.2004.11.004", "Olive et al., Cell 2004") },
    ],
    organoids: [REPOS.hcmi],
  },
  {
    subject: "brca",
    cellLines: [
      { name: "MDA-MB-436", note: "Breast, BRCA1 5396+1G>A; PARP-inhibitor sensitive.", targets: ["brca", "parp"] },
      { name: "HCC1937", note: "Breast, BRCA1 5382insC; relatively PARP-inhibitor resistant despite BRCA1 loss.", targets: ["brca", "parp"] },
      { name: "SUM149PT", note: "Breast, BRCA1 2288delT.", targets: ["brca", "parp"] },
      { name: "Capan-1", note: "Pancreatic, BRCA2 6174delT; olaparib-resistant derivatives carry reversions.", targets: ["brca", "parp"] },
      { name: "PEO1", note: "Ovarian, BRCA2 5193C>G; PEO4 sister line has a reversion.", targets: ["brca", "parp"] },
      { name: "UWB1.289", note: "Ovarian, BRCA1-null; BRCA1-restored isogenic pair available.", targets: ["brca", "parp"] },
      { name: "COV362", note: "Ovarian, BRCA1-mutant.", targets: ["brca", "parp"] },
      { name: "DLD-1 BRCA2-/-", note: "Isogenic colorectal knock-out pair (Horizon).", targets: ["brca", "parp"] },
    ],
    pdx: [REPOS.pdmr, REPOS.pdcm, REPOS.champions],
    gemms: [
      { name: "K14-Cre; Brca1; Trp53", alleles: "Mammary Brca1 and Trp53 loss", note: "Basal-like tumours; the source of PARP-inhibitor resistance mechanisms (53BP1 loss, drug efflux).", source: doi("10.1073/pnas.0702969104", "Liu et al., PNAS 2007") },
    ],
    organoids: [REPOS.hcmi, REPOS.hub],
  },
  {
    subject: "idh",
    cellLines: [
      { name: "HT-1080", note: "Fibrosarcoma, IDH1 R132C; the most used endogenous mutant-IDH1 line.", targets: ["idh"] },
      { name: "BT142", note: "Glioma, IDH1 R132H (hemizygous); one of few IDH-mutant glioma lines that grows.", targets: ["idh"] },
      { name: "TS603", note: "Glioma, IDH1 R132H neurosphere culture.", targets: ["idh"] },
      { name: "SW1353", note: "Chondrosarcoma, IDH2 R172S.", targets: ["idh"] },
      { name: "RBE", note: "Cholangiocarcinoma, IDH1 R132S.", targets: ["idh"] },
      { name: "SNU-1079", note: "Cholangiocarcinoma, IDH1 R132C.", targets: ["idh"] },
    ],
    pdx: [REPOS.pdmr, REPOS.pdcm],
    gemms: [
      { name: "Idh2 R172K; Kras G12D liver", alleles: "Albumin-Cre driven", note: "Intrahepatic cholangiocarcinoma.", source: doi("10.1038/nature13441", "Saha et al., Nature 2014") },
    ],
    organoids: [REPOS.hcmi],
    caveats: ["IDH-mutant gliomas are notoriously hard to culture and lose the mutation or growth in vitro; most work uses engineered lines or slow-growing PDX (e.g. the Mayo GBM panel)."],
  },
  {
    subject: "kit",
    cellLines: [
      { name: "GIST-T1", note: "Exon 11 deletion.", targets: ["kit"] },
      { name: "GIST882", note: "K642E.", targets: ["kit"] },
      { name: "GIST430", note: "Exon 11 plus V654A.", targets: ["kit"] },
      { name: "GIST48", note: "Exon 11 plus D820A.", targets: ["kit"] },
      { name: "HMC-1", note: "Mast-cell leukaemia, D816V (HMC-1.2) and V560G; the mastocytosis line.", targets: ["kit"] },
      { name: "Kasumi-1", note: "AML, N822K.", targets: ["kit"] },
    ],
    pdx: [REPOS.pdcm, REPOS.champions],
    gemms: [
      { name: "Kit V558del knock-in", alleles: "Endogenous exon 11 deletion", note: "Imatinib-responsive GIST.", source: MTB },
    ],
    organoids: [],
  },
  {
    subject: "flt3",
    cellLines: [
      { name: "MOLM-13", note: "ITD heterozygous.", targets: ["flt3"] },
      { name: "MV4-11", note: "ITD homozygous.", targets: ["flt3"] },
      { name: "MOLM-14", note: "ITD; sister line of MOLM-13.", targets: ["flt3"] },
      { name: "Ba/F3 FLT3-ITD and D835Y", note: "Engineered alleles including F691L gatekeeper.", targets: ["flt3"] },
    ],
    pdx: [REPOS.pdcm, { name: "PRoXe (Public Repository of Xenografts)", url: "https://www.proxe.org/", note: "Dana-Farber bank of leukaemia and lymphoma patient-derived xenografts." }],
    gemms: [
      { name: "Flt3-ITD knock-in", alleles: "Endogenous ITD", note: "Myeloproliferative disease; AML with a second hit.", source: doi("10.1016/j.ccr.2007.08.031", "Lee et al., Cancer Cell 2007") },
    ],
    organoids: [],
  },
  {
    subject: "bcr-abl",
    cellLines: [
      { name: "K-562", note: "CML blast crisis, BCR::ABL1 (b3a2); the original imatinib line and the CAR-T negative-control target.", targets: ["bcr-abl"] },
      { name: "KU812", note: "CML basophilic line, BCR::ABL1.", targets: ["bcr-abl"] },
      { name: "KCL-22", note: "CML line that acquires T315I under imatinib in culture.", targets: ["bcr-abl"] },
      { name: "SUP-B15", note: "Ph-positive ALL, p190.", targets: ["bcr-abl"] },
      { name: "Ba/F3 BCR-ABL1 mutants", note: "T315I, E255K, Y253H and myristoyl-pocket panels.", targets: ["bcr-abl"] },
    ],
    pdx: [REPOS.pdcm],
    gemms: [
      { name: "Retroviral BCR-ABL bone-marrow transplant", alleles: "p210 BCR-ABL1 in transplanted marrow", note: "CML-like myeloproliferation in weeks; the standard for kinase-inhibitor and stem-cell studies.", source: MTB },
    ],
    organoids: [],
  },
  {
    subject: "btk",
    cellLines: [
      { name: "TMD8", note: "ABC-DLBCL, CD79B mutant; ibrutinib-sensitive with C481S resistant derivatives.", targets: ["btk"] },
      { name: "HBL-1", note: "ABC-DLBCL.", targets: ["btk"] },
      { name: "OCI-LY10", note: "ABC-DLBCL, MYD88 L265P.", targets: ["btk"] },
      { name: "REC-1", note: "Mantle-cell lymphoma, ibrutinib-sensitive.", targets: ["btk"] },
      { name: "MEC-1", note: "CLL-derived line.", targets: ["btk"] },
    ],
    pdx: [REPOS.pdcm],
    gemms: [
      { name: "Eμ-TCL1", alleles: "TCL1 transgene", note: "CLL model used for BTK-inhibitor pharmacology.", source: doi("10.1073/pnas.102181599", "Bichi et al., PNAS 2002") },
    ],
    organoids: [],
  },
  {
    subject: "androgen-receptor",
    cellLines: [
      { name: "LNCaP", note: "T878A; androgen-sensitive.", targets: ["androgen-receptor"] },
      { name: "VCaP", note: "AR-amplified, wild-type LBD.", targets: ["androgen-receptor"] },
      { name: "22Rv1", note: "AR-V7 expressing.", targets: ["androgen-receptor"] },
      { name: "LAPC-4", note: "Wild-type AR.", targets: ["androgen-receptor"] },
      { name: "MDA PCa 2b", note: "T878A and L702H double mutant.", targets: ["androgen-receptor"] },
      { name: "C4-2B", note: "Castration-resistant LNCaP derivative, bone-metastatic.", targets: ["androgen-receptor"] },
    ],
    pdx: [REPOS.pdmr, REPOS.pdcm, { name: "LuCaP PDX series (University of Washington)", url: "https://www.uwmedicine.org/", note: "The largest prostate PDX collection, including AR-V7-high and neuroendocrine lines, shared by material transfer agreement." }],
    gemms: [
      { name: "Pten conditional", alleles: "PB-Cre4; Pten flox", note: "AR-dependent adenocarcinoma responsive to castration.", source: doi("10.1016/S1535-6108(03)00215-0", "Wang et al., Cancer Cell 2003") },
    ],
    organoids: [REPOS.hcmi, REPOS.pdcm],
  },
  {
    subject: "psma",
    cellLines: [
      { name: "LNCaP", note: "PSMA-high; the radioligand binding and dosimetry standard.", targets: ["psma"] },
      { name: "C4-2", note: "PSMA-high, castration-resistant.", targets: ["psma"] },
      { name: "22Rv1", note: "Moderate PSMA.", targets: ["psma"] },
      { name: "PC-3", note: "PSMA-negative control; PC-3 PIP (PSMA-transduced) and PC-3 flu form the classic matched pair.", targets: ["psma"] },
      { name: "DU145", note: "PSMA-negative.", targets: ["psma"] },
    ],
    pdx: [REPOS.pdcm],
    gemms: [],
    organoids: [],
    caveats: ["Mouse PSMA (Folh1) differs in expression pattern (kidney, not prostate), so off-target dosimetry in mice does not predict human salivary or renal uptake."],
  },
  {
    subject: "trop2",
    cellLines: [
      { name: "MDA-MB-468", note: "TROP2-high TNBC.", targets: ["trop2"] },
      { name: "HCC1806", note: "TROP2-high TNBC.", targets: ["trop2"] },
      { name: "BxPC-3", note: "TROP2-high pancreatic.", targets: ["trop2"] },
      { name: "NCI-H1975", note: "TROP2-positive lung; Dato-DXd model.", targets: ["trop2"] },
      { name: "Calu-3", note: "TROP2-positive lung.", targets: ["trop2"] },
      { name: "MDA-MB-231", note: "TROP2-low comparator.", targets: ["trop2"] },
    ],
    pdx: [REPOS.pdmr, REPOS.pdcm, REPOS.champions],
    gemms: [],
    organoids: [REPOS.hcmi],
  },
  {
    subject: "cd19",
    cellLines: [
      { name: "NALM-6", note: "Pre-B ALL; CAR-T potency standard.", targets: ["cd19"] },
      { name: "Raji", note: "Burkitt; CD19 and CD20.", targets: ["cd19", "cd20"] },
      { name: "Daudi", note: "Burkitt; beta-2-microglobulin null (no HLA class I), useful for MHC-independent killing.", targets: ["cd19", "cd20"] },
      { name: "REH", note: "Pre-B ALL.", targets: ["cd19"] },
      { name: "JeKo-1", note: "Mantle-cell lymphoma.", targets: ["cd19", "cd20", "btk"] },
      { name: "K-562 CD19", note: "CD19-transduced K-562 as an artificial target with CD19-negative parent as control.", targets: ["cd19"] },
    ],
    pdx: [REPOS.pdcm, { name: "PRoXe (Public Repository of Xenografts)", url: "https://www.proxe.org/", note: "Dana-Farber bank of leukaemia and lymphoma patient-derived xenografts." }],
    gemms: [
      { name: "Eμ-Myc", alleles: "Myc transgene", note: "Syngeneic B-cell lymphoma for murine CD19 CAR-T studies.", source: doi("10.1038/318533a0", "Adams et al., Nature 1985") },
    ],
    organoids: [],
  },
  {
    subject: "bcma",
    cellLines: [
      { name: "MM.1S", note: "BCMA-high; luciferase derivatives for in vivo CAR-T imaging.", targets: ["bcma"] },
      { name: "NCI-H929", note: "BCMA-positive.", targets: ["bcma"] },
      { name: "RPMI 8226", note: "BCMA-positive.", targets: ["bcma"] },
      { name: "U266", note: "BCMA-lower comparator.", targets: ["bcma"] },
      { name: "KMS-11", note: "BCMA-positive; BCMA knock-out derivatives model antigen loss.", targets: ["bcma"] },
    ],
    pdx: [REPOS.pdcm],
    gemms: [
      { name: "Vk*MYC", alleles: "Sporadic MYC in germinal-centre B cells", note: "Immunocompetent myeloma model with murine Bcma.", source: doi("10.1016/j.ccr.2008.01.007", "Chesi et al., Cancer Cell 2008") },
    ],
    organoids: [],
  },
  {
    subject: "pd1",
    cellLines: [
      { name: "MC38", note: "Mouse colon; PD-1 responsive.", targets: ["pd1", "pdl1"] },
      { name: "CT26", note: "Mouse colon; partially responsive.", targets: ["pd1"] },
      { name: "B16-F10", note: "Mouse melanoma; PD-1 refractory unless combined.", targets: ["pd1", "ctla4"] },
      { name: "4T1", note: "Mouse breast; refractory, metastatic.", targets: ["pd1"] },
      { name: "LL/2", note: "Lewis lung carcinoma; refractory.", targets: ["pd1"] },
      { name: "EMT6", note: "Mouse breast; responsive.", targets: ["pd1"] },
      { name: "YUMMER1.7", note: "UV-mutagenised Braf/Pten melanoma; responsive.", targets: ["pd1", "braf"] },
      { name: "KPC-derived lines", note: "Pancreatic; immune-excluded and refractory.", targets: ["pd1", "kras"] },
    ],
    pdx: [{ name: "Humanised-mouse PDX (CD34+ or PBMC engrafted)", url: "https://www.jax.org/jax-mice-and-services/in-vivo-pharmacology/oncology-services/pdx-tumors", note: "Human immune system mice bearing PDX, the only patient-derived setting for human checkpoint antibodies." }],
    gemms: [
      { name: "KP lung and KPC pancreas", alleles: "Kras G12D; Trp53", note: "Low mutation burden and immune-cold; used to model checkpoint resistance rather than response.", source: doi("10.1038/nprot.2009.95", "DuPage et al., Nat Protoc 2009") },
    ],
    organoids: [{ name: "Tumour-organoid and autologous T-cell co-cultures", url: "https://www.huborganoids.nl/", note: "Patient organoids co-cultured with peripheral blood T cells to test checkpoint blockade per patient (Dijkstra et al., Cell 2018)." }],
    caveats: ["Syngeneic lines are the only immunocompetent option for human checkpoint biology but carry far higher mutation burden than most human tumours, and the human antibodies do not bind mouse PD-1, so surrogate antibodies are used."],
  },
];

/** Resolved identifiers for a cell line by Cellosaurus spelling; undefined when the name was not resolved. */
export function cellLineIds(name: string): CellLineIds | undefined {
  return CELL_LINE_IDS[name];
}

/** Every distinct cell-line name in the registry (used by the fetch script and the page). */
export function allCellLineNames(): string[] {
  return [...new Set(preclinicalModels.flatMap((m) => m.cellLines.map((c) => c.name)))].sort();
}

export const modelsFor = (subject: string): ModelEntry | undefined => preclinicalModels.find((m) => m.subject === subject);
