/**
 * GENERATED by scripts/fetch-cancer-genes.ts on 2026-09-23; do not edit by hand, re-run the script (see its header for the
 * sources, licences and rules). 0 genes and proteins the open catalogues tie to cancer that had no target page:
 * CIViC (CC0), Open Targets (CC0; cancer MONDO_0004992 association at or above 0.5, per-cancer at or above 0.5),
 * IntOGen driver catalogue release 20240920 (CC0 1.0), identifiers from HGNC, function text from UniProt (CC BY 4.0).
 * Ordered by evidence tier, strongest first: approved-drug 0, clinical-evidence 0, cohort-driver 0, association-only 0.
 * Every record names its sources in `sources`; cancers are linked only through the id map in the script; unmapped disease
 * names stay in `notes`. `cancerGeneIdsBySource` lets the CIViC, Open Targets and IntOGen collection records list them.
 */
import type { TargetInput } from "@/lib/schema";

export const TARGETS_GENES_WAVE_GENERATED = "2026-09-23";

/** Types each record on its own so the compiler never has to form a union over every object literal in the array. */
const t = (x: TargetInput): TargetInput => x;

export const targetsGenesWave: TargetInput[] = [

];

/** Record ids by the catalogue that lists the gene, for the collection records in src/data/collections.ts. */
export const cancerGeneIdsBySource: Record<"civic" | "open-targets" | "intogen", string[]> = {"civic":[],"open-targets":[],"intogen":[]};
