/**
 * GENERATED by scripts/fetch-cancer-genes.ts on 2026-09-23 from hgnc_complete_set.txt: external identifiers for the gene
 * records in targets-genes-wave.ts, in the shape of target-xrefs.ts, which spreads them into `targetXrefs`. ChEMBL ids
 * are not looked up here; scripts/fetch-xrefs.ts adds them when it next runs. Do not edit by hand.
 */
import type { TargetXref } from "./target-xrefs";

export const targetXrefsGenes: Record<string, TargetXref> = {};
