/**
 * External identifiers for every target, keyed by target id. GENERATED by scripts/fetch-xrefs.ts on 2026-09-10
 * from the HGNC REST API (ids, Ensembl, UniProt, Entrez, COSMIC, OMIM, locus) and the ChEMBL REST API (target id).
 * Do not edit by hand; re-run the script. Link builders live in src/components/XrefStrip.tsx.
 */
import { targetXrefsGenes } from "./target-xrefs-genes";

export type GeneXref = {
  symbol: string; name: string; hgnc: string; ensembl?: string; uniprot?: string; entrez?: string; chembl?: string; cosmic?: string; omim?: string; locus?: string;
};
export type TargetXref = { genes: GeneXref[] };

export const TARGET_XREFS_GENERATED = "2026-09-10";

// Gene records written by scripts/fetch-cancer-genes.ts carry their own HGNC-derived cross-references; a hand-fetched entry below wins.
export const targetXrefs: Record<string, TargetXref> = { ...targetXrefsGenes,
  akt: {
    genes: [
      {
        symbol: "AKT1",
        name: "AKT serine/threonine kinase 1",
        hgnc: "HGNC:391",
        ensembl: "ENSG00000142208",
        uniprot: "P31749",
        entrez: "207",
        chembl: "CHEMBL4282",
        cosmic: "AKT1",
        omim: "164730",
        locus: "14q32.33"
      },
      {
        symbol: "AKT2",
        name: "AKT serine/threonine kinase 2",
        hgnc: "HGNC:392",
        ensembl: "ENSG00000105221",
        uniprot: "P31751",
        entrez: "208",
        chembl: "CHEMBL2431",
        cosmic: "AKT2",
        omim: "164731",
        locus: "19q13.2"
      },
      {
        symbol: "AKT3",
        name: "AKT serine/threonine kinase 3",
        hgnc: "HGNC:393",
        ensembl: "ENSG00000117020",
        uniprot: "Q9Y243",
        entrez: "10000",
        chembl: "CHEMBL4816",
        omim: "611223",
        locus: "1q43-q44"
      }
    ]
  },
  alk: {
    genes: [
      {
        symbol: "ALK",
        name: "ALK receptor tyrosine kinase",
        hgnc: "HGNC:427",
        ensembl: "ENSG00000171094",
        uniprot: "Q9UM73",
        entrez: "238",
        chembl: "CHEMBL4247",
        cosmic: "ALK",
        omim: "105590",
        locus: "2p23.2-p23.1"
      }
    ]
  },
  "androgen-receptor": {
    genes: [
      {
        symbol: "AR",
        name: "androgen receptor",
        hgnc: "HGNC:644",
        ensembl: "ENSG00000169083",
        uniprot: "P10275",
        entrez: "367",
        chembl: "CHEMBL1871",
        cosmic: "AR",
        omim: "313700",
        locus: "Xq12"
      }
    ]
  },
  atr: {
    genes: [
      {
        symbol: "ATR",
        name: "ATR checkpoint kinase",
        hgnc: "HGNC:882",
        ensembl: "ENSG00000175054",
        uniprot: "Q13535",
        entrez: "545",
        chembl: "CHEMBL5024",
        cosmic: "ATR",
        omim: "601215",
        locus: "3q23"
      }
    ]
  },
  "b7h3": {
    genes: [
      {
        symbol: "CD276",
        name: "CD276 molecule",
        hgnc: "HGNC:19137",
        ensembl: "ENSG00000103855",
        uniprot: "Q5ZPR3",
        entrez: "80381",
        chembl: "CHEMBL3712879",
        omim: "605715",
        locus: "15q24.1"
      }
    ]
  },
  "bcl2": {
    genes: [
      {
        symbol: "BCL2",
        name: "BCL2 apoptosis regulator",
        hgnc: "HGNC:990",
        ensembl: "ENSG00000171791",
        uniprot: "P10415",
        entrez: "596",
        chembl: "CHEMBL4860",
        cosmic: "BCL2",
        omim: "151430",
        locus: "18q21.33"
      }
    ]
  },
  bcma: {
    genes: [
      {
        symbol: "TNFRSF17",
        name: "TNF receptor superfamily member 17",
        hgnc: "HGNC:11913",
        ensembl: "ENSG00000048462",
        uniprot: "Q02223",
        entrez: "608",
        chembl: "CHEMBL4523587",
        cosmic: "TNFRSF17",
        omim: "109545",
        locus: "16p13.13"
      }
    ]
  },
  "bcr-abl": {
    genes: [
      {
        symbol: "BCR",
        name: "BCR activator of RhoGEF and GTPase",
        hgnc: "HGNC:1014",
        ensembl: "ENSG00000186716",
        uniprot: "P11274",
        entrez: "613",
        chembl: "CHEMBL5146",
        cosmic: "BCR",
        omim: "151410",
        locus: "22q11.23"
      },
      {
        symbol: "ABL1",
        name: "ABL proto-oncogene 1, non-receptor tyrosine kinase",
        hgnc: "HGNC:76",
        ensembl: "ENSG00000097007",
        uniprot: "P00519",
        entrez: "25",
        chembl: "CHEMBL1862",
        cosmic: "ABL1",
        omim: "189980",
        locus: "9q34.12"
      }
    ]
  },
  braf: {
    genes: [
      {
        symbol: "BRAF",
        name: "B-Raf proto-oncogene, serine/threonine kinase",
        hgnc: "HGNC:1097",
        ensembl: "ENSG00000157764",
        uniprot: "P15056",
        entrez: "673",
        chembl: "CHEMBL5145",
        cosmic: "BRAF",
        omim: "164757",
        locus: "7q34"
      }
    ]
  },
  brca: {
    genes: [
      {
        symbol: "BRCA1",
        name: "BRCA1 DNA repair associated",
        hgnc: "HGNC:1100",
        ensembl: "ENSG00000012048",
        uniprot: "P38398",
        entrez: "672",
        chembl: "CHEMBL5990",
        cosmic: "BRCA1",
        omim: "113705",
        locus: "17q21.31"
      },
      {
        symbol: "BRCA2",
        name: "BRCA2 DNA repair associated",
        hgnc: "HGNC:1101",
        ensembl: "ENSG00000139618",
        uniprot: "P51587",
        entrez: "675",
        cosmic: "BRCA2",
        omim: "600185",
        locus: "13q13.1"
      }
    ]
  },
  btk: {
    genes: [
      {
        symbol: "BTK",
        name: "Bruton tyrosine kinase",
        hgnc: "HGNC:1133",
        ensembl: "ENSG00000010671",
        uniprot: "Q06187",
        entrez: "695",
        chembl: "CHEMBL5251",
        cosmic: "BTK",
        omim: "300300",
        locus: "Xq22.1"
      }
    ]
  },
  "ccr4": {
    genes: [
      {
        symbol: "CCR4",
        name: "C-C motif chemokine receptor 4",
        hgnc: "HGNC:1605",
        ensembl: "ENSG00000183813",
        uniprot: "P51679",
        entrez: "1233",
        chembl: "CHEMBL2414",
        omim: "604836",
        locus: "3p22.3"
      }
    ]
  },
  "cd123": {
    genes: [
      {
        symbol: "IL3RA",
        name: "interleukin 3 receptor subunit alpha",
        hgnc: "HGNC:6012",
        ensembl: "ENSG00000185291",
        uniprot: "P26951",
        entrez: "3563",
        chembl: "CHEMBL3712987",
        omim: "308385",
        locus: "Xp22.33 and Yp11.2"
      }
    ]
  },
  "cd19": {
    genes: [
      {
        symbol: "CD19",
        name: "CD19 molecule",
        hgnc: "HGNC:1633",
        ensembl: "ENSG00000177455",
        uniprot: "P15391",
        entrez: "930",
        chembl: "CHEMBL3390821",
        omim: "107265",
        locus: "16p11.2"
      }
    ]
  },
  "cd20": {
    genes: [
      {
        symbol: "MS4A1",
        name: "membrane spanning 4-domains A1",
        hgnc: "HGNC:7315",
        ensembl: "ENSG00000156738",
        uniprot: "P11836",
        entrez: "931",
        chembl: "CHEMBL2058",
        omim: "112210",
        locus: "11q12.2"
      }
    ]
  },
  "cd22": {
    genes: [
      {
        symbol: "CD22",
        name: "CD22 molecule",
        hgnc: "HGNC:1643",
        ensembl: "ENSG00000012124",
        uniprot: "P20273",
        entrez: "933",
        chembl: "CHEMBL3218",
        omim: "107266",
        locus: "19q13.12"
      }
    ]
  },
  "cd25": {
    genes: [
      {
        symbol: "IL2RA",
        name: "interleukin 2 receptor subunit alpha",
        hgnc: "HGNC:6008",
        ensembl: "ENSG00000134460",
        uniprot: "P01589",
        entrez: "3559",
        chembl: "CHEMBL1778",
        omim: "147730",
        locus: "10p15.1"
      }
    ]
  },
  "cd3": {
    genes: [
      {
        symbol: "CD3E",
        name: "CD3 epsilon subunit of T-cell receptor complex",
        hgnc: "HGNC:1674",
        ensembl: "ENSG00000198851",
        uniprot: "P07766",
        entrez: "916",
        chembl: "CHEMBL1975",
        omim: "186830",
        locus: "11q23.3"
      }
    ]
  },
  "cd30": {
    genes: [
      {
        symbol: "TNFRSF8",
        name: "TNF receptor superfamily member 8",
        hgnc: "HGNC:11923",
        ensembl: "ENSG00000120949",
        uniprot: "P28908",
        entrez: "943",
        chembl: "CHEMBL2364161",
        omim: "153243",
        locus: "1p36.22"
      }
    ]
  },
  "cd33": {
    genes: [
      {
        symbol: "CD33",
        name: "CD33 molecule",
        hgnc: "HGNC:1659",
        ensembl: "ENSG00000105383",
        uniprot: "P20138",
        entrez: "945",
        chembl: "CHEMBL1842",
        omim: "159590",
        locus: "19q13.41"
      }
    ]
  },
  "cd38": {
    genes: [
      {
        symbol: "CD38",
        name: "CD38 molecule",
        hgnc: "HGNC:1667",
        ensembl: "ENSG00000004468",
        uniprot: "P28907",
        entrez: "952",
        chembl: "CHEMBL4660",
        omim: "107270",
        locus: "4p15.32"
      }
    ]
  },
  "cd47": {
    genes: [
      {
        symbol: "CD47",
        name: "CD47 molecule",
        hgnc: "HGNC:1682",
        ensembl: "ENSG00000196776",
        uniprot: "Q08722",
        entrez: "961",
        chembl: "CHEMBL3714583",
        omim: "601028",
        locus: "3q13.12"
      }
    ]
  },
  "cd52": {
    genes: [
      {
        symbol: "CD52",
        name: "CD52 molecule",
        hgnc: "HGNC:1804",
        ensembl: "ENSG00000169442",
        uniprot: "P31358",
        entrez: "1043",
        chembl: "CHEMBL1912",
        omim: "114280",
        locus: "1p36.11"
      }
    ]
  },
  "cd7": {
    genes: [
      {
        symbol: "CD7",
        name: "CD7 molecule",
        hgnc: "HGNC:1695",
        ensembl: "ENSG00000173762",
        uniprot: "P09564",
        entrez: "924",
        omim: "186820",
        locus: "17q25.3"
      }
    ]
  },
  "cd70": {
    genes: [
      {
        symbol: "CD70",
        name: "CD70 molecule",
        hgnc: "HGNC:11937",
        ensembl: "ENSG00000125726",
        uniprot: "P32970",
        entrez: "970",
        chembl: "CHEMBL3712913",
        omim: "602840",
        locus: "19p13.3"
      }
    ]
  },
  "cd73-adenosine": {
    genes: [
      {
        symbol: "NT5E",
        name: "5'-nucleotidase ecto",
        hgnc: "HGNC:8021",
        ensembl: "ENSG00000135318",
        uniprot: "P21589",
        entrez: "4907",
        chembl: "CHEMBL5957",
        omim: "129190",
        locus: "6q14.3"
      }
    ]
  },
  "cd79b": {
    genes: [
      {
        symbol: "CD79B",
        name: "CD79b molecule",
        hgnc: "HGNC:1699",
        ensembl: "ENSG00000007312",
        uniprot: "P40259",
        entrez: "974",
        chembl: "CHEMBL3712852",
        cosmic: "CD79B",
        omim: "147245",
        locus: "17q23.3"
      }
    ]
  },
  "cdh6": {
    genes: [
      {
        symbol: "CDH6",
        name: "cadherin 6",
        hgnc: "HGNC:1765",
        ensembl: "ENSG00000113361",
        uniprot: "P55285",
        entrez: "1004",
        omim: "603007",
        locus: "5p13.3"
      }
    ]
  },
  "cdk4-6": {
    genes: [
      {
        symbol: "CDK4",
        name: "cyclin dependent kinase 4",
        hgnc: "HGNC:1773",
        ensembl: "ENSG00000135446",
        uniprot: "P11802",
        entrez: "1019",
        chembl: "CHEMBL331",
        cosmic: "CDK4",
        omim: "123829",
        locus: "12q14.1"
      },
      {
        symbol: "CDK6",
        name: "cyclin dependent kinase 6",
        hgnc: "HGNC:1777",
        ensembl: "ENSG00000105810",
        uniprot: "Q00534",
        entrez: "1021",
        chembl: "CHEMBL2508",
        cosmic: "CDK6",
        omim: "603368",
        locus: "7q21.2"
      }
    ]
  },
  "ceacam5": {
    genes: [
      {
        symbol: "CEACAM5",
        name: "CEA cell adhesion molecule 5",
        hgnc: "HGNC:1817",
        ensembl: "ENSG00000105388",
        uniprot: "P06731",
        entrez: "1048",
        chembl: "CHEMBL3712881",
        omim: "114890",
        locus: "19q13.2"
      }
    ]
  },
  "cldn18-2": {
    genes: [
      {
        symbol: "CLDN18",
        name: "claudin 18",
        hgnc: "HGNC:2039",
        ensembl: "ENSG00000066405",
        uniprot: "P56856",
        entrez: "51208",
        chembl: "CHEMBL3712859",
        omim: "609210",
        locus: "3q22.3"
      }
    ]
  },
  "cldn6": {
    genes: [
      {
        symbol: "CLDN6",
        name: "claudin 6",
        hgnc: "HGNC:2048",
        ensembl: "ENSG00000184697",
        uniprot: "P56747",
        entrez: "9074",
        omim: "615798",
        locus: "16p13.3"
      }
    ]
  },
  "csf1r": {
    genes: [
      {
        symbol: "CSF1R",
        name: "colony stimulating factor 1 receptor",
        hgnc: "HGNC:2433",
        ensembl: "ENSG00000182578",
        uniprot: "P07333",
        entrez: "1436",
        chembl: "CHEMBL1844",
        omim: "164770",
        locus: "5q32"
      }
    ]
  },
  "ctla4": {
    genes: [
      {
        symbol: "CTLA4",
        name: "cytotoxic T-lymphocyte associated protein 4",
        hgnc: "HGNC:2505",
        ensembl: "ENSG00000163599",
        uniprot: "P16410",
        entrez: "1493",
        chembl: "CHEMBL2364164",
        omim: "123890",
        locus: "2q33.2"
      }
    ]
  },
  "cxcr4": {
    genes: [
      {
        symbol: "CXCR4",
        name: "C-X-C motif chemokine receptor 4",
        hgnc: "HGNC:2561",
        ensembl: "ENSG00000121966",
        uniprot: "P61073",
        entrez: "7852",
        chembl: "CHEMBL2107",
        cosmic: "CXCR4",
        omim: "162643",
        locus: "2q22.1"
      }
    ]
  },
  "dll3": {
    genes: [
      {
        symbol: "DLL3",
        name: "delta like canonical Notch ligand 3",
        hgnc: "HGNC:2909",
        ensembl: "ENSG00000090932",
        uniprot: "Q9NYJ7",
        entrez: "10683",
        chembl: "CHEMBL4630888",
        omim: "602768",
        locus: "19q13.2"
      }
    ]
  },
  egfr: {
    genes: [
      {
        symbol: "EGFR",
        name: "epidermal growth factor receptor",
        hgnc: "HGNC:3236",
        ensembl: "ENSG00000146648",
        uniprot: "P00533",
        entrez: "1956",
        chembl: "CHEMBL203",
        cosmic: "EGFR",
        omim: "131550",
        locus: "7p11.2"
      }
    ]
  },
  epcam: {
    genes: [
      {
        symbol: "EPCAM",
        name: "epithelial cell adhesion molecule",
        hgnc: "HGNC:11529",
        ensembl: "ENSG00000119888",
        uniprot: "P16422",
        entrez: "4072",
        chembl: "CHEMBL3580493",
        omim: "185535",
        locus: "2p21"
      }
    ]
  },
  "estrogen-receptor": {
    genes: [
      {
        symbol: "ESR1",
        name: "estrogen receptor 1",
        hgnc: "HGNC:3467",
        ensembl: "ENSG00000091831",
        uniprot: "P03372",
        entrez: "2099",
        chembl: "CHEMBL206",
        cosmic: "ESR1",
        omim: "133430",
        locus: "6q25.1-q25.2"
      }
    ]
  },
  "ewsr1-fli1": {
    genes: [
      {
        symbol: "EWSR1",
        name: "EWS RNA binding protein 1",
        hgnc: "HGNC:3508",
        ensembl: "ENSG00000182944",
        uniprot: "Q01844",
        entrez: "2130",
        chembl: "CHEMBL3351202",
        cosmic: "EWSR1",
        omim: "133450",
        locus: "22q12.2"
      },
      {
        symbol: "FLI1",
        name: "Fli-1 proto-oncogene, ETS transcription factor",
        hgnc: "HGNC:3749",
        ensembl: "ENSG00000151702",
        uniprot: "Q01543",
        entrez: "2313",
        chembl: "CHEMBL5465299",
        cosmic: "FLI1",
        omim: "193067",
        locus: "11q24.3"
      }
    ]
  },
  "ezh2": {
    genes: [
      {
        symbol: "EZH2",
        name: "enhancer of zeste 2 polycomb repressive complex 2 subunit",
        hgnc: "HGNC:3527",
        ensembl: "ENSG00000106462",
        uniprot: "Q15910",
        entrez: "2146",
        chembl: "CHEMBL2189110",
        cosmic: "EZH2",
        omim: "601573",
        locus: "7q36.1"
      }
    ]
  },
  fap: {
    genes: [
      {
        symbol: "FAP",
        name: "fibroblast activation protein alpha",
        hgnc: "HGNC:3590",
        ensembl: "ENSG00000078098",
        uniprot: "Q12884",
        entrez: "2191",
        chembl: "CHEMBL4683",
        omim: "600403",
        locus: "2q24.2"
      }
    ]
  },
  "fgfr2": {
    genes: [
      {
        symbol: "FGFR2",
        name: "fibroblast growth factor receptor 2",
        hgnc: "HGNC:3689",
        ensembl: "ENSG00000066468",
        uniprot: "P21802",
        entrez: "2263",
        chembl: "CHEMBL4142",
        cosmic: "FGFR2",
        omim: "176943",
        locus: "10q26.13"
      }
    ]
  },
  "flt3": {
    genes: [
      {
        symbol: "FLT3",
        name: "fms related receptor tyrosine kinase 3",
        hgnc: "HGNC:3765",
        ensembl: "ENSG00000122025",
        uniprot: "P36888",
        entrez: "2322",
        chembl: "CHEMBL1974",
        cosmic: "FLT3",
        omim: "136351",
        locus: "13q12.2"
      }
    ]
  },
  "folr1": {
    genes: [
      {
        symbol: "FOLR1",
        name: "folate receptor alpha",
        hgnc: "HGNC:3791",
        ensembl: "ENSG00000110195",
        uniprot: "P15328",
        entrez: "2348",
        chembl: "CHEMBL2121",
        omim: "136430",
        locus: "11q13.4"
      }
    ]
  },
  "gd2": {
    genes: [
      {
        symbol: "B4GALNT1",
        name: "beta-1,4-N-acetyl-galactosaminyltransferase 1",
        hgnc: "HGNC:4117",
        ensembl: "ENSG00000135454",
        uniprot: "Q00973",
        entrez: "2583",
        omim: "601873",
        locus: "12q13.3"
      }
    ]
  },
  "gpc3": {
    genes: [
      {
        symbol: "GPC3",
        name: "glypican 3",
        hgnc: "HGNC:4451",
        ensembl: "ENSG00000147257",
        uniprot: "P51654",
        entrez: "2719",
        chembl: "CHEMBL4630889",
        cosmic: "GPC3",
        omim: "300037",
        locus: "Xq26.2"
      }
    ]
  },
  "gp100": {
    genes: [
      {
        symbol: "PMEL",
        name: "premelanosome protein",
        hgnc: "HGNC:10880",
        ensembl: "ENSG00000185664",
        uniprot: "P40967",
        entrez: "6490",
        chembl: "CHEMBL3712988",
        omim: "155550",
        locus: "12q13.2"
      }
    ]
  },
  "gprc5d": {
    genes: [
      {
        symbol: "GPRC5D",
        name: "G protein-coupled receptor class C group 5 member D",
        hgnc: "HGNC:13310",
        ensembl: "ENSG00000111291",
        uniprot: "Q9NZD1",
        entrez: "55507",
        chembl: "CHEMBL4523925",
        omim: "607437",
        locus: "12p13.1"
      }
    ]
  },
  grpr: {
    genes: [
      {
        symbol: "GRPR",
        name: "gastrin releasing peptide receptor",
        hgnc: "HGNC:4609",
        ensembl: "ENSG00000126010",
        uniprot: "P30550",
        entrez: "2925",
        chembl: "CHEMBL4959",
        omim: "305670",
        locus: "Xp22.2"
      }
    ]
  },
  "her2": {
    genes: [
      {
        symbol: "ERBB2",
        name: "erb-b2 receptor tyrosine kinase 2",
        hgnc: "HGNC:3430",
        ensembl: "ENSG00000141736",
        uniprot: "P04626",
        entrez: "2064",
        chembl: "CHEMBL1824",
        cosmic: "ERBB2",
        omim: "164870",
        locus: "17q12"
      }
    ]
  },
  "her3": {
    genes: [
      {
        symbol: "ERBB3",
        name: "erb-b2 receptor tyrosine kinase 3",
        hgnc: "HGNC:3431",
        ensembl: "ENSG00000065361",
        uniprot: "P21860",
        entrez: "2065",
        chembl: "CHEMBL5838",
        cosmic: "ERBB3",
        omim: "190151",
        locus: "12q13.2"
      }
    ]
  },
  "hif2a": {
    genes: [
      {
        symbol: "EPAS1",
        name: "endothelial PAS domain protein 1",
        hgnc: "HGNC:3374",
        ensembl: "ENSG00000116016",
        uniprot: "Q99814",
        entrez: "2034",
        chembl: "CHEMBL1744522",
        cosmic: "EPAS1",
        omim: "603349",
        locus: "2p21"
      }
    ]
  },
  hdac: {
    genes: [
      {
        symbol: "HDAC1",
        name: "histone deacetylase 1",
        hgnc: "HGNC:4852",
        ensembl: "ENSG00000116478",
        uniprot: "Q13547",
        entrez: "3065",
        chembl: "CHEMBL325",
        omim: "601241",
        locus: "1p35.2-p35.1"
      },
      {
        symbol: "HDAC2",
        name: "histone deacetylase 2",
        hgnc: "HGNC:4853",
        ensembl: "ENSG00000196591",
        uniprot: "Q92769",
        entrez: "3066",
        chembl: "CHEMBL1937",
        omim: "605164",
        locus: "6q21"
      },
      {
        symbol: "HDAC3",
        name: "histone deacetylase 3",
        hgnc: "HGNC:4854",
        ensembl: "ENSG00000171720",
        uniprot: "O15379",
        entrez: "8841",
        chembl: "CHEMBL1829",
        omim: "605166",
        locus: "5q31.3"
      },
      {
        symbol: "HDAC6",
        name: "histone deacetylase 6",
        hgnc: "HGNC:14064",
        ensembl: "ENSG00000094631",
        uniprot: "Q9UBN7",
        entrez: "10013",
        chembl: "CHEMBL1865",
        omim: "300272",
        locus: "Xp11.23"
      }
    ]
  },
  idh: {
    genes: [
      {
        symbol: "IDH1",
        name: "isocitrate dehydrogenase (NADP(+)) 1",
        hgnc: "HGNC:5382",
        ensembl: "ENSG00000138413",
        uniprot: "O75874",
        entrez: "3417",
        chembl: "CHEMBL2007625",
        cosmic: "IDH1",
        omim: "147700",
        locus: "2q34"
      },
      {
        symbol: "IDH2",
        name: "isocitrate dehydrogenase (NADP(+)) 2",
        hgnc: "HGNC:5383",
        ensembl: "ENSG00000182054",
        uniprot: "P48735",
        entrez: "3418",
        chembl: "CHEMBL3991501",
        cosmic: "IDH2",
        omim: "147650",
        locus: "15q26.1"
      }
    ]
  },
  "il6": {
    genes: [
      {
        symbol: "IL6",
        name: "interleukin 6",
        hgnc: "HGNC:6018",
        ensembl: "ENSG00000136244",
        uniprot: "P05231",
        entrez: "3569",
        chembl: "CHEMBL1795129",
        omim: "147620",
        locus: "7p15.3"
      },
      {
        symbol: "IL6R",
        name: "interleukin 6 receptor",
        hgnc: "HGNC:6019",
        ensembl: "ENSG00000160712",
        uniprot: "P08887",
        entrez: "3570",
        chembl: "CHEMBL2364155",
        omim: "147880",
        locus: "1q21.3"
      }
    ]
  },
  "jak2": {
    genes: [
      {
        symbol: "JAK2",
        name: "Janus kinase 2",
        hgnc: "HGNC:6192",
        ensembl: "ENSG00000096968",
        uniprot: "O60674",
        entrez: "3717",
        chembl: "CHEMBL2971",
        cosmic: "JAK2",
        omim: "147796",
        locus: "9p24.1"
      }
    ]
  },
  kit: {
    genes: [
      {
        symbol: "KIT",
        name: "KIT proto-oncogene, receptor tyrosine kinase",
        hgnc: "HGNC:6342",
        ensembl: "ENSG00000157404",
        uniprot: "P10721",
        entrez: "3815",
        chembl: "CHEMBL1936",
        cosmic: "KIT",
        omim: "164920",
        locus: "4q12"
      }
    ]
  },
  "klk2": {
    genes: [
      {
        symbol: "KLK2",
        name: "kallikrein related peptidase 2",
        hgnc: "HGNC:6363",
        ensembl: "ENSG00000167751",
        uniprot: "P20151",
        entrez: "3817",
        chembl: "CHEMBL2442",
        cosmic: "KLK2",
        omim: "147960",
        locus: "19q13.33"
      }
    ]
  },
  "kmt2a": {
    genes: [
      {
        symbol: "KMT2A",
        name: "lysine methyltransferase 2A",
        hgnc: "HGNC:7132",
        ensembl: "ENSG00000118058",
        uniprot: "Q03164",
        entrez: "4297",
        chembl: "CHEMBL1293299",
        cosmic: "KMT2A",
        omim: "159555",
        locus: "11q23.3"
      }
    ]
  },
  kras: {
    genes: [
      {
        symbol: "KRAS",
        name: "KRas proto-oncogene, GTPase",
        hgnc: "HGNC:6407",
        ensembl: "ENSG00000133703",
        uniprot: "P01116",
        entrez: "3845",
        chembl: "CHEMBL2189121",
        cosmic: "KRAS",
        omim: "190070",
        locus: "12p12.1"
      }
    ]
  },
  "lag3": {
    genes: [
      {
        symbol: "LAG3",
        name: "lymphocyte activating 3",
        hgnc: "HGNC:6476",
        ensembl: "ENSG00000089692",
        uniprot: "P18627",
        entrez: "3902",
        chembl: "CHEMBL4630881",
        omim: "153337",
        locus: "12p13.31"
      }
    ]
  },
  "liv1": {
    genes: [
      {
        symbol: "SLC39A6",
        name: "solute carrier family 39 member 6",
        hgnc: "HGNC:18607",
        ensembl: "ENSG00000141424",
        uniprot: "Q13433",
        entrez: "25800",
        chembl: "CHEMBL4523581",
        omim: "608731",
        locus: "18q12.2"
      }
    ]
  },
  "mage-a4": {
    genes: [
      {
        symbol: "MAGEA4",
        name: "MAGE family member A4",
        hgnc: "HGNC:6802",
        ensembl: "ENSG00000147381",
        uniprot: "P43358",
        entrez: "4103",
        chembl: "CHEMBL4296022",
        omim: "300175",
        locus: "Xq28"
      }
    ]
  },
  "mdm2": {
    genes: [
      {
        symbol: "MDM2",
        name: "MDM2 proto-oncogene",
        hgnc: "HGNC:6973",
        ensembl: "ENSG00000135679",
        uniprot: "Q00987",
        entrez: "4193",
        chembl: "CHEMBL5023",
        cosmic: "MDM2",
        omim: "164785",
        locus: "12q15"
      }
    ]
  },
  mek: {
    genes: [
      {
        symbol: "MAP2K1",
        name: "mitogen-activated protein kinase kinase 1",
        hgnc: "HGNC:6840",
        ensembl: "ENSG00000169032",
        uniprot: "Q02750",
        entrez: "5604",
        chembl: "CHEMBL3587",
        cosmic: "MAP2K1",
        omim: "176872",
        locus: "15q22.31"
      },
      {
        symbol: "MAP2K2",
        name: "mitogen-activated protein kinase kinase 2",
        hgnc: "HGNC:6842",
        ensembl: "ENSG00000126934",
        uniprot: "P36507",
        entrez: "5605",
        chembl: "CHEMBL2964",
        cosmic: "MAP2K2",
        omim: "601263",
        locus: "19p13.3"
      }
    ]
  },
  menin: {
    genes: [
      {
        symbol: "MEN1",
        name: "menin 1",
        hgnc: "HGNC:7010",
        ensembl: "ENSG00000133895",
        uniprot: "O00255",
        entrez: "4221",
        chembl: "CHEMBL1615381",
        cosmic: "MEN1",
        omim: "613733",
        locus: "11q13.1"
      }
    ]
  },
  mesothelin: {
    genes: [
      {
        symbol: "MSLN",
        name: "mesothelin",
        hgnc: "HGNC:7371",
        ensembl: "ENSG00000102854",
        uniprot: "Q13421",
        entrez: "10232",
        chembl: "CHEMBL3712878",
        omim: "601051",
        locus: "16p13.3"
      }
    ]
  },
  met: {
    genes: [
      {
        symbol: "MET",
        name: "MET proto-oncogene, receptor tyrosine kinase",
        hgnc: "HGNC:7029",
        ensembl: "ENSG00000105976",
        uniprot: "P08581",
        entrez: "4233",
        chembl: "CHEMBL3717",
        cosmic: "MET",
        omim: "164860",
        locus: "7q31.2"
      }
    ]
  },
  mtor: {
    genes: [
      {
        symbol: "MTOR",
        name: "mechanistic target of rapamycin kinase",
        hgnc: "HGNC:3942",
        ensembl: "ENSG00000198793",
        uniprot: "P42345",
        entrez: "2475",
        chembl: "CHEMBL2842",
        cosmic: "MTOR",
        omim: "601231",
        locus: "1p36.22"
      }
    ]
  },
  "muc16": {
    genes: [
      {
        symbol: "MUC16",
        name: "mucin 16, cell surface associated",
        hgnc: "HGNC:15582",
        ensembl: "ENSG00000181143",
        uniprot: "Q8WXI7",
        entrez: "94025",
        chembl: "CHEMBL3580482",
        omim: "606154",
        locus: "19p13.2"
      }
    ]
  },
  "nectin4": {
    genes: [
      {
        symbol: "NECTIN4",
        name: "nectin cell adhesion molecule 4",
        hgnc: "HGNC:19688",
        ensembl: "ENSG00000143217",
        uniprot: "Q96NY8",
        entrez: "81607",
        chembl: "CHEMBL3712928",
        omim: "609607",
        locus: "1q23.3"
      }
    ]
  },
  "npm1": {
    genes: [
      {
        symbol: "NPM1",
        name: "nucleophosmin 1",
        hgnc: "HGNC:7910",
        ensembl: "ENSG00000181163",
        uniprot: "P06748",
        entrez: "4869",
        chembl: "CHEMBL5178",
        cosmic: "NPM1",
        omim: "164040",
        locus: "5q35.1"
      }
    ]
  },
  ntrk: {
    genes: [
      {
        symbol: "NTRK1",
        name: "neurotrophic receptor tyrosine kinase 1",
        hgnc: "HGNC:8031",
        ensembl: "ENSG00000198400",
        uniprot: "P04629",
        entrez: "4914",
        chembl: "CHEMBL2815",
        cosmic: "NTRK1",
        omim: "191315",
        locus: "1q23.1"
      },
      {
        symbol: "NTRK2",
        name: "neurotrophic receptor tyrosine kinase 2",
        hgnc: "HGNC:8032",
        ensembl: "ENSG00000148053",
        uniprot: "Q16620",
        entrez: "4915",
        chembl: "CHEMBL4898",
        cosmic: "NTRK2",
        omim: "600456",
        locus: "9q21.33"
      },
      {
        symbol: "NTRK3",
        name: "neurotrophic receptor tyrosine kinase 3",
        hgnc: "HGNC:8033",
        ensembl: "ENSG00000140538",
        uniprot: "Q16288",
        entrez: "4916",
        chembl: "CHEMBL5608",
        cosmic: "NTRK3",
        omim: "191316",
        locus: "15q25.3"
      }
    ]
  },
  parp: {
    genes: [
      {
        symbol: "PARP1",
        name: "poly(ADP-ribose) polymerase 1",
        hgnc: "HGNC:270",
        ensembl: "ENSG00000143799",
        uniprot: "P09874",
        entrez: "142",
        chembl: "CHEMBL3105",
        omim: "173870",
        locus: "1q42.12"
      }
    ]
  },
  "pd1": {
    genes: [
      {
        symbol: "PDCD1",
        name: "programmed cell death 1",
        hgnc: "HGNC:8760",
        ensembl: "ENSG00000188389",
        uniprot: "Q15116",
        entrez: "5133",
        chembl: "CHEMBL3307223",
        omim: "600244",
        locus: "2q37.3"
      }
    ]
  },
  "pdl1": {
    genes: [
      {
        symbol: "CD274",
        name: "CD274 molecule",
        hgnc: "HGNC:17635",
        ensembl: "ENSG00000120217",
        uniprot: "Q9NZQ7",
        entrez: "29126",
        chembl: "CHEMBL3580522",
        cosmic: "CD274",
        omim: "605402",
        locus: "9p24.1"
      }
    ]
  },
  pdgfra: {
    genes: [
      {
        symbol: "PDGFRA",
        name: "platelet derived growth factor receptor alpha",
        hgnc: "HGNC:8803",
        ensembl: "ENSG00000134853",
        uniprot: "P16234",
        entrez: "5156",
        chembl: "CHEMBL2007",
        cosmic: "PDGFRA",
        omim: "173490",
        locus: "4q12"
      }
    ]
  },
  "pik3ca": {
    genes: [
      {
        symbol: "PIK3CA",
        name: "phosphatidylinositol-4,5-bisphosphate 3-kinase catalytic subunit alpha",
        hgnc: "HGNC:8975",
        ensembl: "ENSG00000121879",
        uniprot: "P42336",
        entrez: "5290",
        chembl: "CHEMBL4005",
        cosmic: "PIK3CA",
        omim: "171834",
        locus: "3q26.32"
      }
    ]
  },
  prame: {
    genes: [
      {
        symbol: "PRAME",
        name: "PRAME nuclear receptor transcriptional regulator",
        hgnc: "HGNC:9336",
        ensembl: "ENSG00000185686",
        uniprot: "P78395",
        entrez: "23532",
        omim: "606021",
        locus: "22q11.22"
      }
    ]
  },
  "prmt5-mtap": {
    genes: [
      {
        symbol: "PRMT5",
        name: "protein arginine methyltransferase 5",
        hgnc: "HGNC:10894",
        ensembl: "ENSG00000100462",
        uniprot: "O14744",
        entrez: "10419",
        chembl: "CHEMBL1795116",
        omim: "604045",
        locus: "14q11.2"
      },
      {
        symbol: "MTAP",
        name: "methylthioadenosine phosphorylase",
        hgnc: "HGNC:7413",
        ensembl: "ENSG00000099810",
        uniprot: "Q13126",
        entrez: "4507",
        chembl: "CHEMBL4941",
        omim: "156540",
        locus: "9p21.3"
      }
    ]
  },
  psma: {
    genes: [
      {
        symbol: "FOLH1",
        name: "folate hydrolase 1",
        hgnc: "HGNC:3788",
        ensembl: "ENSG00000086205",
        uniprot: "Q04609",
        entrez: "2346",
        chembl: "CHEMBL1892",
        omim: "600934",
        locus: "11p11.12"
      }
    ]
  },
  rankl: {
    genes: [
      {
        symbol: "TNFSF11",
        name: "TNF superfamily member 11",
        hgnc: "HGNC:11926",
        ensembl: "ENSG00000120659",
        uniprot: "O14788",
        entrez: "8600",
        chembl: "CHEMBL2364162",
        omim: "602642",
        locus: "13q14.11"
      }
    ]
  },
  ret: {
    genes: [
      {
        symbol: "RET",
        name: "ret proto-oncogene",
        hgnc: "HGNC:9967",
        ensembl: "ENSG00000165731",
        uniprot: "P07949",
        entrez: "5979",
        chembl: "CHEMBL2041",
        cosmic: "RET",
        omim: "164761",
        locus: "10q11.21"
      }
    ]
  },
  rxr: {
    genes: [
      {
        symbol: "RXRA",
        name: "retinoid X receptor alpha",
        hgnc: "HGNC:10477",
        ensembl: "ENSG00000186350",
        uniprot: "P19793",
        entrez: "6256",
        chembl: "CHEMBL2061",
        omim: "180245",
        locus: "9q34.2"
      },
      {
        symbol: "RXRB",
        name: "retinoid X receptor beta",
        hgnc: "HGNC:10478",
        ensembl: "ENSG00000204231",
        uniprot: "P28702",
        entrez: "6257",
        chembl: "CHEMBL1870",
        omim: "180246",
        locus: "6p21.32"
      },
      {
        symbol: "RXRG",
        name: "retinoid X receptor gamma",
        hgnc: "HGNC:10479",
        ensembl: "ENSG00000143171",
        uniprot: "P48443",
        entrez: "6258",
        chembl: "CHEMBL2004",
        omim: "180247",
        locus: "1q23.3"
      }
    ]
  },
  "ror1": {
    genes: [
      {
        symbol: "ROR1",
        name: "ROR family WNT receptor 1",
        hgnc: "HGNC:10256",
        ensembl: "ENSG00000185483",
        uniprot: "Q01973",
        entrez: "4919",
        chembl: "CHEMBL4665585",
        omim: "602336",
        locus: "1p31.3"
      }
    ]
  },
  "ros1": {
    genes: [
      {
        symbol: "ROS1",
        name: "ROS proto-oncogene 1, receptor tyrosine kinase",
        hgnc: "HGNC:10261",
        ensembl: "ENSG00000047936",
        uniprot: "P08922",
        entrez: "6098",
        chembl: "CHEMBL5568",
        cosmic: "ROS1",
        omim: "165020",
        locus: "6q22.1"
      }
    ]
  },
  smoothened: {
    genes: [
      {
        symbol: "SMO",
        name: "smoothened, frizzled class receptor",
        hgnc: "HGNC:11119",
        ensembl: "ENSG00000128602",
        uniprot: "Q99835",
        entrez: "6608",
        chembl: "CHEMBL5971",
        cosmic: "SMO",
        omim: "601500",
        locus: "7q32.1"
      }
    ]
  },
  "sstr2": {
    genes: [
      {
        symbol: "SSTR2",
        name: "somatostatin receptor 2",
        hgnc: "HGNC:11331",
        ensembl: "ENSG00000180616",
        uniprot: "P30874",
        entrez: "6752",
        chembl: "CHEMBL1804",
        omim: "182452",
        locus: "17q25.1"
      }
    ]
  },
  "steap1": {
    genes: [
      {
        symbol: "STEAP1",
        name: "STEAP family member 1",
        hgnc: "HGNC:11378",
        ensembl: "ENSG00000164647",
        uniprot: "Q9UHE8",
        entrez: "26872",
        chembl: "CHEMBL3712956",
        omim: "604415",
        locus: "7q21.13"
      }
    ]
  },
  tigit: {
    genes: [
      {
        symbol: "TIGIT",
        name: "T cell immunoreceptor with Ig and ITIM domains",
        hgnc: "HGNC:26838",
        ensembl: "ENSG00000181847",
        uniprot: "Q495A1",
        entrez: "201633",
        chembl: "CHEMBL4630878",
        omim: "612859",
        locus: "3q13.31"
      }
    ]
  },
  "tim3": {
    genes: [
      {
        symbol: "HAVCR2",
        name: "hepatitis A virus cellular receptor 2",
        hgnc: "HGNC:18437",
        ensembl: "ENSG00000135077",
        uniprot: "Q8TDQ0",
        entrez: "84868",
        chembl: "CHEMBL4630879",
        omim: "606652",
        locus: "5q33.3"
      }
    ]
  },
  "tissue-factor": {
    genes: [
      {
        symbol: "F3",
        name: "coagulation factor III, tissue factor",
        hgnc: "HGNC:3541",
        ensembl: "ENSG00000117525",
        uniprot: "P13726",
        entrez: "2152",
        chembl: "CHEMBL4081",
        omim: "134390",
        locus: "1p21.3"
      }
    ]
  },
  "tp53": {
    genes: [
      {
        symbol: "TP53",
        name: "tumor protein p53",
        hgnc: "HGNC:11998",
        ensembl: "ENSG00000141510",
        uniprot: "P04637",
        entrez: "7157",
        chembl: "CHEMBL4096",
        cosmic: "TP53",
        omim: "191170",
        locus: "17p13.1"
      }
    ]
  },
  "trop2": {
    genes: [
      {
        symbol: "TACSTD2",
        name: "tumor associated calcium signal transducer 2",
        hgnc: "HGNC:11530",
        ensembl: "ENSG00000184292",
        uniprot: "P09758",
        entrez: "4070",
        chembl: "CHEMBL3856163",
        omim: "137290",
        locus: "1p32.1"
      }
    ]
  },
  vegf: {
    genes: [
      {
        symbol: "VEGFA",
        name: "vascular endothelial growth factor A",
        hgnc: "HGNC:12680",
        ensembl: "ENSG00000112715",
        uniprot: "P15692",
        entrez: "7422",
        chembl: "CHEMBL1783",
        omim: "192240",
        locus: "6p21.1"
      },
      {
        symbol: "KDR",
        name: "kinase insert domain receptor",
        hgnc: "HGNC:6307",
        ensembl: "ENSG00000128052",
        uniprot: "P35968",
        entrez: "3791",
        chembl: "CHEMBL279",
        cosmic: "KDR",
        omim: "191306",
        locus: "4q12"
      },
      {
        symbol: "FLT1",
        name: "fms related receptor tyrosine kinase 1",
        hgnc: "HGNC:3763",
        ensembl: "ENSG00000102755",
        uniprot: "P17948",
        entrez: "2321",
        chembl: "CHEMBL1868",
        omim: "165070",
        locus: "13q12.3"
      },
      {
        symbol: "FLT4",
        name: "fms related receptor tyrosine kinase 4",
        hgnc: "HGNC:3767",
        ensembl: "ENSG00000037280",
        uniprot: "P35916",
        entrez: "2324",
        chembl: "CHEMBL1955",
        cosmic: "FLT4",
        omim: "136352",
        locus: "5q35.3"
      }
    ]
  },
  vista: {
    genes: [
      {
        symbol: "VSIR",
        name: "V-set immunoregulatory receptor",
        hgnc: "HGNC:30085",
        ensembl: "ENSG00000107738",
        uniprot: "Q9H7M9",
        entrez: "64115",
        chembl: "CHEMBL4523457",
        omim: "615608",
        locus: "10q22.1"
      }
    ]
  },
  "wee1": {
    genes: [
      {
        symbol: "WEE1",
        name: "WEE1 G2 checkpoint kinase",
        hgnc: "HGNC:12761",
        ensembl: "ENSG00000166483",
        uniprot: "P30291",
        entrez: "7465",
        chembl: "CHEMBL5491",
        omim: "193525",
        locus: "11p15.4"
      }
    ]
  },
  wrn: {
    genes: [
      {
        symbol: "WRN",
        name: "WRN RecQ like helicase",
        hgnc: "HGNC:12791",
        ensembl: "ENSG00000165392",
        uniprot: "Q14191",
        entrez: "7486",
        chembl: "CHEMBL2146312",
        cosmic: "WRN",
        omim: "604611",
        locus: "8p12"
      }
    ]
  },
  cyp17a1: {
    genes: [
      {
        symbol: "CYP17A1",
        name: "cytochrome P450 family 17 subfamily A member 1",
        hgnc: "HGNC:2593",
        ensembl: "ENSG00000148795",
        uniprot: "P05093",
        entrez: "1586",
        locus: "10q24.32"
      }
    ]
  },
  aromatase: {
    genes: [
      {
        symbol: "CYP19A1",
        name: "cytochrome P450 family 19 subfamily A member 1",
        hgnc: "HGNC:2594",
        ensembl: "ENSG00000137869",
        uniprot: "P11511",
        entrez: "1588",
        locus: "15q21.2"
      }
    ]
  },
  proteasome: {
    genes: [
      {
        symbol: "PSMB5",
        name: "proteasome 20S subunit beta 5",
        hgnc: "HGNC:9542",
        ensembl: "ENSG00000100804",
        uniprot: "P28074",
        entrez: "5693",
        locus: "14q11.2"
      }
    ]
  },
  cereblon: {
    genes: [
      {
        symbol: "CRBN",
        name: "cereblon",
        hgnc: "HGNC:30185",
        ensembl: "ENSG00000113851",
        uniprot: "Q96SW2",
        entrez: "51185",
        locus: "3p26.2"
      }
    ]
  },
  top1: {
    genes: [
      {
        symbol: "TOP1",
        name: "DNA topoisomerase I",
        hgnc: "HGNC:11986",
        ensembl: "ENSG00000198900",
        uniprot: "P11387",
        entrez: "7150",
        locus: "20q12"
      }
    ]
  },
  top2a: {
    genes: [
      {
        symbol: "TOP2A",
        name: "DNA topoisomerase II alpha",
        hgnc: "HGNC:11989",
        ensembl: "ENSG00000131747",
        uniprot: "P11388",
        entrez: "7153",
        locus: "17q21.2"
      }
    ]
  },
  tyms: {
    genes: [
      {
        symbol: "TYMS",
        name: "thymidylate synthetase",
        hgnc: "HGNC:12441",
        ensembl: "ENSG00000176890",
        uniprot: "P04818",
        entrez: "7298",
        locus: "18p11.32"
      }
    ]
  },
  dhfr: {
    genes: [
      {
        symbol: "DHFR",
        name: "dihydrofolate reductase",
        hgnc: "HGNC:2861",
        ensembl: "ENSG00000228716",
        uniprot: "P00374",
        entrez: "1719",
        locus: "5q14.1"
      }
    ]
  },
  gnrhr: {
    genes: [
      {
        symbol: "GNRHR",
        name: "gonadotropin releasing hormone receptor",
        hgnc: "HGNC:4421",
        ensembl: "ENSG00000109163",
        uniprot: "P30968",
        entrez: "2798",
        locus: "4q13.2"
      }
    ]
  },
  xpo1: {
    genes: [
      {
        symbol: "XPO1",
        name: "exportin 1",
        hgnc: "HGNC:12825",
        ensembl: "ENSG00000082898",
        uniprot: "O14980",
        entrez: "7514",
        locus: "2p15"
      }
    ]
  },
  slamf7: {
    genes: [
      {
        symbol: "SLAMF7",
        name: "SLAM family member 7",
        hgnc: "HGNC:21394",
        ensembl: "ENSG00000026751",
        uniprot: "Q9NQ25",
        entrez: "57823",
        locus: "1q23.3"
      }
    ]
  },
  tubulin: {
    genes: [
      {
        symbol: "TUBB",
        name: "tubulin beta class I",
        hgnc: "HGNC:20778",
        ensembl: "ENSG00000196230",
        uniprot: "P07437",
        entrez: "203068",
        locus: "6p21.33"
      }
    ]
  },
  dnmt1: {
    genes: [
      {
        symbol: "DNMT1",
        name: "DNA methyltransferase 1",
        hgnc: "HGNC:2976",
        ensembl: "ENSG00000130816",
        uniprot: "P26358",
        entrez: "1786",
        locus: "19p13.2"
      }
    ]
  },
  rrm1: {
    genes: [
      {
        symbol: "RRM1",
        name: "ribonucleotide reductase catalytic subunit M1",
        hgnc: "HGNC:10451",
        ensembl: "ENSG00000167325",
        uniprot: "P23921",
        entrez: "6240",
        locus: "11p15.4"
      }
    ]
  },
  pik3cd: {
    genes: [
      {
        symbol: "PIK3CD",
        name: "phosphatidylinositol-4,5-bisphosphate 3-kinase catalytic subunit delta",
        hgnc: "HGNC:8977",
        ensembl: "ENSG00000171608",
        uniprot: "O00329",
        entrez: "5293",
        locus: "1p36.22"
      }
    ]
  },
  rara: {
    genes: [
      {
        symbol: "RARA",
        name: "retinoic acid receptor alpha",
        hgnc: "HGNC:9864",
        ensembl: "ENSG00000131759",
        uniprot: "P10276",
        entrez: "5914",
        locus: "17q21.2"
      }
    ]
  },
  "fgfr3-receptor": {
    genes: [
      {
        symbol: "FGFR3",
        name: "fibroblast growth factor receptor 3",
        hgnc: "HGNC:3690",
        ensembl: "ENSG00000068078",
        uniprot: "P22607",
        entrez: "2261",
        locus: "4p16.3"
      }
    ]
  },
  pdgfrb: {
    genes: [
      {
        symbol: "PDGFRB",
        name: "platelet derived growth factor receptor beta",
        hgnc: "HGNC:8804",
        ensembl: "ENSG00000113721",
        uniprot: "P09619",
        entrez: "5159",
        locus: "5q32"
      }
    ]
  },
  src: {
    genes: [
      {
        symbol: "SRC",
        name: "SRC proto-oncogene, non-receptor tyrosine kinase",
        hgnc: "HGNC:11283",
        ensembl: "ENSG00000197122",
        uniprot: "P12931",
        entrez: "6714",
        locus: "20q11.23"
      }
    ]
  },
  ifnar1: {
    genes: [
      {
        symbol: "IFNAR1",
        name: "interferon alpha and beta receptor subunit 1",
        hgnc: "HGNC:5432",
        ensembl: "ENSG00000142166",
        uniprot: "P17181",
        entrez: "3454",
        locus: "21q22.11"
      }
    ]
  },
  csf3r: {
    genes: [
      {
        symbol: "CSF3R",
        name: "colony stimulating factor 3 receptor",
        hgnc: "HGNC:2439",
        ensembl: "ENSG00000119535",
        uniprot: "Q99062",
        entrez: "1441",
        locus: "1p34.3"
      }
    ]
  },
  htr3a: {
    genes: [
      {
        symbol: "HTR3A",
        name: "5-hydroxytryptamine receptor 3A",
        hgnc: "HGNC:5297",
        ensembl: "ENSG00000166736",
        uniprot: "P46098",
        entrez: "3359",
        locus: "11q23.2"
      }
    ]
  },
  tacr1: {
    genes: [
      {
        symbol: "TACR1",
        name: "tachykinin receptor 1",
        hgnc: "HGNC:11526",
        ensembl: "ENSG00000115353",
        uniprot: "P25103",
        entrez: "6869",
        locus: "2p12"
      }
    ]
  },
  epor: {
    genes: [
      {
        symbol: "EPOR",
        name: "erythropoietin receptor",
        hgnc: "HGNC:3416",
        ensembl: "ENSG00000187266",
        uniprot: "P19235",
        entrez: "2057",
        locus: "19p13.2"
      }
    ]
  },
  axl: {
    genes: [
      {
        symbol: "AXL",
        name: "AXL receptor tyrosine kinase",
        hgnc: "HGNC:905",
        ensembl: "ENSG00000167601",
        uniprot: "P30530",
        entrez: "558",
        locus: "19q13.2"
      }
    ]
  },
  "glucocorticoid-receptor": {
    genes: [
      {
        symbol: "NR3C1",
        name: "nuclear receptor subfamily 3 group C member 1",
        hgnc: "HGNC:7978",
        ensembl: "ENSG00000113580",
        uniprot: "P04150",
        entrez: "2908",
        locus: "5q31.3"
      }
    ]
  },
  "gamma-secretase": {
    genes: [
      {
        symbol: "PSEN1",
        name: "presenilin 1",
        hgnc: "HGNC:9508",
        ensembl: "ENSG00000080815",
        uniprot: "P49768",
        entrez: "5663",
        locus: "14q24.2"
      }
    ]
  },
  fgfr1: {
    genes: [
      {
        symbol: "FGFR1",
        name: "fibroblast growth factor receptor 1",
        hgnc: "HGNC:3688",
        ensembl: "ENSG00000077782",
        uniprot: "P11362",
        entrez: "2260",
        locus: "8p11.23"
      }
    ]
  },
  erbb4: {
    genes: [
      {
        symbol: "ERBB4",
        name: "erb-b2 receptor tyrosine kinase 4",
        hgnc: "HGNC:3432",
        ensembl: "ENSG00000178568",
        uniprot: "Q15303",
        entrez: "2066",
        locus: "2q34"
      }
    ]
  },
  ada: {
    genes: [{ symbol: "ADA", name: "adenosine deaminase", hgnc: "HGNC:186", ensembl: "ENSG00000196839", uniprot: "P00813", entrez: "100", locus: "20q13.12" }],
  },
  pgr: {
    genes: [{ symbol: "PGR", name: "progesterone receptor", hgnc: "HGNC:8910", ensembl: "ENSG00000082175", uniprot: "P06401", entrez: "5241", locus: "11q22.1" }],
  },
  eef2: {
    genes: [{"symbol":"EEF2","name":"eukaryotic translation elongation factor 2","hgnc":"HGNC:3214","ensembl":"ENSG00000167658","uniprot":"P13639","entrez":"1938","locus":"19p13.3"}],
  },
  fkbp12: {
    genes: [{"symbol":"FKBP1A","name":"FKBP prolyl isomerase 1A","hgnc":"HGNC:3711","ensembl":"ENSG00000088832","uniprot":"P62942","entrez":"2280","locus":"20p13"}],
  },
  dnmt3a: {
    genes: [{"symbol":"DNMT3A","name":"DNA methyltransferase 3 alpha","hgnc":"HGNC:2978","ensembl":"ENSG00000119772","uniprot":"Q9Y6K1","entrez":"1788","locus":"2p23.3"}],
  },
  gart: {
    genes: [{"symbol":"GART","name":"phosphoribosylglycinamide formyltransferase, phosphoribosylglycinamide synthetase, phosphoribosylaminoimidazole synthetase","hgnc":"HGNC:4163","ensembl":"ENSG00000159131","uniprot":"P22102","entrez":"2618","locus":"21q22.11"}],
  },
  tlr7: {
    genes: [{"symbol":"TLR7","name":"toll like receptor 7","hgnc":"HGNC:15631","ensembl":"ENSG00000196664","uniprot":"Q9NYK1","entrez":"51284","locus":"Xp22.2"}],
  },
  pap: {
    genes: [{"symbol":"ACP3","name":"acid phosphatase 3","hgnc":"HGNC:125","ensembl":"ENSG00000014257","uniprot":"P15309","entrez":"55","locus":"3q22.1"}],
  },
  ron: {
    genes: [{"symbol":"MST1R","name":"macrophage stimulating 1 receptor","hgnc":"HGNC:7381","ensembl":"ENSG00000164078","uniprot":"Q04912","entrez":"4486","locus":"3p21.31"}],
  },
  ddr2: {
    genes: [{"symbol":"DDR2","name":"discoidin domain receptor tyrosine kinase 2","hgnc":"HGNC:2731","ensembl":"ENSG00000162733","uniprot":"Q16832","entrez":"4921","locus":"1q23.3"}],
  },
  epha2: {
    genes: [{"symbol":"EPHA2","name":"EPH receptor A2","hgnc":"HGNC:3386","ensembl":"ENSG00000142627","uniprot":"P29317","entrez":"1969","locus":"1p36.13"}],
  },
  raf1: {
    genes: [{"symbol":"RAF1","name":"Raf-1 proto-oncogene, serine/threonine kinase","hgnc":"HGNC:9829","ensembl":"ENSG00000132155","uniprot":"P04049","entrez":"5894","locus":"3p25.2"}],
  },
  pkc: {
    genes: [{"symbol":"PRKCA","name":"protein kinase C alpha","hgnc":"HGNC:9393","ensembl":"ENSG00000154229","uniprot":"P17252","entrez":"5578","locus":"17q24.2"}],
  },
  cox2: {
    genes: [{"symbol":"PTGS2","name":"prostaglandin-endoperoxide synthase 2","hgnc":"HGNC:9605","ensembl":"ENSG00000073756","uniprot":"P35354","entrez":"5743","locus":"1q31.1"}],
  },
  tshr: {
    genes: [{"symbol":"TSHR","name":"thyroid stimulating hormone receptor","hgnc":"HGNC:12373","ensembl":"ENSG00000165409","uniprot":"P16473","entrez":"7253","locus":"14q24-q31"}],
  },
  igf1r: {
    genes: [{"symbol":"IGF1R","name":"insulin like growth factor 1 receptor","hgnc":"HGNC:5465","ensembl":"ENSG00000140443","uniprot":"P08069","entrez":"3480","locus":"15q26.3"}],
  },
  tie2: {
    genes: [{"symbol":"TEK","name":"TEK receptor tyrosine kinase","hgnc":"HGNC:11724","ensembl":"ENSG00000120156","uniprot":"Q02763","entrez":"7010","locus":"9p21.2"}],
  },
  il11ra: {
    genes: [{"symbol":"IL11RA","name":"interleukin 11 receptor subunit alpha","hgnc":"HGNC:5967","ensembl":"ENSG00000137070","uniprot":"Q14626","entrez":"3590","locus":"9p13.3"}],
  },
  csf2ra: {
    genes: [{"symbol":"CSF2RA","name":"colony stimulating factor 2 receptor subunit alpha","hgnc":"HGNC:2435","ensembl":"ENSG00000198223","uniprot":"P15509","entrez":"1438","locus":"Xp22.32 and Yp11.3"}],
  },
  lyn: {
    genes: [{"symbol":"LYN","name":"LYN proto-oncogene, Src family tyrosine kinase","hgnc":"HGNC:6735","ensembl":"ENSG00000254087","uniprot":"P07948","entrez":"4067","locus":"8q12.1"}],
  },
  hck: {
    genes: [{"symbol":"HCK","name":"HCK proto-oncogene, Src family tyrosine kinase","hgnc":"HGNC:4840","ensembl":"ENSG00000101336","uniprot":"P08631","entrez":"3055","locus":"20q11.21"}],
  },
  ptk6: {
    genes: [{"symbol":"PTK6","name":"protein tyrosine kinase 6","hgnc":"HGNC:9617","ensembl":"ENSG00000101213","uniprot":"Q13882","entrez":"5753","locus":"20q13.33"}],
  },
  frk: {
    genes: [{"symbol":"FRK","name":"fyn related Src family tyrosine kinase","hgnc":"HGNC:3955","ensembl":"ENSG00000111816","uniprot":"P42685","entrez":"2444","locus":"6q22.1"}],
  },
  xdh: {
    genes: [{"symbol":"XDH","name":"xanthine dehydrogenase","hgnc":"HGNC:12805","ensembl":"ENSG00000158125","uniprot":"P47989","entrez":"7498","locus":"2p23.1"}],
  },
  txnrd1: {
    genes: [{"symbol":"TXNRD1","name":"thioredoxin reductase 1","hgnc":"HGNC:12437","ensembl":"ENSG00000198431","uniprot":"Q16881","entrez":"7296","locus":"12q23.3"}],
  },
  gsr: {
    genes: [{"symbol":"GSR","name":"glutathione-disulfide reductase","hgnc":"HGNC:4623","ensembl":"ENSG00000104687","uniprot":"P00390","entrez":"2936","locus":"8p12"}],
  },
  pola1: {
    genes: [{"symbol":"POLA1","name":"DNA polymerase alpha 1, catalytic subunit","hgnc":"HGNC:9173","ensembl":"ENSG00000101868","uniprot":"P09884","entrez":"5422","locus":"Xp22.11-p21.3"}],
  },
  cyp11a1: {
    genes: [{"symbol":"CYP11A1","name":"cytochrome P450 family 11 subfamily A member 1","hgnc":"HGNC:2590","ensembl":"ENSG00000140459","uniprot":"P05108","entrez":"1583","locus":"15q24.1"}],
  },
  srd5a2: {
    genes: [{"symbol":"SRD5A2","name":"steroid 5 alpha-reductase 2","hgnc":"HGNC:11285","ensembl":"ENSG00000277893","uniprot":"P31213","entrez":"6716","locus":"2p23.1"}],
  },
  drd2: {
    genes: [{"symbol":"DRD2","name":"dopamine receptor D2","hgnc":"HGNC:3023","ensembl":"ENSG00000149295","uniprot":"P14416","entrez":"1813","locus":"11q23.2"}],
  },
  oprm1: {
    genes: [{"symbol":"OPRM1","name":"opioid receptor mu 1","hgnc":"HGNC:8156","ensembl":"ENSG00000112038","uniprot":"P35372","entrez":"4988","locus":"6q25.2"}],
  },
  cnr1: {
    genes: [{"symbol":"CNR1","name":"cannabinoid receptor 1","hgnc":"HGNC:2159","ensembl":"ENSG00000118432","uniprot":"P21554","entrez":"1268","locus":"6q15"}],
  },
  tph1: {
    genes: [{"symbol":"TPH1","name":"tryptophan hydroxylase 1","hgnc":"HGNC:12008","ensembl":"ENSG00000129167","uniprot":"P17752","entrez":"7166","locus":"11p15.1"}],
  },
  impdh2: {
    genes: [{"symbol":"IMPDH2","name":"inosine monophosphate dehydrogenase 2","hgnc":"HGNC:6053","ensembl":"ENSG00000178035","uniprot":"P12268","entrez":"3615","locus":"3p21.31"}],
  },
  // Wave 5 targets (targets-wave-soc.ts): HGNC REST read 22 Sep 2026; ChEMBL ids to be filled by the next scripts/fetch-xrefs.ts run.
  nras: {
    genes: [{"symbol":"NRAS","name":"NRAS proto-oncogene, GTPase","hgnc":"HGNC:7989","ensembl":"ENSG00000213281","uniprot":"P01111","entrez":"4893","cosmic":"NRAS","omim":"164790","locus":"1p13.2"}],
  },
  cd28: {
    genes: [{"symbol":"CD28","name":"CD28 molecule","hgnc":"HGNC:1653","ensembl":"ENSG00000178562","uniprot":"P10747","entrez":"940","omim":"186760","locus":"2q33.2"}],
  },
  "hla-a": {
    genes: [{"symbol":"HLA-A","name":"major histocompatibility complex, class I, A","hgnc":"HGNC:4931","ensembl":"ENSG00000206503","uniprot":"P04439","entrez":"3105","cosmic":"HLA-A","omim":"142800","locus":"6p22.1"}],
  },
  mpl: {
    genes: [{"symbol":"MPL","name":"MPL proto-oncogene, thrombopoietin receptor","hgnc":"HGNC:7217","ensembl":"ENSG00000117400","uniprot":"P40238","entrez":"4352","cosmic":"MPL","omim":"159530","locus":"1p34.2"}],
  },
  shp2: {
    genes: [{"symbol":"PTPN11","name":"protein tyrosine phosphatase non-receptor type 11","hgnc":"HGNC:9644","ensembl":"ENSG00000179295","uniprot":"Q06124","entrez":"5781","cosmic":"PTPN11","omim":"176876","locus":"12q24.13"}],
  },
  stat5: {
    genes: [{"symbol":"STAT5A","name":"signal transducer and activator of transcription 5A","hgnc":"HGNC:11366","ensembl":"ENSG00000126561","uniprot":"P42229","entrez":"6776","omim":"601511","locus":"17q21.2"}, {"symbol":"STAT5B","name":"signal transducer and activator of transcription 5B","hgnc":"HGNC:11367","ensembl":"ENSG00000173757","uniprot":"P51692","entrez":"6777","cosmic":"STAT5B","omim":"604260","locus":"17q21.2"}],
  },
  ikzf1: {
    genes: [{"symbol":"IKZF1","name":"IKAROS family zinc finger 1","hgnc":"HGNC:13176","ensembl":"ENSG00000185811","uniprot":"Q13422","entrez":"10320","cosmic":"IKZF1","omim":"603023","locus":"7p12.2"}],
  },
  jak1: {
    genes: [{"symbol":"JAK1","name":"Janus kinase 1","hgnc":"HGNC:6190","ensembl":"ENSG00000162434","uniprot":"P23458","entrez":"3716","cosmic":"JAK1","omim":"147795","locus":"1p31.3"}],
  },
  cd80: {
    genes: [{"symbol":"CD80","name":"CD80 molecule","hgnc":"HGNC:1700","ensembl":"ENSG00000121594","uniprot":"P33681","entrez":"941","omim":"112203","locus":"3q13.33"}],
  },
  abl1: {
    genes: [{"symbol":"ABL1","name":"ABL proto-oncogene 1, non-receptor tyrosine kinase","hgnc":"HGNC:76","ensembl":"ENSG00000097007","uniprot":"P00519","entrez":"25","cosmic":"ABL1","omim":"189980","locus":"9q34.12"}],
  },
  fak: {
    genes: [{"symbol":"PTK2","name":"protein tyrosine kinase 2","hgnc":"HGNC:9611","ensembl":"ENSG00000169398","uniprot":"Q05397","entrez":"5747","omim":"600758","locus":"8q24.3"}],
  },
  ikzf3: {
    genes: [{"symbol":"IKZF3","name":"IKAROS family zinc finger 3","hgnc":"HGNC:13178","ensembl":"ENSG00000161405","uniprot":"Q9UKT9","entrez":"22806","cosmic":"IKZF3","omim":"606221","locus":"17q12-q21.1"}],
  },
  ptch1: {
    genes: [{"symbol":"PTCH1","name":"patched 1","hgnc":"HGNC:9585","ensembl":"ENSG00000185920","uniprot":"Q13635","entrez":"5727","cosmic":"PTCH1","omim":"601309","locus":"9q22.32"}],
  },
  cd137: {
    genes: [{"symbol":"TNFRSF9","name":"TNF receptor superfamily member 9","hgnc":"HGNC:11924","ensembl":"ENSG00000049249","uniprot":"Q07011","entrez":"3604","omim":"602250","locus":"1p36.23"}],
  },
  hif1a: {
    genes: [{"symbol":"HIF1A","name":"hypoxia inducible factor 1 subunit alpha","hgnc":"HGNC:4910","ensembl":"ENSG00000100644","uniprot":"Q16665","entrez":"3091","cosmic":"HIF1A","omim":"603348","locus":"14q23.2"}],
  },
  ido1: {
    genes: [{"symbol":"IDO1","name":"indoleamine 2,3-dioxygenase 1","hgnc":"HGNC:6059","ensembl":"ENSG00000131203","uniprot":"P14902","entrez":"3620","omim":"147435","locus":"8p11.21"}],
  },
  brd4: {
    genes: [{"symbol":"BRD4","name":"bromodomain containing 4","hgnc":"HGNC:13575","ensembl":"ENSG00000141867","uniprot":"O60885","entrez":"23476","cosmic":"BRD4","omim":"608749","locus":"19p13.12"}],
  },
  irf4: {
    genes: [{"symbol":"IRF4","name":"interferon regulatory factor 4","hgnc":"HGNC:6119","ensembl":"ENSG00000137265","uniprot":"Q15306","entrez":"3662","cosmic":"IRF4","omim":"601900","locus":"6p25.3"}],
  },
  b7h4: {
    genes: [{"symbol":"VTCN1","name":"V-set domain containing T cell activation inhibitor 1","hgnc":"HGNC:28873","ensembl":"ENSG00000134258","uniprot":"Q7Z7D3","entrez":"79679","omim":"608162","locus":"1p13.1-p12"}],
  },
  tet2: {
    genes: [{"symbol":"TET2","name":"tet methylcytosine dioxygenase 2","hgnc":"HGNC:25941","ensembl":"ENSG00000168769","uniprot":"Q6N021","entrez":"54790","cosmic":"TET2","omim":"612839","locus":"4q24"}],
  },
  nf1: {
    genes: [{"symbol":"NF1","name":"neurofibromin 1","hgnc":"HGNC:7765","ensembl":"ENSG00000196712","uniprot":"P21359","entrez":"4763","cosmic":"NF1","omim":"613113","locus":"17q11.2"}],
  },
  acvr1: {
    genes: [{"symbol":"ACVR1","name":"activin A receptor type 1","hgnc":"HGNC:171","ensembl":"ENSG00000115170","uniprot":"Q04771","entrez":"90","cosmic":"ACVR1","omim":"102576","locus":"2q24.1"}],
  },
  hoxa9: {
    genes: [{"symbol":"HOXA9","name":"homeobox A9","hgnc":"HGNC:5109","ensembl":"ENSG00000078399","uniprot":"P31269","entrez":"3205","cosmic":"HOXA9","omim":"142956","locus":"7p15.2"}],
  },
  meis1: {
    genes: [{"symbol":"MEIS1","name":"Meis homeobox 1","hgnc":"HGNC:7000","ensembl":"ENSG00000143995","uniprot":"O00470","entrez":"4211","omim":"601739","locus":"2p14"}],
  },
  bim: {
    genes: [{"symbol":"BCL2L11","name":"BCL2 like 11","hgnc":"HGNC:994","ensembl":"ENSG00000153094","uniprot":"O43521","entrez":"10018","omim":"603827","locus":"2q13"}],
  },
  bax: {
    genes: [{"symbol":"BAX","name":"BCL2 associated X, apoptosis regulator","hgnc":"HGNC:959","ensembl":"ENSG00000087088","uniprot":"Q07812","entrez":"581","cosmic":"BAX","omim":"600040","locus":"19q13.33"}],
  },
};
